### ISSUE TITLE
On Slug Change Event feature

### ISSUE THREAD

**Issue by Ardakilic** [cviebrock/eloquent-sluggable#101]
Hello,

First of all, thanks for maintaining this plugin, this saves a great hassle!

I am using sluggable on L4, on my model `on_update` parameter set as `true`, and I want to store old slugs and redirect them to new ones.

What I've been thinking is that something like a model event, something like `onSlugChange` which I can catch old and new slug and work with them.

How can I achieve this?

Thanks in advance,

**Comment by cviebrock** [comment]
Yup, I could certainly add some events into the package, so that you can do stuff when a slug is set, or changes, etc..  I'll add it to my todo list.

Thanks for the suggestion!
