### ISSUE TITLE
Using cache can lead to dupes

### ISSUE THREAD

**Issue by yswery** [cviebrock/eloquent-sluggable#102]
So if you have cache enabled I see that this can leade to duplicate slugs even if unique is selected.

in the method ``makeSlugUnique()``:

```
                // if using the cache, check if we have an entry already instead
		// of querying the database
		if ( $use_cache )
		{
			$increment = \Cache::tags('sluggable')->get($slug);
			if ( $increment === null )
			{
				\Cache::tags('sluggable')->put($slug, 0, $use_cache);
			}
			else
			{
				\Cache::tags('sluggable')->put($slug, ++$increment, $use_cache);
				$slug .= $separator . $increment;
			}
			return $slug;
		}
```

As you can see here in line ``\Cache::tags('sluggable')->put($slug, 0, $use_cache);`` we are setting the slug to be cached for the config time (lets say.... 10 mins) and as soon as that 10 mins are over this means that that slug is no longer in cache. Which means even though we have it in our DB (which we use as the main source) we can have multiple slugs?

am I correct saying this?

**Comment by cviebrock** [comment]
I'm not sure if you are correct or not ... but I do admit that the whole cache stuff is a bit of a mess.  I should probably pull it out of the code and rethink the implementation a bit better.

I think it's probably safe to say, avoid using `'use_cache' => true` for now. :(
