### ISSUE TITLE
illuminate/support not working

### ISSUE THREAD

**Issue by Goddard** [cviebrock/eloquent-sluggable#106]
illuminate support is giving me errors when trying to update/install... laravel 5

**Comment by Goddard** [comment]
- don't install illuminate/support v4.2.9|don't install laravel/framework v5.0.5

**Comment by cviebrock** [comment]
Are you using another package that requires `illuminate/support:4.2.9`? Because Sluggable should only be asking for `5.x` things.

**Comment by Goddard** [comment]
I think I installed the wrong version, but I attempted to follow the instructions.  I am new to laravel.

**Comment by voodooattack** [comment]
Getting the same error here.
```
  Problem 1
    - cviebrock/eloquent-sluggable 2.0.5 requires illuminate/support 4.* -> no matching package found.
    - cviebrock/eloquent-sluggable 2.0.4 requires illuminate/support 4.* -> no matching package found.
    - cviebrock/eloquent-sluggable 2.0.3 requires illuminate/support 4.* -> no matching package found.
    - cviebrock/eloquent-sluggable 2.0.2 requires illuminate/support 4.* -> no matching package found.
    - cviebrock/eloquent-sluggable 2.0.1 requires illuminate/support 4.* -> no matching package found.
    - cviebrock/eloquent-sluggable 2.0.0 requires illuminate/support 4.* -> no matching package found.
```

**Comment by voodooattack** [comment]
I solved this temporarily by manually adding this to composer.json:

```
"cviebrock/eloquent-sluggable": "dev-master"
```

**Comment by cviebrock** [comment]
If you are using Laravel 5, then you need `"cviebrock/eloquent-sluggable": "~3.*"` ... specifically the `3.0.0-alpha` tag.
