### ISSUE TITLE
Localizing or Translating Slugs?

### ISSUE THREAD

**Issue by broszies** [cviebrock/eloquent-sluggable#109]
Hi,
I am using Dimsav\Translatable to localize my application. I would like to have localized slugs, too.

I have installed Sluggable, appended the Model and the database, but get the error "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'slug' in 'field list' (SQL: select `slug`, `id` from `units` where `slug` LIKE test-unit%) "

Could this be because the Model attempts to save the slug in the "units" table instead of the unit_translations-table?

Disclaimer: I am not very experienced with PHP/Laravel, please excuse me if I am asking the obvious.

Regards

Wolf

The Model:
----------------
    use \Dimsav\Translatable\Translatable;
    use Cviebrock\EloquentSluggable\SluggableInterface;
    use Cviebrock\EloquentSluggable\SluggableTrait;

class Unit extends Eloquent implements SluggableInterface {

// All functions related to sluggable

    use SluggableTrait;
    protected $sluggable = array(
        'build_from' => 'name',
        'save_to'    => 'slug',
    );

// All functions related to translation

    protected $fillable = ['name', 'description', 'slug'];

    public $translatedAttributes = array('name', 'description', 'slug');
}

the Controller:

	public function store()
	   {
      //Store created unit in database
      $input = Input::all();
      $validation = Validator::make($input, Unit::$rules);
        if ($validation->passes())
            {
            Unit::create($input);
            return Redirect::route('units.index')
            ->with('message', trans('units.success_create'));
            }
        return Redirect::route('units.create')
            ->withInput()
            ->withErrors($validation)
            ->with('message', trans('validation.error'));
	   }

the migration for unit_translations:
------------------
	public function up()
	   {
        Schema::create('unit_translations', function(Blueprint $table)
        {
            $table->increments('id');
            
            // Translatable attributes
            $table->string('name');
            $table->string('description');
            $table->string('slug')->index();
                             
            // Translatable attributes
            
            $table->integer('unit_id')->unsigned()->index();
            $table->foreign('unit_id')->references('id')->on('units')->onDelete('cascade');
            $table->string('locale')->index();
            $table->unique(['unit_id', 'locale']);
            $table->timestamps();
        });
	}

**Comment by cviebrock** [comment]
My package works by automatically generating a slug based on the model attributes when you call `$model->save()`.  I'm not sure how (or even if) Dimsav\Translatable automatically creates the translatable versions of model attributes.

I'm not 100% sure if this would work, but looking at [his project](https://github.com/dimsav/laravel-translatable), I would think you just need to make the translated entity models sluggable as well, e.g.:

```php
// models/Country.php
class Country extends Eloquent implements Cviebrock\EloquentSluggable\SluggableInterface {

    use Cviebrock\EloquentSluggable\SluggableTrait;
    use \Dimsav\Translatable\Translatable;

    public $translatedAttributes = array('name');
    protected $fillable = ['iso', 'name'];
    protected $sluggable = [
        'build_from' => 'name',
        'save_to'    => 'slug',
    ];
}

// models/CountryTranslation.php
class CountryTranslation extends Eloquent implements Cviebrock\EloquentSluggable\SluggableInterface {
    use Cviebrock\EloquentSluggable\SluggableTrait;

    public $timestamps = false;
    protected $fillable = ['name'];
    protected $sluggable = [
        'build_from' => 'name',
        'save_to'    => 'slug',
    ];

}
```

As long as the main model and the Translation model both implement sluggable, and both have the same sluggable configuration, I think that will do what you are expecting.

**Comment by mauro-moreno** [comment]
I had the same question today and the "name" attribute only exists in the CountryTranslation model so you don't need to implement the sluggable functionality in Country, just in the translation. So it would end like this:
```php
// models/Country.php
class Country extends Eloquent {

    use \Dimsav\Translatable\Translatable;

    public $translatedAttributes = ['name', 'slug'];
    protected $fillable = ['iso', 'name'];
}

// models/CountryTranslation.php
class CountryTranslation extends Eloquent implements Cviebrock\EloquentSluggable\SluggableInterface {
    use Cviebrock\EloquentSluggable\SluggableTrait;

    public $timestamps = false;
    protected $fillable = ['name'];
    protected $sluggable = [
        'build_from' => 'name',
        'save_to'    => 'slug',
    ];

}
```

**Comment by cviebrock** [comment]
That makes even more sense.  Closing this now, but feel free to open again if you are still having issues @broszies

**Comment by nWidart** [comment]
Hello,

I'm having the same 'issue', but the method explained above by @mauro-moreno doesn't seem to do it for me.

Here's my 'base' entity:

``` php
<?php namespace Modules\Product\Domain\Entities;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use Translatable;

    protected $table = 'product__categories';
    public $translatedAttributes = ['name', 'slug', 'description'];
    protected $fillable = ['parent_id', 'name', 'slug', 'description'];
}
```

And my translatable model:

```php
<?php namespace Modules\Product\Domain\Entities;

use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;
use Illuminate\Database\Eloquent\Model;

class CategoryTranslation extends Model implements SluggableInterface
{
    use SluggableTrait;

    public $timestamps = false;
    protected $fillable = ['name', 'slug', 'description'];
    protected $table = 'product__category_translations';
    protected $sluggable = array(
        'build_from' => 'name',
        'save_to' => 'slug',
    );
}
```

When saving my Category, the slug column in the `product__category_translations` doesn't get set.

Did I miss something ?

Thanks,

**Comment by mauro-moreno** [comment]
Are you using a "non standard" relationship Id? Translatable has a "translationForeignKey" attribute that you should use in the Category model if so.

**Comment by nWidart** [comment]
Hm I use the standard foreign key.

**Comment by mauro-moreno** [comment]
I think that the models are OK so I would check the queries, maybe your problem is in your database definition.

**Comment by nWidart** [comment]
Hm possibly, but doubtful since I have the usual migration from the Translatable package.

Here's the db definition (`product__` is the prefix)
``` sql
CREATE TABLE `product__categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) unsigned DEFAULT NULL,
  `order` int(11) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `product__category_translations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci NOT NULL,
  `category_id` int(10) unsigned NOT NULL,
  `locale` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `product__category_translations_category_id_locale_unique` (`category_id`,`locale`),
  KEY `product__category_translations_locale_index` (`locale`),
  CONSTRAINT `product__category_translations_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `product__categories` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Comment by KelvynCarbone** [comment]
try this:

    public function sluggable () {

                return [
                    'tag_slug' => [
                        'source' => 'tag'
                    ]
                ];

            }

**Comment by KelvynCarbone** [comment]
public function sluggable () {

                return [
                    'name_of_your_custom_column' => [
                        'source' => 'name_column_source'
                    ]
                ];

            }
