### ISSUE TITLE
Cant create slug for greek characters (utf8 support)

### ISSUE THREAD

**Issue by mosky7** [cviebrock/eloquent-sluggable#110]
When the record is with greek characters the slug becomes empty quotes

**Comment by mosky7** [comment]
ok i managed to fix ti with a custom slugger
1. Go to vendor/cviebrock/eloquent-sluggable/src/config/config.php
2. Change 'method' (line 56) to: 
'method' => function($string, $sep = '-') {
	$flip = $sep == '-' ? '_' : '-';
	$string = preg_replace('!['.preg_quote($flip).']+!u', $sep, $string);
	$string = preg_replace('![^'.preg_quote($sep).'\pL\pN\s]+!u', '', mb_strtolower($string));
	$string = preg_replace('!['.preg_quote($sep).'\s]+!u', $sep, $string);
	return trim($string, $sep);
	},

(ref: http://killerwhalesoft.com/blog/make-laravel-slug-support-utf8-characters/)

**Comment by mkwsra** [comment]
+1, @cviebrock  This is really so much important, otherwise str_slug() helper function is doing more than enough, but I need UTF-8 support too for non-latin languages.

Thanks in advance

**Comment by cviebrock** [comment]
You can do this already via the `method` configuration or via a custom `generateSlug` method in your model.

I agree that the default behaviour -- that UTF-8 strings aren't supported -- is a problem, and I do plan to address it (probably using [cocur/slugify](https://github.com/cocur/slugify).  But in the meantime, you can get around it with @mosky7 's solution above, or your own functions.

**Comment by mkwsra** [comment]
:+1: Thanks
