### ISSUE TITLE
Can't create slug if I don't define `$sluggable` in model

### ISSUE THREAD

**Issue by vinitkh** [cviebrock/eloquent-sluggable#111]
Hi,

I have defined `build_from` column value in config file but still I have to define `$sluggable` property in my model everytime. If I have many models and in each model I need same `$sluggable` attribute, then I have to define in each model (I don't want to define this in my parent model class and I want that it will take from config.).

**Comment by cviebrock** [comment]
A recent PR should have fixed this for you.  Do you mind testing again with `dev-master` and letting me know if it now works?
