### ISSUE TITLE
array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by Dancia** [cviebrock/eloquent-sluggable#113]
Error:
    ErrorException in SluggableTrait.php line 205:
    array_merge(): Argument #2 is not an array

While tryint to create news:

    public function store(NewsRequest $request)
    {
    $newsItem = new News($request->all());

    Auth::user()->news()->save($newsItem); <-- this triggers error.

    flash()->success('News have been created');

    return redirect('admincp/news');
	}

SluugableTrait.php line 205 is:
    		$this->sluggable = array_merge( $config, $this->sluggable );

Any ideas how to fix this? Im new to eloquent-sluggable.

**Comment by Dancia** [comment]
Brain fart, fixed.

**Comment by cviebrock** [comment]
:wink ... was it forgetting to add the trait on your News model?

**Comment by Dancia** [comment]
No, I accidently added  ['build_from' => 'title', 'save_to'    => 'slug'] to protected $fillable, not protected $sluggable.

**Comment by somratcste** [comment]
here is a problem laravel 5.4 how to fix that ??

**Comment by cviebrock** [comment]
Can you be more specific, @somratcste ?  Also, if it's not the same error message, please open a new issue.
