### ISSUE TITLE
"php artisan sluggable:table tablename" tries to create migration to old laravel path?

### ISSUE THREAD

**Issue by blomdahldaniel** [cviebrock/eloquent-sluggable#114]
Hi!
Great plugin! But i think i might have stumbled upon an error:
when i run "php artisan sluggable:table tablename"
i get this:
`[ErrorException]
file_put_contents(/home/luke/Desktop/learninglaravel/app/database/migrations/2015_03_06_174711_add_sluggable_columns.php): failed to open stream: No such file or directory`

It seems like the command tires to write to the old laravel 4 structure.
Because now /database is not inside app/

What do you think? Am I doing things wrong?

I have the 3.0.0-alpha installed

**Comment by cviebrock** [comment]
I'm looking at my code and the relevant line would be `SluggableTableCommand.php`, line 80:

```php
$path = $this->getMigrationPath();
```

That's a method on [Illuminate\Database\Console\Migrations\BaseCommand](https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Console/Migrations/BaseCommand.php), which just returns:

```php
return $this->laravel['path.database'].'/migrations';
```

So ... I'm not sure what to suggest.  Are you changing your paths in anyway?

**Comment by WillyReyno** [comment]
I just got the same problem, and I didn't change my path!

**Comment by pathros** [comment]
same problem here. Somebody told me it was because the table name was icorrect but that table does exist in my database!

**Comment by darwinmanchola** [comment]
Aqui tienes la solucion https://github.com/cviebrock/eloquent-sluggable/issues/126

Davox08 commented on 30 Apr
I just change the require from: "cviebrock/eloquent-sluggable": ">=3.0.0-alpha" to: "cviebrock/eloquent-sluggable": "dev-master", then I run $composer update. The path works now.

**Comment by cviebrock** [comment]
Closing ... this should be fixed in the latest 3.x versions.
