### ISSUE TITLE
It's forcing me to use unique slugs

### ISSUE THREAD

**Issue by chicag0** [cviebrock/eloquent-sluggable#117]
I have unique set to false but my app is still generating unique slugs, is there something I am missing?  I have tried all of the settings and nothing seems to work.

**Comment by chicag0** [comment]
Have you experienced this before @cviebrock ?

**Comment by chicag0** [comment]
Any chance you can help me @cviebrock?

**Comment by cviebrock** [comment]
Sorry for the lack of response.  I really haven't seen this behaviour before.  Have you tried running the unit tests that come with the package to see if you still get unique slugs when you shouldn't (there is a test for that, if I recall).

Maybe something in your config file isn't right?

**Comment by cviebrock** [comment]
Closed for lack of response.  Re-open if you continue to have issues (and provide some of your code so I can see what the issue might be).  Thanks!
