### ISSUE TITLE
If model construct requires parameters it will fail on getting existing slugs

### ISSUE THREAD

**Issue by MLoureiro** [cviebrock/eloquent-sluggable#118]
Hi everyone

I'm loading required models (through IoC) into my model/parent.
So it will throw an error at https://github.com/cviebrock/eloquent-sluggable/blob/master/src/SluggableTrait.php#L166
because is loading a new class.

Any idea if there is a way I could do to resolve this?

Thanks

**Comment by cviebrock** [comment]
I think the line numbers on the trait have changed since you posted this issue.  Can you just copy the line/method that's causing you problems (assuming recent updates haven't fixed things for you)?

Thanks!

**Comment by MLoureiro** [comment]
Hi @cviebrock 
the problem was this line [3eff777e:/src/SluggableTrait.php#L166](https://github.com/cviebrock/eloquent-sluggable/blob/3eff777e085722bc2dc7bf13c11e69a3aa4f6517/src/SluggableTrait.php#L166)

TBH I hadn't time to work on that project for a while, as soon as I re-test it I'll update here.

**Comment by cviebrock** [comment]
Closing off for now.  Re-open a new issue if you continue to have problems!

**Comment by MLoureiro** [comment]
Sorry, I haven't had time to pick this again.
It's best to leave it close.
Thanks!
