### ISSUE TITLE
Option to override the unique suffix

### ISSUE THREAD

**Issue by EspadaV8** [cviebrock/eloquent-sluggable#119]
It would be great if the unique suffix could be overridden to allow, e.g. unique random digits. This could be used when creating accounts new users and you don't want to disclose how many previous accounts have the same name.

**Comment by DavidPhilip** [comment]
+

**Comment by cviebrock** [comment]
Have you tried overloading SluggableTrait's `makeSlugUnique($slug)` method?

**Comment by EspadaV8** [comment]
That would be an option, but in most cases I imagine that would mean copy/pasting the existing code and just changing the `increment` part, which isn't ideal.

As an alternative to #120 it would be possible to just have the `increment` part within `generateSuffix` and then just have that overridden within the model (rather than having it as an setting), which would probably be a bit 'cleaner' I think.

**Comment by EspadaV8** [comment]
I've just create PR #129 that does basically the same as #120 but without needing the setting, the model can just override the `generateSuffix` method that's defined within the trait.

**Comment by cviebrock** [comment]
Closed.  #129 was merged to provide this.
