### ISSUE TITLE
[ErrorException]   file_put_contents(...\app/database/migrations/2015_04_17_003214_add_sluggable_columns.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by LoveAndHappiness** [cviebrock/eloquent-sluggable#126]
Hi there

I get the following Error Message, when I try to execute the php artisan sluggable:table lessons command:

´´´[ErrorException]
  file_put_contents(D:\wamp\www\laravel3\app/database/migrations/2015_04_17_003214_add_sluggable_columns.php): failed to open stream: No such file or directory´´´

I followed your installation instructions. Yet it won't add a migration to my existing migrations.

**Comment by MatejB** [comment]
It seems it's corrected in master.

To make it work in composer downloaded version, in file:
```vendor/cviebrock/eloquent-sluggable/src/SluggableTableCommand.php```
change 
```$this->laravel['path'].'/database/migrations';```
to
```$path = base_path().'/database/migrations';```

**Comment by owlpaste** [comment]
So the above will help with the issue temporary until composer downloaded version is fixed (I am not totally clear how this actually works...)

But now there is another issue:

file_get_contents(*base-path*/vendor/cviebrock/eloquent-sluggable/src/stubs/migration.stub): failed to open stream
  : No such file or directory

It seems that it is looking for stubs in the src dir but they are actually one directory above! Any suggestions? I am pretty new to composer way of doing things and when it stops just working... kinda lost XD

**Comment by UniversoDVX** [comment]
I just change the dev from: "cviebrock/eloquent-sluggable": ">=3.0.0-alpha"  to: "cviebrock/eloquent-sluggable": "dev-master", then I run $composer update. The path works now.

**Comment by cviebrock** [comment]
Closing this ... should be fixed in 3.0.0 release.
