### ISSUE TITLE
two slug field in a table for example: slug, slug_nep

### ISSUE THREAD

**Issue by vtxmg** [cviebrock/eloquent-sluggable#127]
Hello Namaste!! I m creating a site having two languages ... so it needs two slugs for a same content ...  please tell me how can i do it with this package.. Thanks in advance :)

**Comment by cviebrock** [comment]
This isn't trivial, but it shouldn't be too hard by overloading some of SluggableTrait's methods [as described here](https://github.com/cviebrock/eloquent-sluggable#extending).

**Comment by vtxmg** [comment]
if u don't mind, can you give me a example ... :)
