### ISSUE TITLE
Stable Release for Laravel 5

### ISSUE THREAD

**Issue by maximebeaudoin** [cviebrock/eloquent-sluggable#142]
Hi, i was wondering when the first stable version 3.* will be tagged ? The alpha tag is from 11 February.

**Comment by zh-daniel-huang** [comment]
+1

**Comment by cviebrock** [comment]
I've just pushed out a _3.0.0-beta_ release for testing.

* Supports Laravel 5.0 and 5.1
* Fixed most of the outstanding bugs
* Standardized the code styling
* Adds PHPdocs for all classes and methods
* **Breaking Change:** Dropped support for the `use_cache` option (which never really worked as intended)
* **Maybe Breaking Change:** Changed the default slugging method from Laravel's `Str::slug()` to the well-maintained [Cocur/Slugify](https://github.com/cocur/slugify) (which gives some transliteration functionality for slugging non-Western strings)

I don't anticipate any more feature additions/changes between now and the final release, so please kick the tires a bit and let me know. Open a new issue if something isn't working.

Thanks!
