### ISSUE TITLE
Problem with updated slugs and 301 redirections

### ISSUE THREAD

**Issue by WillyReyno** [cviebrock/eloquent-sluggable#146]
Hi,

First of all thank you for this awesome package!

I'm using it on a project where people can create "events".
Each events' name is slugged and used in the url.
For example, if I want to go to the "new year 2015" events' page, the url would be : 
http://mywebsite.com/events/new-year-2015

I set "on_update" to true, because I want to change the url as the name is updated.
When an event's name is updated, I store its old slug and its ID in an other table in order to make 301 redirects from the old slug to the new one.

So, if I update "new year 2015" events to "new year 2016", 
this : http://mywebsite.com/events/new-year-2015
will lead to this :  http://mywebsite.com/events/new-year-2016

Now if I want to create a whole new event named "new year 2015", this new event's slug will lead to "new-year-2016" instead of  "new-year-2015-1" (which would be the new one I just created)

So I think that the solution would be to check if the slug being created isn't existing in both my events table and my oldslugs table, but I don't really see how...

I tried to make it the clearer possible, but I don't really know if it's easy to understand.

If you have any questions, feel free to ask!

Thank you.

**Comment by Keoghan** [comment]
Hi - I think you'll need to override the `getExistingSlugs($slug)` method to get it to retrieve values from both your tables. So, I think you can just override that method in the model (keeping it simple).
