### ISSUE TITLE
Is route-model binding working?

### ISSUE THREAD

**Issue by MatthewRuddy** [cviebrock/eloquent-sluggable#147]
Thanks for this awesome package, looks like a lot of hard work has gone into it!

I've run into a bit of trouble trying to get route-model binding working. I'm using `dev-master`, and I've added the service provider as described in the `readme.md`. I've added the model bindings to `RouteServiceProvider` and that's all working fine when using ID's.

Slugs aren't working at all. I can see that in `SluggableRoutingServiceProvider` you're rebinding with your own router, but `$this->app->share` (line 17) doesn't appear to be firing, so the sluggable model binding isn't taking effect.

Am I missing something? Followed the `readme.md` installation instructions word for word and checked twice.

**Comment by TheJjokerR** [comment]
I can confirm a 404 is given when attempting to go to a page by its slug. All other features seem to work correctly .

**Comment by Keoghan** [comment]
Hi - you are correct, unfortunately, there is a problem with overriding the router. 
I've created a pull request to share the best alternative - rather than using a service provider, you'll need to set the router earlier on in bootstrap/app.php.

```php

$app->singleton(
    'router',
    '\Cviebrock\EloquentSluggable\SluggableRouter'
);

```

**Comment by cviebrock** [comment]
Yeah, @Keoghan's PR has just been merged.  I have 2 others that I want to clean up and then I should be able to tag this ready for Laravel 5 (and 5.1).
