### ISSUE TITLE
Not checking duplicate with soft deleted items

### ISSUE THREAD

**Issue by vtxmg** [cviebrock/eloquent-sluggable#150]
Hello everyone!
I found duplicate entry error while inserting data with slug then i checked and found that the same items was soft deleted. Means there is a record with same name but date at delete_at so it doesn't check this record for duplicate. How to check every even soft deleted record for duplicate record for slug??

**Comment by jaewun** [comment]
> On 17/06/2015, at 1:07 pm, vtx mg <notifications@github.com> wrote:
> 
> Hello everyone!
> I found duplicate entry error while inserting data with slug then i checked and found that the same items was soft deleted. Means there is a record with same name but date at delete_at so it doesn't check this record for duplicate. How to check every even soft deleted record for duplicate record for slug??
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/cviebrock/eloquent-sluggable/issues/150>.
> 

include_trashed

Setting this to true will also check deleted models when trying to enforce uniqueness. This only affects Eloquent models that are using the softDelete <http://laravel.com/docs/eloquent#soft-deleting> feature. Default is false, so soft-deleted models don't count when checking for uniqueness.


 <https://github.com/cviebrock/eloquent-sluggable#on_update>

**Comment by vtxmg** [comment]
got it thanks!! ^_^

**Comment by bishalpaudel** [comment]
Thanks, this saved my lot of hours.
