### ISSUE TITLE
Two slug fields required!!!

### ISSUE THREAD

**Issue by vtxmg** [cviebrock/eloquent-sluggable#151]
Hello everyone!
I want to have two slug fields slug, slug_nep from fields title, title_nep respectively. How can i manage this ? Both field are unique als0?

**Comment by muratsplat** [comment]
You can do this by using eloquent event with  the aid of eloquent-sluggable method.

Look at this line : https://github.com/cviebrock/eloquent-sluggable/blob/master/src/SluggableServiceProvider.php#L60

You can write same code for your situation
