### ISSUE TITLE
archive old slugs after update

### ISSUE THREAD

**Issue by Remo** [cviebrock/eloquent-sluggable#156]
Haven't found anything about that here, but what I have should be a fairly common problem.

When I update the title and the slug my URLs are broken and I keep getting a lot of 404 errors.
To avoid that I'd like to keep all slugs in an additional table which I can then use to redirect the user to the correct page using a 301 redirect.

Keeping the slugs is easy, I can override the save method and I'm done. However, making sure my slugs stay unique seems to be a bit trickier. Is there anything I can do to tell eloquent-sluggable to check two tables for the uniqueness of the slugs?

**Comment by kkiernan** [comment]
I've been thinking about this as well and just checked it out in WordPress. It looks like they store all old slugs in an additional table, but don't include them when checking for uniqueness. That is, they only check the old slugs if a 404 is encountered. If a new post uses another posts older slug, WordPress just shows that new post. Is that what you are looking to avoid?

**Comment by Remo** [comment]
@kkiernan I would have included that "old-slugs-table" in my checks, otherwise one user might be able to steal the address for another one. But on the other hand I might not want to block too many addresses which aren't really active anymore. I guess both way have their benefits.

Yes, I searched a bit different, but this is a duplicate, closing it..
