### ISSUE TITLE
on_update callback

### ISSUE THREAD

**Issue by borys-p** [cviebrock/eloquent-sluggable#160]
Hi,

How about an option to execute slug-related callback when model is updated? For example you could save the old and the new slug in some table and perform redirect with a catch-all route. Currently it requires extending Sluggable or listening for events, which makes the slug-related code scattered all over the app.

**Comment by cviebrock** [comment]
I've added "slugging" and "slugged" Eloquent model events to master (soon to be in the 3.1.0 release).
