### ISSUE TITLE
findBySlugOrId() fails when slug is numeric

### ISSUE THREAD

**Issue by mrdth** [cviebrock/eloquent-sluggable#161]
The current implementation of findBySlugOrId($slug) / findBySlugOrIdOrFail($slug) assumes that any numeric values for $slug should be regarded as an ID, which means that any entity which has had a numeric slug generated can't be loaded via these methods.

**Comment by cviebrock** [comment]
Good point.

Not sure how best to handle this, other than just going with `findBySlug` and `findById` methods (i.e. you need to know what you are searching for before you search for it).

**Comment by mrdth** [comment]
I thought of reversing the logic of the checks, something like the following might be better, but there is still the chance of a collision:

    public static function findBySlugOrId($slug) {

        if (!$result = self::findBySlug($slug)) {
            return self::find($slug);
        }
        return $result;
    }

(I'm doing similar in controllers, as it should work OK for my use case, where numeric slugs will be high 4 digits.)

**Comment by cviebrock** [comment]
That would probably work.  PR it?
