### ISSUE TITLE
A request feature of  adding rules for Cocur\SlugifySlugify

### ISSUE THREAD

**Issue by muratsplat** [cviebrock/eloquent-sluggable#164]
Hi,

Some Turkish character is German character at the same time..

I was marked  same characters on down..
```
//
  // German characters
        'Ä' => 'AE',
        'Ö' => 'OE', //  it must be  "O" in Turkish..
        'Ü' => 'UE', //  it must be  "U" in Turkish..
        'ß' => 'ss',
        'ä' => 'ae',
        'ö' => 'oe', //   it must be  "o" in Turkish..
        'ü' => 'ue', //  it must be  "u" in Turkish..

        // Turkish characters
        'Ç' => 'C',
        'Ğ' => 'G',
        'İ' => 'I',
        'Ş' => 'S',
        'ç' => 'c',
        'ğ' => 'g',
        'ı' => 'i',
        'ş' => 's',
```
I want to give an examle in Unit test to show the point..

```php

        public function testSlugBugWhenUseTurkishCharacter() 
        { 
                        
            $attr = [                
                'name'      => 'Gümüşhane',  // Turkish City Name           
            ];            

            $city = factory(City::class)->make($attr);   
                  
            // generating slug 
            $city->sluggify();
            
            $this->assertEquals($city['slug'], 'gumushane'); // failed! returns: 'guemueshane-1' 
        }    

```
'Gümüşhane'  is Turkish name. But `Cocur\SlugifySlugify` object thinks of it is 'german name', also is not..

There is have to be way to adding rules according to this situation  while model is saving..

Maybe SluggableTrait can check custum rule on the model ? If it is exist, SluggableTrait adds the rule to  'Cocur\SlugifySlugify' Object..

**Comment by muratsplat** [comment]
I have write a solution to add custom rules  to Cocur\SlugifySlugify. All tests is passed :+1: 

https://github.com/muratsplat/eloquent-sluggable/commit/4f7982650f944627009caf0d8c5fc9fceede9bc4

**Comment by cviebrock** [comment]
That seems reasonable (although I probably wouldn't have made as many private and protected functions to get to that point).

Feel free to make a MR.

**Comment by muratsplat** [comment]
Ok I will check my codes, and than I will send pull request..

**Comment by cviebrock** [comment]
See: https://github.com/cviebrock/eloquent-sluggable#getslugengine

**Comment by emir** [comment]
Just edit config/sluggable.php like this:

```
'method' => function( $string, $sep ) {
    return str_slug(\Patchwork\Utf8::toAscii($string));
},
```
