### ISSUE TITLE
Unique based on model

### ISSUE THREAD

**Issue by canfiax** [cviebrock/eloquent-sluggable#167]
Say I have a User. A User hasMany Post.

I want the Post slug to be unique based on the User, and not to the whole Post table.

I would like this result:

    http://domain.com/user1/blog-post
    http://domain.com/user2/blog-post
    http://domain.com/user3/blog-post

Currently it is:

    http://domain.com/user1/blog-post
    http://domain.com/user2/blog-post-1
    http://domain.com/user3/blog-post-2

Is this possible, or did anyone already build this?

**Comment by bryannielsen** [comment]
I had to do this recently too, I don't think it's particularly clean but I didn't see too many options.  I re-implemented the `getExistingSlugs()` method provided by the SluggableTrait inside my model to modify the query.

It would be nice if there was a way to hook into just the "existing query" for the slug instead of doing this, if I get some time I could pull request that.

**Comment by cviebrock** [comment]
Yeah, other than reimplementing `getExistingSlugs()`, there really isn't a clean way to do this.

I could refactor the part of that method that generates the query, but there isn't a whole lot more to that method anyway: it just generates the query, runs it, and creates a _key->slug_ collection.

I'm open to suggestions!

**Comment by canvural** [comment]
I'm facing this issue too.

And i can't figure out how can you solve this by modifying `getExistingSlugs` method.

**Comment by canvural** [comment]
This issue only happens when using more then one slug in an URL.

For example, `http://example.com/user/{user_slug}/post/{post_slug}`

Now `post_slug` belongs to the user. In order to get the right `Post` model for that slug, we have to know the `User` model. And i think this is not the job for the library. We can fix the issue in the controller. Like this, `$post = $user->posts()->where('slug', $slug)->get();`

**Comment by cviebrock** [comment]
If you wanted to get the existing slugs of all posts that belong to a user (instead of _all_ posts), then you might do something like (untested):

```php
protected function getExistingSlugs($slug)
    {

        // get current user
        $user = $this->user;

        $config = $this->getSluggableConfig();
        $save_to = $config['save_to'];
        $include_trashed = $config['include_trashed'];

        $instance = new static;

        //check for direct match or something that has a separator followed by a suffix
        $query = $instance->where('user_id',$user->getKey())
            ->where(function ($query) use (
                $save_to,
                $config,
                $slug
            ) {
                $query->where($save_to, $slug);
                $query->orWhere($save_to, 'LIKE',
                  $slug . $config['separator'] . '%');
            });

        // include trashed models if required
        if ($include_trashed && $this->usesSoftDeleting()) {
            $query = $query->withTrashed();
        }

        // get a list of all matching slugs
        $list = $query->lists($save_to, $this->getKeyName());

        // Laravel 5.0/5.1 check
        return $list instanceof Collection ? $list->all() : $list;
    }
```

The two changes between that and the method in the trait are a) I use `$user=$this->user` to get the user of the current slug, and b) the additional `where()` clause on the query that looks for existing slugs so that it's limited to that particular user.

Does that help?

**Comment by bryannielsen** [comment]
Using your example I would just implement the `getExistingSlugs` method on your `Post` model like this:

````
/**
	 * Get all existing slugs that are similar to the given slug.
	 *
	 * @param string $slug
	 * @return array
	 */
	protected function getExistingSlugs($slug) {
		$config = $this->getSluggableConfig();
		$save_to = $config['save_to'];
		$include_trashed = $config['include_trashed'];

		$instance = new static;

		$query = $instance->where($save_to, 'LIKE', $slug . '%');

		// @overriden - changed this to scope unique slugs per user
		$query = $query->where('user_id', $this->user_id);

		// include trashed models if required
		if ($include_trashed && $this->usesSoftDeleting()) {
			$query = $query->withTrashed();
		}

		// get a list of all matching slugs
		$list = $query->lists($save_to, $this->getKeyName());

		// Laravel 5.0/5.1 check
		return $list instanceof Collection ? $list->all() : $list;
	}
````

And then you could add bindings for them like this:

````
Route::bind('user', function($value, $route)
{
    return \App\User::findBySlugOrIdOrFail($value);
});

Route::bind('post', function($value, $route)
{
    $user = $route->getParameter('user');

    return \App\Post::whereSlug($value)->where('user_id', $user->id)->firstOrFail();
});
````

I've taken a similar approach in a recent project and it seems to work pretty well.

@cviebrock the only thing that might be a nice addition is adding some kind of default query scope to the `SluggableTrait` that by default would just return the unaltered query.  Then we could just implement that query scope to further restrict what qualifies as an "existing slug" for the model.  I could work up a PR for this quickly if you think it sounds sane.

**Comment by canvural** [comment]
I fixed the issue for myself with the method i wrote above.

But for adding a new feature to the library, we can discuss it here.

@cviebrock, @bryannielsen in the examples you gave, `user` is hardcoded. How can we generalize that, and let it know the "previous" model?

**Comment by canvural** [comment]
And if the `unique` config key is `false` the `getExistingSlugs` method is never called. We need to do it somewhere else.

**Comment by bryannielsen** [comment]
Yea I don't really see any way to do something like this without hardcoding on the specific model, it would just be nicer if there was a smaller method to reimplement and not copy so much code from the SluggableTrait.  Perhaps there's a way to do this through config on a per-model basis but for my purposes I just needed something quick and simple.

If the `unique` config key is `false` then you don't care about uniqueness right?  I'm not sure I follow the use case where you would not have that enabled to get a unique child slug given a specific parent (or related) model.

**Comment by canvural** [comment]
From the original post:

```
http://domain.com/user1/blog-post
http://domain.com/user2/blog-post
http://domain.com/user3/blog-post
```

We don't care the uniqueness of the post. So we set `unique` to `false` for the `Post` model. The uniqueness of the post comes from that it belongs to a different user.

**Comment by phroggyy** [comment]
Well, if you have a global scope which is added to query on just that user, it could work if you did unique.

**Comment by cviebrock** [comment]
Going to close this issue.  Some nicer way of scoping slug uniqueness is something I'll plan on adding in the next version.
