### ISSUE TITLE
Installation instructions out of date

### ISSUE THREAD

**Issue by oldskool73** [cviebrock/eloquent-sluggable#168]
The install instructions are still using L4 syntax I think, should be...

```
'providers' => [
    // ...
    Cviebrock\EloquentSluggable\SluggableServiceProvider::class
];
```

**Comment by cviebrock** [comment]
That's more a PHP 5.5 vs PHP 5.4 syntax difference.  Since Laravel 5.0 doesn't require PHP 5.5, I think I'm going to leave this.  The end result is the same.
