### ISSUE TITLE
Configuration 'built_from' = null fails

### ISSUE THREAD

**Issue by OzanKurt** [cviebrock/eloquent-sluggable#170]
When you don't set a default field it adds the `built_from` key in the `sluggable` property from the model and it ends up doing something like this.

```php
class Department extends Model implements SluggableInterface
{
	use SluggableTrait;

	protected $sluggable = [
		'built_from' 	=> 'name',
		'save_to' 		=> 'slug',
	];

	protected $fillable = ['name', 'slug'];
}
```

When I create a new department while the 'built_from' key is empty in the configuration file, it generates a slug like this: `name-name-of-the-department`

The first name comes from:

```php
	protected $sluggable = [
		'built_from' 	=> 'name',
		'save_to' 		=> 'slug',
	];
```

Thanks!

**Comment by cviebrock** [comment]
I'm not sure I follow.  You create a new Department but don't set the _name_ attribute .... and the slug is then "name"?

Can you write a test to show me what you mean?

**Comment by OzanKurt** [comment]
I am not so familiar with test but can provide a short video where i show what is happening. Nice to hear your feedback. :)

**Comment by cviebrock** [comment]
Sounds good!

**Comment by cviebrock** [comment]
Closing for lack of feedback.

**Comment by OzanKurt** [comment]
```php
	protected $sluggable = [
		'built_from' 	=> 'name',
		'save_to' 		=> 'slug',
	];
```
This code resulted this:
![Result of this](http://i.imgur.com/vJizwVC.png)
