### ISSUE TITLE
Just an FYI

### ISSUE THREAD

**Issue by andrewtweber** [cviebrock/eloquent-sluggable#177]
It looks like this blog plagiarized your readme and published it as a "blog post"

http://dunebook.com/easily-create-slugs-for-your-eloquent-models-in-laravel-5

**Comment by cviebrock** [comment]
Thanks!

**Comment by cviebrock** [comment]
Looks like the author of that post is also the guy who runs the site. I took a quick look at a few more of his "tutorials", and they are just copy-pastes of other package's READMEs as well.

_sigh_
