### ISSUE TITLE
findBySlugOrFail to scope

### ISSUE THREAD

**Issue by codel** [cviebrock/eloquent-sluggable#179]
What would you think about making this method a scope so we can eager-load relationships while using it like this:

Items::with('things')->findBySlugOrFail($slug);

Now I'm not sure if that's the way laravel handles findOrFail but I think it's pretty useful.

**Comment by aronduby** [comment]
Yes please! I just spent a bunch of time reworking this for my non-laravel CMS so that my laravel sites can use it, only to be greeted with an exception screen after all my work.

**Comment by cviebrock** [comment]
Eloquent's `findOrFail` methods are not scopes, though.  If you think about it, scopes are meant to be chainable, but `findOrFail` needs to be terminal (either you find something, or you fail). So chaining isn't possible.

You can always do `Items::with('things')->whereSlug($slug)->get()` and then just check the return value.

**Comment by codel** [comment]
Then we could make it a nonstatic function just like Laravel and use magic methods to allow it to be called as static.

**Comment by codel** [comment]
Well I think I'm just gonna go for the whereSlug so we don't make the code of Eloquent-sluggable a mess, or make it harder to read. :)

**Comment by aronduby** [comment]
I ended up going the `whereSlug` route. I'm not familiar enough yet with the under the hood setup to know scopes vs. not scopes etc. but I was quite surprised to find that the function mimicking `findOrFail` doesn't actually work the same way and can't accomplish the same things.

**Comment by phroggyy** [comment]
@cviebrock: `findOrFail` might not be chainable, but it's on the `Builder` and can hence be called statically or dynamically. I often abuse scopes and make them do this. Yes, it somewhat violates what a scope should do, but it serves the end-user better.
