### ISSUE TITLE
Should not build slug if build_from fields are empty

### ISSUE THREAD

**Issue by canfiax** [cviebrock/eloquent-sluggable#180]
If I create a user without a firstname and lastname (scope: fullname), it creates -1, -2, -3, -4, as slugs on the different users.

Have a look:

![image](https://cloud.githubusercontent.com/assets/3786627/9761028/51c6a302-56fa-11e5-80cf-93995198d110.png)
**(of course above is fake data)**

**Comment by cviebrock** [comment]
A fix for this is coming in the next release (see #162).  In the meantime, using `dev-master` should take care of it.
