### ISSUE TITLE
Cannot prevent slugging when creating a new model

### ISSUE THREAD

**Issue by MauMaGau** [cviebrock/eloquent-sluggable#184]
We have on_update to prevent re-slugging, but we have a use case that requires the slug not be created when the model is first created, but at a later date. Is this currently possible?

**Comment by cviebrock** [comment]
Out of the box, I don't think so.  However, you could hook something up using the Eloquent events that are fired when a model is slugged.  The **slugging** event is fired before, so you could create a method that checks if it exists yet (i.e. when it's first created), and return `false` so as not to slug on the initial save.

Maybe something like this (untested, off-the-cuff code):

```php
Model::slugging(function ($model) {
    if(!$model->exists()) {
        return false;
    }
});
```

**Comment by MauMaGau** [comment]
Looks good. We decided to let the slug be set, but use a mutator to return the id until a status property changes. Thanks for the help.
