### ISSUE TITLE
bind sluggable to multiple models

### ISSUE THREAD

**Issue by tim-peterson** [cviebrock/eloquent-sluggable#186]
In the DRY spirit, I'd like to bind sluggable to multiple models. So ideally one wouldn't write the code in the link below multiple times. May it be documented somewhere what's the recommended Laravel approach for that?

https://github.com/cviebrock/eloquent-sluggable#updating-your-eloquent-models

**Comment by phroggyy** [comment]
@tim-peterson what do you mean? Do you want Sluggable on multiple models that have the same column names, without repeating that array multiple times?

**Comment by tim-peterson** [comment]
Yes. All my tables have the same column name, "slug". Is there a way to bind this interface to multiple multiples?

**Comment by phroggyy** [comment]
@tim-peterson: what about placing it in a config file. Let's say you put it in `services.php` you'd add a key `sluggable` with the value being your array. Then, in your models you can just do `protected $sluggable = config('services.sluggable')`. Alternatively, create a base model `SluggableModel` which your models extend or similar.

**Comment by tim-peterson** [comment]
Thanks @phroggyy , i'm not seeing how the configuration relates to the question. What you said before about extending the base model made more sense to me. Can you clarify how the Configuration section relates to implementing Sluggable in multiple models simultaneously?

**Comment by phroggyy** [comment]
@tim-peterson: you can set a default `build_from` and `save_to` in your config. If you don't set a `sluggable` attribute on your model, it will use your config if I've understood correctly.

**Comment by tim-peterson** [comment]
Sounds good, yes that works. Because the config files has the default `build_from` and `save_to` I'm using, I don't need to specify that array every time. To even be more DRY, I also extended the Models where I want to use Sluggable  with a `Base` Model such that I could write this:

```
class User extends Base 
{
```

Instead of: 

```
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class User extends Model implements SluggableInterface 
{
```


Here's the relevant part of my `Base` Model:

```
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class Base extends Model implements SluggableInterface 
{
    use SluggableTrait;
```
