### ISSUE TITLE
[Proposal] Allow multiple slugs per model

### ISSUE THREAD

**Issue by phroggyy** [cviebrock/eloquent-sluggable#187]
I propose introducing a new notation for the sluggable arrays to allow for multiple slugs without using the custom slugging event. I propose this would be denoted as

```
protected $sluggable = [
    'build_from' => [
        'title',
        'subtitle',
    ],
    'save_to' => [
        'slug',
        'slug2',
    ],
]
```

This would bind `title` to `slug` and `subtitle` to `slug2`, and hopefully feels logical for users.

**Comment by cviebrock** [comment]
Something like this might be more intuitive:

```php
protected $sluggable = [
	'slug' => [
		'build_from' => 'title',
		'unique' => true,
		...
	],
	'slug2' => [
		'build_from' => ['firstname','lastname'],
		...
	]
]
```

Pretty major backwards-compatability breakage, however, in any case.  But a good idea.

**Comment by salvisb** [comment]
What is status of this issue? Is it possible to pass multiple slugs per model?

**Comment by AnMartini** [comment]
+1

**Comment by maximepvrt** [comment]
I have the same problem as @salvisb :) I want create a title_fr and title_en slug ^^
What is status of this issue? Is it possible to pass multiple slugs per model?

**Comment by cviebrock** [comment]
Version 4.0 supports multiple slugs per model. Enjoy!
