### ISSUE TITLE
wrong create migrate

### ISSUE THREAD

**Issue by WaterSpout** [cviebrock/eloquent-sluggable#189]
Hello, i use command `php artisan sluggable:table courses`, be created by wrong file

```php
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class {{class}} extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::table('{{table}}', function(Blueprint $table)
		{
			$table->string('slug')->nullable();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::table('{{table}}', function(Blueprint $table)
		{
			$table->dropColumn('slug');
		});
	}

}
```
the values are not substituted

**Comment by canvural** [comment]
Are you sure you are using latest version? This should be fixed with #169

**Comment by WaterSpout** [comment]
Yea, i sure. My latest version is `## 3.0.0 - 06-Jul-2015`
`"cviebrock/eloquent-sluggable": "^3.0"`
`Nothing to install or update`
Sorry, but wrong don`t fixed.

**Comment by canvural** [comment]
You have to use master branch i guess. Master branch is not merged with the 3.0 tag. But the fix is in thre master.

**Comment by cviebrock** [comment]
Weird ... gonna do a 3.0.1 release now.

**Comment by cviebrock** [comment]
Try again @WaterSpout ... should be good with 3.1

**Comment by WaterSpout** [comment]
Yea, its work, thanks.
