### ISSUE TITLE
Product::withTrashed()->findBySlug($slug) Call to undefined method Illuminate\Database\Query\Builder::findBySlug() Laravel 5.1

### ISSUE THREAD

**Issue by JHanAlex** [cviebrock/eloquent-sluggable#194]
My model:
====================================================
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Config,
    Lang,
    DB;
use Illuminate\Database\Eloquent\SoftDeletes;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;
class Product extends Model implements SluggableInterface
{
    use SoftDeletes;
    use SluggableTrait;

    const MODERATION             = 1; // На модерации
    const CORRECTION             = 2; // На исправлении
    const SALE                   = 3; // В продаже

    protected $sluggable = [
        'build_from' => 'name',
        'save_to'    => 'slug',
    ];

    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

.....
========================================================
In Controller I ask Product::withTrashed()->findBySlug($slug) and have an error

**Comment by cviebrock** [comment]
`findBySlug` doesn't work that way. Try using `Product::withTrashed()->whereSlug($slug)->get()`.
