### ISSUE TITLE
Slug Engine Turkish ruleset problem

### ISSUE THREAD

**Issue by kaankilic** [cviebrock/eloquent-sluggable#196]
Hi,

There is a problem on turkish usages on cocur/slugify package usage.In turkish, this package converts *ü* to *ue*, *ö* to *oe* etc. In real, we need to convert them like a *"ü"* to *u*, *ö* to *o*. This is the best conversation for the sef links. And there is an ruleset on the cocur's slugify package 
$slugify->activateRuleset('turkish');

If you define that rule for those kind of language and If people can change that on the configuration page. It would be better for this kind of things.

**Comment by cviebrock** [comment]
Sounds more like an issue for Slugify than for my package, no?

**Comment by kaankilic** [comment]
Actually it's about the version of the slugify package which is on your packages composer. I reviewed both codes. On the latest version of slugify, they defined turkish ruleset already. I tried to change your packages composer to master version of slugify but I got an error. Actually, on laravel 4.2 I've used your plugin also.Unfortunetly, there was no turkish character error on there. According to that problem, I've tried to use Str::slug function of laravel to create an slug. It's also getting problem to call that function. It's a mass problem for the turkish characters. Any solution about that?

**Comment by hgokturk** [comment]
in \vendor\cocur\slugify\src\Slugify.php search "turkish characters" then add this at the end of it: 

'ü' => 'u',
'Ü' => 'u',
'Ö' => 'o',
'ö' => 'o',

**Comment by eyeoftigers** [comment]
any changes you do in **\vendor** directory will go away on **composer update ** and on **composer install **

**Comment by eyeoftigers** [comment]
the new version of** cocur\slugify **fix above issue for turkish character.if you package support latest cocur\slugify it will be super

**Comment by emir** [comment]
Just edit config/sluggable.php like this:

```
'method' => function( $string, $sep ) {
    return str_slug(\Patchwork\Utf8::toAscii($string));
},
```

**Comment by faridmovsumov** [comment]
@emir I noticed your solution doesn't work for Arabic chars.
Example string "فرحان تيوب"

**Comment by faridmovsumov** [comment]
I refactored function to prevent empty string problem.

```
'method' => function( $string, $sep ) {
        $result = str_slug(\Patchwork\Utf8::toAscii($string));
        if(empty($result)){
            $result = "user".time();
        }
        return $result;
    },
```

**Comment by cviebrock** [comment]
@faridmovsumov Did you try the solution I posted here: https://github.com/cviebrock/eloquent-sluggable/issues/338#issuecomment-273024457 ?

**Comment by faridmovsumov** [comment]
I didn't try it because I don't want to activate rulsets for each languages seperately. I prefer to generate non seo friendly slug for edge cases. Arabic is rare language for my app.
