### ISSUE TITLE
Implementing this pack in my application is giving me error

### ISSUE THREAD

**Issue by Unstinted** [cviebrock/eloquent-sluggable#199]
Hello,

Please I need full implementation of this package in my application with laravel 4.2*. I want to know how I can implement the slug in my view file, controller and route.

Please I will love to read from you soon.

**Comment by mydnic** [comment]
Did you follow the installation steps from the 2.x branch ?

https://github.com/cviebrock/eloquent-sluggable/tree/2.x

**Comment by Unstinted** [comment]
Yes i read it. here attach is the screen short of the application.
![wpc - c__xampp_htdocs_wpc - _app_controllers_storecontroller php - phpstorm 8 0 3 2015-11-14 11 36 59](https://cloud.githubusercontent.com/assets/8928708/11163131/717e5cf0-8ac4-11e5-9404-4be15f784cc1.png)
![wpc - c__xampp_htdocs_wpc - _app_routes php - phpstorm 8 0 3 2015-11-14 11 38 48](https://cloud.githubusercontent.com/assets/8928708/11163132/7184b37a-8ac4-11e5-8229-df871fca5013.png)
![wpc - c__xampp_htdocs_wpc - _app_views_project_project blade php - phpstorm 8 0 3 2015-11-14 11 33 58](https://cloud.githubusercontent.com/assets/8928708/11163133/71893850-8ac4-11e5-93f3-fa89116d0a67.png)

Please what do i add to the view or controller or route to give me the desired result. Because i followed your instruction but didnt get the desired result.

Hope to read from you soon.

**Comment by mydnic** [comment]
Use $projetct->slug or whatever column you store the slug in.

**Comment by Unstinted** [comment]
Hello, I have replace it with slug column but given error exception with message trying to get property of non object. And it works well wen I use I'd of that project.

Pls can you give me a detail explanation on how to use dis package very well.

**Comment by cviebrock** [comment]
"Trying to get property of non-object" would indicate to me that in your template, where you do `{{ $project->slug }}`, that `$project` isn't an actual Project model. 

In your controller, you're doing `Project::find($id)`. Maybe try `Project::findOrFail($id)` to first make sure you are actually loading a model.

**Comment by Unstinted** [comment]
When i use {{ $project->is }} it work fine. But when i use {{ $project->slug }} its now showing the detail page but show the slug in the url.

Please what can i do?

**Comment by cviebrock** [comment]
If you are using slugs in your URLs, then your controller needs to not use the `::find()` method since that only works on the IDs.  Something like this:

```php
public function getView($slug) {
    $project = Project::where('slug',$slug)->get();
    if ($project) {
        return View::make('project.view')->with('project', $project);
    }
    // no model with that slug found ...
}
```

It's been a while, but I'm not sure if `Route::controller` is useable in this case. You may need to manually define the routes, but maybe not.

Finally, please don't post screenshots of your code.  I can't copy-paste anything to reference it.  Just copy the code from your editor, and paste it here between ``` blocks.  Take a look [here](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) for how to do code blocks in Markdown.

**Comment by Unstinted** [comment]
Here is my Code that links to another view page:
<a href="/project/view/{{$project->id}}"> 

Here is my Controller code:
public function getView($id){
    return View::make('project.view')
        ->with('project', Project::find($id));
}

The above code works fine in getting the project id in the url but i want to display the slug in the Url that links to the view page:


public function getView($slug) {
    $project = Project::where('slug',$slug)->get();
    if ($project) {
        return View::make('project.view')->with('project', $project);
    }
    // no model with that slug found ...
}
The above code you gave me i used it as mention but it giveing me the following error in my laravel log message: Next exception 'ErrorException' with message 'Undefined property: Illuminate\Database\Eloquent\Collection::$pname (View: C:\xampp\htdocs\wpc\app\views\project\view.blade.php)'

![mozilla firefox 2015-11-20 21 41 54](https://cloud.githubusercontent.com/assets/8928708/11311376/c8cdc134-8fcf-11e5-826d-83e3d62e00ac.png)

Please what can i do to make everything work well? It has been giving me bottle neck with my application.
I can provide the view page code and the project page code if you need it.

**Comment by mydnic** [comment]
Your link give me a 404 error

**Comment by Unstinted** [comment]
Here is my Code that links to another view page:
<a href="/project/view/{{$project->id}}"> 

Here is my Controller code:
------ public function getView($id){
    return View::make('project.view')
        ->with('project', Project::find($id));
} -----------

The above code works fine in getting the project id in the url but i want to display the slug in the Url that links to the view page:


public function getView($slug) {
    $project = Project::where('slug',$slug)->get();
    if ($project) {
        return View::make('project.view')->with('project', $project);
    }
    // no model with that slug found ...
}
The above code you gave me i used it as mention but it giveing me the following error in my laravel log message: Next exception 'ErrorException' with message 'Undefined property: Illuminate\Database\Eloquent\Collection::$pname (View: C:\xampp\htdocs\wpc\app\views\project\view.blade.php)'

![mozilla firefox 2015-11-20 21 41 54](https://cloud.githubusercontent.com/assets/8928708/11311376/c8cdc134-8fcf-11e5-826d-83e3d62e00ac.png)
--------------------
Please what can i do to make everything work well? It has been giving me bottle neck with my application.
I can provide the view page code and the project page code if you need it.

**Comment by Unstinted** [comment]
Dont know why it not showing properly. find attach note pad.
[viewcodes.txt](https://github.com/cviebrock/eloquent-sluggable/files/40555/viewcodes.txt)

**Comment by mydnic** [comment]
$project = Project::where('slug',$slug)->first();

**Comment by Unstinted** [comment]
Thanks @mydnic @cviebrock it working fine now. Appreciate your help.
