### ISSUE TITLE
'on_update'  => true don't work

### ISSUE THREAD

**Issue by rafalau** [cviebrock/eloquent-sluggable#201]
how do I change the slug on update?

**Comment by cviebrock** [comment]
`"on_update"=>true` should do that for you.

Can you post some code that doesn't work, so we can test?

**Comment by rafalau** [comment]
Of course. Thanks for helping:

<----------------Update function In controller ---------------->
public function postEditar(Request $request, $id) {        
        $dadosForm = $request->except('_token');        
        $validator = Validator::make($dadosForm, Noticia::$regras);        
        if ($validator->fails()) {
            return redirect('painel/noticias/editar/' . $id)
                    ->withErrors($validator)
                    ->withInput();
        }   
        Noticia::where('id', $id)->update($dadosForm);    
        Session::flash('mensagem', 'Notícia atualizada com sucesso!');
        return redirect('painel/noticias');
    }

<---------------- model ---------------->
namespace App\Models\Painel;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class Noticia extends Model implements SluggableInterface
{
    // Tratamento dos dados permitidos
    protected $guarded = ['id'];
    protected $fillable = ['titulo', 'subtitulo', 'texto'];
    
    static $regras = [
                        'titulo' => 'required|min:3|max:255',
                        'texto' => 'required'
                    ];
    
    // Slug Url
    use SluggableTrait;
    protected $sluggable = [
        'build_from' => 'titulo',
        'save_to'    => 'slug_url',
        'on_update'  => true        
    ];
}

<---------------- also set in vendor/cviebrock/eloquent-sluggable/config/sluggable.php ---------------->
'on_update' => true,

**Comment by cviebrock** [comment]
Did you load the service provider in `app/config.php` and publish the config?

**Comment by rafalau** [comment]
Yes, see:
![captura de tela 2015-11-19 as 04 04 15](https://cloud.githubusercontent.com/assets/15903589/11263535/bd23d34a-8e72-11e5-91b3-3e8a6c3bc5ec.png)

**Comment by Krato** [comment]
Same to me on Laravel 5.1. 

I have this on model

```php
protected $sluggable = [
        'build_from' => 'slug_or_name',
        'save_to'    => 'slug',
        'on_update'  => true,
        'unique'	 => true
    ];
```

And doesn't work. I save the model with create function. 

Thanks

**Comment by rafalau** [comment]
I also not found a solution

**Comment by mattvb91** [comment]
@Krato make sure you also have:

```
implements SluggableInterface
```

**Comment by Krato** [comment]
@mattvb91 sure. I Have it.

Take a look og my model:

```php
<?php namespace starter\Admin\Pages\Models;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class PageTranslation extends Model implements SluggableInterface
{
    use SluggableTrait;

    /**
     * A list of methods protected from mass assignment.
     *
     * @var string[]
     */
    protected $guarded = ['_token', '_method'];

    protected $sluggable = [
        'build_from' => 'name',
        'save_to'    => 'slug',
        'on_update'  => true,
        'unique'	 => true
    ];


    public function getSlugOrNameAttribute() {
        if ($this->slug!='') return $this->slug;
        return $this->name;
    }
}
```

**Comment by mattvb91** [comment]
@Krato didnt have time to look into this further but is it possible the sluggable.php config file is overwriting the 'on_update' value?

**Comment by cviebrock** [comment]
What version of Laravel are you using? And what version of Sluggable?

From the config path you posted, I'm guessing Laravel 4.* right?

**Comment by rafalau** [comment]
Hi. I'm using Laravel 5.1 and last version Sluggable.

**Comment by umefarooq** [comment]
yes on_update is not working with laravel 5.1. i have also tried.

**Comment by Krato** [comment]
@mattvb91 Maybe. But it is assumed that if I put in the array within the model, you should overwrite the config file. It isn't like this?

**Comment by cviebrock** [comment]
I've deprecated the "on_update" configuration in the new version of the package.  It just wasn't intuitive.

If you want to force a reslugging on update, just set `$model->slug = null` before `$model->save()` and the slug will be regenerated. This is in version 4.0 of the package, which is in beta right now.  Please test and resubmit if you have issues!

**Comment by aleixfabra** [comment]
It works!
