### ISSUE TITLE
Slug in URL

### ISSUE THREAD

**Issue by Unstinted** [cviebrock/eloquent-sluggable#204]
Here is my Code that links to another view page:
<a href="/project/view/{{$project->id}}"> 

Here is my Controller code:
------ public function getView($id){
    return View::make('project.view')
        ->with('project', Project::find($id));
} -----------

The above code works fine in getting the project id in the url but i want to display the slug in the Url that links to the view page:

public function getView($slug) {
    $project = Project::where('slug',$slug)->get();
    if ($project) {
        return View::make('project.view')->with('project', $project);
    }
    // no model with that slug found ...
}
The above code you gave me i used it as mention but it giveing me the following error in my laravel log message: Next exception 'ErrorException' with message 'Undefined property: Illuminate\Database\Eloquent\Collection::$pname (View: C:\xampp\htdocs\wpc\app\views\project\view.blade.php)'

![mozilla firefox 2015-11-20 21 41 54](https://cloud.githubusercontent.com/assets/8928708/11311376/c8cdc134-8fcf-11e5-826d-83e3d62e00ac.png)
--------------------
Please what can i do to make everything work well? It has been giving me bottle neck with my application.
I can provide the view page code and the project page code if you need it.

**Comment by canvural** [comment]
Can you edit the question?

**Comment by mydnic** [comment]
This has been resolved here #199
Can be closed
