### ISSUE TITLE
Problem with slug and laravel 5.1.24

### ISSUE THREAD

**Issue by zodthepossum** [cviebrock/eloquent-sluggable#206]
Hi I have implement slug in my Laravel app, bu I am getting a strange error to do with my model

FatalErrorException in Post.php line 26: Class App\Post contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Cviebrock\EloquentSluggable\SluggableInterface::getSlug, Cviebrock\EloquentSluggable\SluggableInterface::sluggify, Cviebrock\EloquentSluggable\SluggableInterface::resluggify)

my post.php model
<?php

namespace App;

use App\Post;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class Post extends Model implements SluggableInterface
{
	protected $sluggable = [
        'build_from' => 'title',
        'save_to'    => 'slug',
    ];

    public function user()
	{
		return $this->belongsTo(Posts::class);
	}

	public function files()
	{
		return $this->hasMany(Images::class);
	}
}

I have added the slug to the table via a migration.  The last line is line 26, hoping you can help I'm a bit lost on this...

**Comment by cviebrock** [comment]
I don't see `use SluggableTrait` inside the class.  That's likely the issue.

**Comment by zodthepossum** [comment]
ok thanks seem to have missed that
