### ISSUE TITLE
one slug table for all models

### ISSUE THREAD

**Issue by mohammad6006** [cviebrock/eloquent-sluggable#209]
how is it possible to have one slug table for all models?

for example there are news and article tables and I want to store all slugs in slug table 

thanks

**Comment by totoleo** [comment]
You may consider the Polymorphic Relationship

**Comment by cviebrock** [comment]
This isn't built in right now, but is something I'm considering.

**Comment by matiazar** [comment]
Im using 1 table for all my slugs, articles, products, categories, etc.. with polymorphic
It will be very fine to have this. 

thanks

**Comment by cviebrock** [comment]
I didn't implement this in version 4, but I'm curious about the use cases for this.  If I can be convinced, I'll add it in v5 :)

**Comment by matiazar** [comment]
maybe I have
a product called New Fifa 2016 Soccer Ball
a news called New Fifa 2016 Soccer Ball

so if the model check inside it table for a unique id it will dont have duplicates... but really are other slug with same name on other table (model).

**Comment by cviebrock** [comment]
In that case, though, I'm not sure why you would care that they are duplicates.  If you were using them for URLs, I'd think you'd end up with different routes depending on whether it was news or products:

```
http://example.com/products/new-fifa-2016-soccer-ball
http://example.com/news/new-fifa-2016-soccer-ball
```

If you _really_ wanted "object-less" URLs like:

```
http://example.com/new-fifa-2016-soccer-ball
```

then I think this could still be achieved in the 4.0 package with a custom [unique slug constraint scope](https://github.com/cviebrock/eloquent-sluggable#scopewithuniqueslugconstraints).

**Comment by matiazar** [comment]
yes, thats is. perfect !
