### ISSUE TITLE
Exclude slugs with on_update

### ISSUE THREAD

**Issue by ParadoxNL** [cviebrock/eloquent-sluggable#212]
In my case i am building a CMS, and the main page slug will always be a "/". However when users save the page, the on_update will be triggered and thus overriding the default "/".

Now am i able to catch it with the following code

```php
Post::registerModelEvent('slugging', function($post) {
    if ($post->someCondition()) {
        // the model won't be slugged
        return false;
    }
});
```

But wouldn't it be more awesome if we could use something like:

```php
protected $sluggable = [
        'build_from' => 'title',
        'save_to'    => 'slug',
        'ignore'     => '/'
    ];
```

**Comment by mydnic** [comment]
Can't you use 

```
'on_update' => false,
```

From the config file ?

**Comment by ParadoxNL** [comment]
@mydnic 

No, because i DO want it to update, except for one.

**Comment by mydnic** [comment]
Ah ok ! My bad :)

**Comment by cviebrock** [comment]
This seems like a pretty edge case to me.  Your solution is how I'd recommend going about this.
