### ISSUE TITLE
Make compatible with Laravel 5.2

### ISSUE THREAD

**Issue by nivv** [cviebrock/eloquent-sluggable#214]
According to the [upgrade guide](http://laravel.com/docs/master/upgrade)

>The `Illuminate\Foundation\Support\Composer` class has been moved to `Illuminate\Support\Composer`. This is unlikely to affect your application if you were not manually using this class.

**Comment by Prashank25** [comment]
+1
I already upgraded to 5.2 and this broke. I can't wait so i will fork and fix this for now :/

**Comment by freekmurze** [comment]
+1

**Comment by nivv** [comment]
Pull request here: #215 by @EspadaV8

**Comment by unamix** [comment]
+1

**Comment by iainheng** [comment]
+1

**Comment by bernardomacedo** [comment]
+1

**Comment by mrcsmcln** [comment]
+1

**Comment by hiendv** [comment]
:+1:

**Comment by boynoiz** [comment]
:thumbsup:

**Comment by Malin88** [comment]
+1

**Comment by tommhuth** [comment]
+1

**Comment by freekmurze** [comment]
If your looking for a package to generate slugs in Laravel 5.2 take a look one at this one I coded up last week: https://github.com/spatie/laravel-sluggable

Colin's package is more feature rich, mine does only the basics. It also has PHP 7 as a minimum requirement.

**Comment by ljjakovljevic** [comment]
+1

**Comment by LagunaJS** [comment]
+1

**Comment by luanrodrigues** [comment]
+1

**Comment by elimentz** [comment]
+1

**Comment by cviebrock** [comment]
Try the 3.1.4 release now, please.

**Comment by markioooo** [comment]
Thanks!

**Comment by bernardomacedo** [comment]
So far id does work! :D :+1:

**Comment by cviebrock** [comment]
Can you all also try the `4.0.0-beta` release, which should work with L5.2.
