### ISSUE TITLE
Giving an error with php artisan sluggable:table

### ISSUE THREAD

**Issue by shinokada** [cviebrock/eloquent-sluggable#216]
In config/app.php

    'providers' => [
    ... 
        Cviebrock\EloquentSluggable\SluggableServiceProvider::class,
    ...
    ]

Laravel version

    ➜  devtodoparrot  php artisan
    Laravel Framework version 5.2.3

I run `php artisan vendor:publish` but it returned the following.

    ➜  devtodoparrot  php artisan vendor:publish
    Publishing complete for tag []!

When I run the following, I get an error.

    ➜ devtodoparrot  php artisan sluggable:table todolists

    [Symfony\Component\Console\Exception\CommandNotFoundException]
    There are no commands defined in the "sluggable" namespace.

I have the following in composer.json under require.

        "cviebrock/eloquent-sluggable": "^3.1"

I tried dev-master as well. But the result is the same.

        "cviebrock/eloquent-sluggable": "dev-master"

**Comment by bernardomacedo** [comment]
What version on Laravel?

**Comment by shinokada** [comment]
version 5.2.3

**Comment by BastinRobin** [comment]
'providers' => [
... 
    Cviebrock\EloquentSluggable\SluggableServiceProvider::class,
...
]

I run php artisan vendor:publish but it returned the following.

Laravel VERSION: 5.2

[ErrorException]                                                             
  Argument 2 passed to Cviebrock\EloquentSluggable\SluggableTableCommand::__c  
  onstruct() must be an instance of Illuminate\Foundation\Composer, instance   
  of Illuminate\Support\Composer given, called in /media/bastin/Work/praanah/  
  vendor/cviebrock/eloquent-sluggable/src/SluggableServiceProvider.php on lin  
  e 92 and defined

**Comment by cviebrock** [comment]
Try the 3.1.4 release now, please.

**Comment by arnaldocastilla** [comment]
I have the some problem .. help me ;/

**Comment by cviebrock** [comment]
The `php artisan sluggable:table` command doesn't exist in the 4.0 version of the package.  You need to add the column(s) yourself to your model tables.

https://github.com/cviebrock/eloquent-sluggable#updating-your-eloquent-models

**Comment by jcsto** [comment]
Thanks @cviebrock ,
just have to use instead the artisan command: 
1- php artisan make:migration name_of_the_migration
**make adjustments in the migrated file**
      public function up(){
            Schema::table('nameOfTable', function(Blueprint $table){
                    $table->string('slug')->nullable();
             });
      }
      public function down(){
            Schema::table('nameOfTable', function(Blueprint $table){
                    $table->dropColumn('slug');
             });
      }

and then;
2- php artisan migrate
 
Done!
