### ISSUE TITLE
Error when overwriting method

### ISSUE THREAD

**Issue by davidavz** [cviebrock/eloquent-sluggable#217]
I just added this to the sluggable parameters
```
'method' => function ($string, $separator) {
    return strtolower(preg_replace('/[^a-z]+/i', $separator, $string));
},
```
But it throws me this exception : `Constant expression contains invalid operations`

Any idea?

**Comment by cviebrock** [comment]
What version of PHP?

**Comment by davidavz** [comment]
PHP 7

**Comment by cviebrock** [comment]
Don't think this is related to sluggable, since that error relates to constants. (I just googled this: http://www.exakat.io/prepare-for-php-7-error-messages-part-2/).

Maybe something further up your class?

**Comment by cviebrock** [comment]
Closed for lack of response.
