### ISSUE TITLE
Don't scan for existing slugs, if it is empty / not set

### ISSUE THREAD

**Issue by canfiax** [cviebrock/eloquent-sluggable#219]
When creating a say, new User but without any name, the slug will be empty. However, the package will still perform a MySQL query to scan for existing slugs, like so:

    select `slug`, `id` FROM `users` WHERE `users`.`deleted_at` IS null AND (`slug` = ? OR `slug` LIKE ?) 

On large tables, this scan is incredibly slow, and not necessary.

**Comment by cviebrock** [comment]
This should be fixed in 4.0. Thanks!
