### ISSUE TITLE
Uniqueness by relation

### ISSUE THREAD

**Issue by royduin** [cviebrock/eloquent-sluggable#222]
When I've a user and post model with relations setup and a user can only see their own posts when logged in; it would be nice if I can have the same slug for a post as another users post with the same title. Currently if user 1 makes a post "test", de slug will be "test", but when user 2 creates a post "test" the slug will be "test-1" but that doesn't make sense because that user can't see the posts of other users.

Is this currently possible? I couldn't find anything about this. If not, any plans to implement this?

**Comment by sipman** [comment]
I am looking for a way to do this also.

Lets call it local vs global slugs.

Where local is restricted to be unique within a relation. And global is unique on the whole db table.

**Comment by WrongWay** [comment]
+1 for this. Would be nice to get this implemented somehow.

**Comment by m1r0** [comment]
+1

Related issue #167

**Comment by kyranb** [comment]
+1 Also referenced #120 #73 and 103

Has anyone got a fork that implements this functionality?

**Comment by cviebrock** [comment]
Sorry that this has languished for so long.  Yes, I think this is a great idea, and pretty doable.  My suggestion would be to create a scope somewhere (on the model, I'm guessing) that is called when we do the query to check for slug uniqueness.

I have a new version of the package in the works (the `rewrite` branch, for those interested), so I'll either implement it there or accept PRs against that branch.

**Comment by kyranb** [comment]
@cviebrock 

Sounds good. Here's what I've been using to do the job:

```php

        $instance = new static;

        if (method_exists($this, 'uniqueSlugScope'))
        {
            $instance = $instance::whereUniqueSlug();
        }
```

I don't like the naming/assignment, but it works :smile:

**Comment by dokpm0** [comment]
Should this be limited to relations?  I have some Django based sites I might convert to Laravel.  So I'm looking for a slug generator with comparable features to Django AutoSlug.  For example, on one site I have a movie model.  It's Slug field is defined as:

    Slug = AutoSlugField(populate_from='Title', unique_with='Year', always_update=True,
        editable=False)

In the above case, Year is a field of the movie model.  A URL to a specific movie looks like:

    http://www.Lassie.xyz/Movie/Lassie-Come-Home/1943/

On the same site I also have a comic series model.  It's slug field is defined as:

    Slug = AutoSlugField(populate_from='Name', unique_with='Publisher', always_update=True,
        editable=False)

In the second case Publisher is a related model.  And while individual comic issues don't have slugs of their own, I use a combination of the issue number, publisher slug, and series slug to look them up.  A URL to a specific comic issue looks like:

    http://www.Lassie.xyz/Comic/Series/M-G-Ms-Lassie/Publisher/Dell/Issue/1/

**Comment by cviebrock** [comment]
This is supported in 4.0 -- https://github.com/cviebrock/eloquent-sluggable#scopewithuniqueslugconstraints
