### ISSUE TITLE
How to add Provider For L5

### ISSUE THREAD

**Issue by BastinRobin** [cviebrock/eloquent-sluggable#224]
I tried using the provider  in laravel 5.2 as given below but its not accepting
'providers' => [
    // ...
    'Cviebrock\EloquentSluggable\SluggableServiceProvider',
];

**Comment by ahmedraza1995** [comment]
Add the provider in the following way: 

'providers' => [
// ...
  Cviebrock\EloquentSluggable\SluggableServiceProvider::class,
];

**Comment by xitude** [comment]
As @ahmedraza1995 said. Classes shouldn't have quote marks and should be appended with 
``````
::class
``````

**Comment by BastinRobin** [comment]
@ahmedraza1995  thank you for the reply it works :)
