### ISSUE TITLE
With method

### ISSUE THREAD

**Issue by Cannonb4ll** [cviebrock/eloquent-sluggable#225]
Allowing the possibility to do **with** whenever you do findBySlug();

     $post = Post::findBySlug('my-slug');

Works fine, but:

     $post = Post::with('author')->findBySlug('my-slug');

Does not, generates: 

     (Call to undefined method Illuminate\Database\Query\Builder::findBySlug())

**Comment by brynnbp** [comment]
Same happens using `withTrashed()`

**Comment by Cannonb4ll** [comment]
@cviebrock Have you had the chance to look at this?

**Comment by kmare** [comment]
I'm having the same issue filtering results. Eg:
\App\Post::published()->findBySlugOrIdOrFail($id);
am I missing something? or is it not doable with eloquent-sluggable?

**Comment by cviebrock** [comment]
Because version 4.0 now supports multiple slugs per model, I've removed all the `findBy*` methods from the package.  You'll need to implement them yourself now, sorry.

```php
Post::where('slug',$slug)->published()->firstOrFail();
```
