### ISSUE TITLE
Slug cannot save with Unicode

### ISSUE THREAD

**Issue by SnguonTheara** [cviebrock/eloquent-sluggable#226]
I have use slug for saving article with Unicode character. But it cannot save my title. It replace by -1, or -2 number. Please help.

**Comment by cviebrock** [comment]
Sorry for the delay.  This would be related to the underlying `Cocur\Slugify` class not knowing how to translate the unicode character, I suspect.  Can you paste the particular string you are having trouble slugging (or a base64-encoded version, if Gitlab doesn't like you pasting it)?
