### ISSUE TITLE
app() function ?

### ISSUE THREAD

**Issue by imkebe** [cviebrock/eloquent-sluggable#227]
I can't use SluggableTrait because it can't resolve Cviebrock\EloquentSluggable\app() 
Where is a app() function defined?

**Comment by cviebrock** [comment]
What is the exact error message? Sounds like a namespacing problem.

**Comment by imkebe** [comment]
I was lacking ServiceProvider declaration. I fixed it but now it can't find config_path function(). I have some modified Laravel components based app which i try to extend.
I found usage examples of config_path() in Laravel docs but there is no source declaration. 
~~~
Call to undefined function Cviebrock\\EloquentSluggable\\config_path() in .../vendor/cviebro
ck/eloquent-sluggable/src/SluggableServiceProvider.php on line 47
~~~

**Comment by cviebrock** [comment]
`config_path` is a Laravel function in vendor/laravel/framework/src/Illuminate/Foundation/helpers.php.

I think you must have something else going on with regards to namespacing in your app.

**Comment by imkebe** [comment]
Yep. I should fix my sanbox first. Thanks for your help!
