### ISSUE TITLE
Composer won't update

### ISSUE THREAD

**Issue by liliumdev** [cviebrock/eloquent-sluggable#229]
When executing:

`composer require cviebrock/eloquent-sluggable`

I get the following error:

```
[ErrorException]
  Argument 2 passed to Cviebrock\EloquentSluggable\SluggableTableCommand::__c
  onstruct() must be an instance of Illuminate\Foundation\Composer, instance
  of Illuminate\Support\Composer given, called in C:\project\ven
  dor\cviebrock\eloquent-sluggable\src\SluggableServiceProvider.php on line 9
  2 and defined
```

The solution is to change the 4th line in file src\SluggableTableCommand.php from

`use Illuminate\Foundation\Composer;`

to 

`use Illuminate\Support\Composer;`

**Comment by cviebrock** [comment]
This was fixed in commit 74373436392141add5740f561ef4ab25b47cf39e and shouldn't be an issue as of version 3.1.4 of the package.  Maybe try requiring that version or later specifically:

```sh
composer require cviebrock/eloquent-sluggable:^3.1.4
```
