### ISSUE TITLE
laravel 5.2.22 doesn't slugs on save()

### ISSUE THREAD

**Issue by pikilon** [cviebrock/eloquent-sluggable#232]
Everything is working for me, resluggify() and I set the getByIdOrSlug and works really well.

However I added the same example for my model like this.

  use SluggableTrait;
    protected $sluggable = [
        'build_from' => 'title',
        'save_to'    => 'slug',
    ];

but when I make App\Post::create(["title"=>"Test of slug"]) or a new object using later $post->save()

the slug is added to the slug column.

I am sorry if this is not an issue and/or if is not the place.

Thanks

**Comment by Mobius1** [comment]
Make sure the App\Post model implements SluggableInterface.

**Comment by pikilon** [comment]
I am very embarrassed, thank you for you kind help to my silly question.

It was that.

**Comment by Mobius1** [comment]
Don't worry, I make the same mistake quite often :+1:

**Comment by mkwsra** [comment]
@pikilon sweet buddy, you might want to close this?

**Comment by stygiansabyss** [comment]
One final note on this since I just did the same thing.  While your code example shows this, the actual text never calls it out.
