### ISSUE TITLE
Slugs for translations

### ISSUE THREAD

**Issue by vitorf7** [cviebrock/eloquent-sluggable#234]
Hi I would like to use this package but I have a question. I have a project here at work were we Properties which will need to be translated and therefore the Title of a property is in another table like so:

```txt

properties Table
    id
    address
    featured_image_id
    ...

property_translations Table
    id
    property_id
    language_id
    title
    slug
    ...

```

How can I use this package to create the slugs since the slugs are in a pivot table?

**Comment by cviebrock** [comment]
I'll be honest, I've never tried this myself.  I know there were some previous issues regarding doing this, so I feel it's possible.

If you use a custom pivot model, you can always apply Sluggable to it instead of the `Properties` model.

**Comment by oLDu67** [comment]
i used dimsav plugin.You must add to 'property_translation' class.

**Comment by fmmajd** [comment]
```
protected $sluggable = [
        'build_from' => 'slugsomewhere',
        'save_to'    => 'slug',
    ];

public function getSlugsomewhereAttribute(){
        //implement your code, choose the var you wanna use as slug
       //query pivot tables and find it
       $res = your_implementation;
        return $res;
    }
```

it works with relationships too.

**Comment by cviebrock** [comment]
Version 4.0 of the package supports slugging to multiple fields on the same model.  This is likely what you could use.

**Comment by kikky7** [comment]
Slugging to multiple fields on the same model will produce something like this:
test-en (for locale en), test-hr (for locale hr), ...
But that's not an option for me.

I would like to get (if it's possible with current package):
test (for locale en), test (for locale hr), ...

Is there a way to create uniqueness to multiple fields? (in case that names for 2 different locales are the same, but that won't be always the case)
For example: 'unique' => ['name', 'locale']

**Comment by cviebrock** [comment]
I’m on vacation so don’t have access to anything but my phone right now. However, I think the section in the docs about modifying the unique scope constraint is probably what you need.
