### ISSUE TITLE
Number gets increased without reason

### ISSUE THREAD

**Issue by simonfranz** [cviebrock/eloquent-sluggable#235]
Hi there,

I think I found a bug in the package. In my case he appended number of the slug gets increased if there is another model with the same base name.
I'm trying to give an example below, please ask if there is anything ambiguous.

I have a model

	id: 1
	name: numb
	slug: numb

and a additional model:

	id: 2
	name: numb
	slug: numb-2

If I'm saving the model 2, the number gets increased everytime. So after another save  of the second model the slug is saved as numb-3

the global settings are 

	[
	'build_from'      => null,
	'save_to'         => 'slug',
	'max_length'      => null,
	'method'          => null,
	'separator'       => '-',
	'unique'          => true,
	'include_trashed' => false,
	'on_update'       => true,
	'reserved'        => null,
	]

in the model itself i have set this configuraiton:

	protected $sluggable = [
		'build_from' => 'name',
		'save_to'    => 'slug',
	];

**Comment by chaotixlv** [comment]
That's because on_update is set on true, I would be much better that on_update would skip updating slug if title isnt changed.

**Comment by simonfranz** [comment]
Yeah seems to be the right solution to not update the sluggable if the name wasn't updated in the first place.
I'll try to create a PR for this issue the next few days.

**Comment by cviebrock** [comment]
Just a heads-up: I'm working on the `rewrite` branch right now and hope to have that out in the next few days as well.  Right now I'm working through the events, so things are pretty fluid.

But consider pulling that branch and working from there, maybe?

**Comment by cviebrock** [comment]
And -- also keep in mind -- I am likely dropping the `on_update` option entirely.  It's more trouble than it's worth, and I think the cases where people want to use it can be done in other ways.

**Comment by simonfranz** [comment]
Ok, then I'll wait for your rework - thanks for the fast response.
Thanks for the fast headsup.

So the default will be that the slug is generated once and only once or the default will be that the slug is updated every time?

**Comment by cviebrock** [comment]
The default would be the same as `'on_update' => false`, i.e. the slug is generated only once.  You can force it to regenerate by setting the slug field to `null` before saving the model.

**Comment by simonfranz** [comment]
thanks
