### ISSUE TITLE
Instead of N+1 for unique slugs use random string

### ISSUE THREAD

**Issue by chaot1x** [cviebrock/eloquent-sluggable#237]
I would be happy if someone could implement this as global thing, that can be changed in config file. I'm using this package for multiple models and to implement this thing for each model is abit pain (to copy/paste), it would be much better If I could do it by just setting it once in config. And by random strings I mean like 6 alphanum characters, example: my-post-name-s9xj5d

**Comment by WrongWay** [comment]
You can write a custom slugging function that uses `str_slug` and appends random chars to the slug. Set that function's name in the config file's (`app/config/sluggable.php`) _method_ attribute.
