### ISSUE TITLE
Auto make Slug with title or slug

### ISSUE THREAD

**Issue by tuannda** [cviebrock/eloquent-sluggable#238]
Hello Everyone!

I want config make slug with title or slug field.

If Slug empty -> generate with Title field
Else generate with Slug field

**Comment by cviebrock** [comment]
How would you generated a slug using the slug field?

If you mean "If the slug is empty, use the title. Otherwise, leave the existing slug."  ... then just set `on_update` to false.

**Comment by mcblum** [comment]
Actually, I was thinking the same thing. Not the slug field from the database but the slug field from the control panel. Say I make a really dumb title like This is great!!!!!!! and it turns my slug into this-is-great------ (I don't know if it would, but for example). It would be great to be able to allow people to just specify the slug they want to use in the control panel to change it to this-is-great.

**Comment by cviebrock** [comment]
If `onUpdate` is false (the default), then the package won't try and regenerate a slug and will just leave the slug field as-is.

So, provide an admin interface or whatever for your users to edit the slug field and save it to the model.  It should persist.

**Comment by mcblum** [comment]
Ahhh - so if I try to generate a slug on update Sluggable won't do anything by default. I think that's perfect -- thank you!
