### ISSUE TITLE
Slug in URL issue

### ISSUE THREAD

**Issue by Unstinted** [cviebrock/eloquent-sluggable#239]
i want to display some details from a table no foreign key using slug url but i am having issue with it. here below is my code.

public function getView($slug) {
        $cstool = CsTool::where('slug',$slug)->first();
        if ($cstool) {
            return View::make('childict.softview')
                ->with('cstool', $cstool);
        }
    }

**Comment by cviebrock** [comment]
What's the issue? That code looks fine to me (although you don't have any code to handle the case where there is no object with the given slug.  Maybe `->firstOrFail()` would be better?
