### ISSUE TITLE
Problemas con cargar los datos a la vista individual

### ISSUE THREAD

**Issue by jonathanpalma25** [cviebrock/eloquent-sluggable#241]
Por favor me sale este error quisiera que me ayudaran

ErrorException in 030b1c1cc1130b2494d921bf07bbbf7e line 75:
Trying to get property of non-object (View: C:\xampp\htdocs\gestor\resources\views\noticia.blade.php)

**Comment by cviebrock** [comment]
I can't debug anything without more details.
