### ISSUE TITLE
BUG! Cant Create Slug if your Using Laravel Create Method!

### ISSUE THREAD

**Issue by masterpowers** [cviebrock/eloquent-sluggable#242]
I dont know if anyone ever experience this, but When you try to Use
mode::create($request->all) 
BTW im using laravel 5.2  
the save event is not called....
and slug is not created Hope this bug will be fix...

using that create api is kinda handy and lessen the code thanks

**Comment by EssamWD** [comment]
It's work with me... are you sure you added the slug attribute to the $fillable array?

**Comment by cviebrock** [comment]
Closing for lack of response.
