### ISSUE TITLE
Error:Call to undefined method Illuminate\Database\Query\Builder::findBySlug()

### ISSUE THREAD

**Issue by Sudip3105** [cviebrock/eloquent-sluggable#243]
I am trying something like this 
 $productCategories =  ProductCategory::with('products', 'products.images')->findBySlug('shirt');
But it gives me error
 Call to undefined method Illuminate\Database\Query\Builder::findBySlug()

**Comment by matevisky** [comment]
I hase the same issue when I am using with. Looks like the query builder does not know about the sluggable interface, now I am using a manual search on these cases which looks ugly:(

**Comment by cviebrock** [comment]
All the static methods and `findBy*` stuff has been removed from the 4.0 version of the package.  There is no elegant way to handle it with multiple slug values, I don't think.

```php
$productCategories = ProductCategory::with('products', 'products.images')->where('slug','shirt')->first();
```

That should work, no?

**Comment by matevisky** [comment]
Yes, but with the old one, it was searching in the ID, and in the SLUG as well. So it was a nice way to handle both search in one command, also it was nice:) Now I have to handle it in 2 call:( Which is note nice:)

**Comment by cviebrock** [comment]
Well, either you do it with two calls in _your_ code, or it's done in two calls in _my_ code.  I'd rather not hide too much magic away. ;)
