### ISSUE TITLE
Sluggable config returns null

### ISSUE THREAD

**Issue by CopyJosh** [cviebrock/eloquent-sluggable#247]
I'm getting an error when I try to reach a page via a slug:

> ErrorException in SluggableTrait.php line 392:
> array_merge(): Argument #1 is not an array
> 
> in SluggableTrait.php line 392
> at HandleExceptions->handleError('2', 'array_merge(): Argument #1 is not an array', '/home/forge/default/vendor/cviebrock/eloquent-sluggable/src/SluggableTrait.php', '392', array('defaults' => null, 'this' => object(Campaign)))
> at array_merge(null, array('build_from' => 'title', 'save_to' => 'slug')) in SluggableTrait.php line 392
> at Campaign->getSluggableConfig() in SluggableTrait.php line 356

It looks like the issue is with pulling the config from this method in SluggableTrait.php

```php
/**
     * Get the default configuration and merge in any model-specific overrides.
     *
     * @return array
     */
    protected function getSluggableConfig()
    {
        $defaults = app('config')->get('sluggable');
        if (property_exists($this, 'sluggable')) {
            return array_merge($defaults, $this->sluggable);
        }
        return $defaults;
    }
```

I didn't have this issue on my local homestead, but when trying to deploy on a public development box this started happening. I didn't have a config/sluggable.php file, so I thought maybe it was having trouble pulling the configuration from the vendor directory... but adding a app/config/sluggable.php didn't resolve the issue. (even tried clearing cache, etc).

Any ideas?

Thanks

- the /config/sluggable.php is literally a copy/paste of the eloquent-sluggable/config/sluggable.php

**Comment by CopyJosh** [comment]
Temporarily I have resolved this issue by putting the configuration array directly in the method

```php
protected function getSluggableConfig()
    {
        $defaults = app('config')->get('sluggable');
        if($defaults == null) {
                $defaults = array('build_from'      => null,
                                  'save_to'         => 'slug',
                                  'max_length'      => null,
                                  'method'          => null,
                                  'separator'       => '-',
                                  'unique'          => true,
                                  'include_trashed' => false,
                                  'on_update'       => false,
                                  'reserved'        => null
                );
        }
        if (property_exists($this, 'sluggable')) {
            return array_merge($defaults, $this->sluggable);
        }

        return $defaults;
    }
```

**Comment by akehat** [comment]
hey... I was experiencing the exact same issue.

**Comment by de-raaf-media** [comment]
Same here. In laravel 5.2. Temporarily commented out line 392 seems to fix this for me but I don't know what is causing it.

**Comment by cviebrock** [comment]
Are you guys testing this on the `rewrite` branch?

**Comment by de-raaf-media** [comment]
My composer.json:
"cviebrock/eloquent-sluggable": "3.1.4",

**Comment by cviebrock** [comment]
Can you try the `4.0.0-beta` release?  I warn you that the configuration has changed a fair amount, so you will likely need to rewrite a bit of your code (mostly just the configuration file).

**Comment by cviebrock** [comment]
Please use the 4.0 release and let me know if this issue persists.

**Comment by de-raaf-media** [comment]
I will try it out and let you know. Thank you.

**Comment by vladern** [comment]
I have the same problem on Laravel 5.4 : PHP warning:  array_merge(): Argument #1 is not an array in /home/plakaplaka/Escritorio/DSS/DSS/foro/vendor/cviebrock/eloquent-sluggable/src/Services/SlugService.php on line 65

**Comment by akehat** [comment]
I got rid of this package.
I wrote my own code. aprox 10 lines of code.

**Comment by cviebrock** [comment]
@vladern Sounds like you didn't publish the default configuration file:

```sh
php artisan vendor:publish --provider="Cviebrock\EloquentSluggable\ServiceProvider"
```

@akehat Great.

**Comment by alejandro-heredia-coderoad-com** [comment]
When trying to publish the default configuration file the output responds with: **Nothing to publish for tag [].**
