### ISSUE TITLE
Two Column , Two Slug in same table for Multi Language

### ISSUE THREAD

**Issue by mtigdemir** [cviebrock/eloquent-sluggable#25]
Hi cviebrock , 
     Thanks for amazing library. I have two column like  'title_en' , 'title_fr'. I didn't use a language table so both of column at the same table. I want to build two different 'slug_en' and 'slug_fr'. Do you have any suggest for this? How about I define one more sluggable function with different name?

Thanks  for your concern..

**Comment by claudiomedina** [comment]
hey @gastondisacco,

Can you show us the solution you used to extend Sluggable so it could sluggify multiple columns?
Does it handle uniqueness?

Thank you

**Comment by ahmadbadpey** [comment]
@claudiomedina , +1
