### ISSUE TITLE
Slug value doest not save in database in Lumen Framework.

### ISSUE THREAD

**Issue by piyushpatil027** [cviebrock/eloquent-sluggable#250]
Hi,

Hope you are doing great. I am using your package for Slug but I can not save slug value in databse .
I am using Lumen Framework.

  $post = $this->create([
                'title' => 'M ddddy Awesome Blog Hello Post piyush',
                'tbl_user_login_id' => '1'
            ]);

            $post->save();

This code is not working in Lumen Framework.

Can you help me how this problem solve.

**Comment by cviebrock** [comment]
Can you provide some more information? Is it throwing errors, or just not saving data?

Also, if you can try the 4.0.0-beta release, I'm only likely supporting that version going forward.

**Comment by cviebrock** [comment]
Try again with the 4.0.1 release and re-open this ticket if the problem persists.
