### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by giovannipds** [cviebrock/eloquent-sluggable#251]
Hello! Just to inform you guys that the build is failing. Somebody should fix it.
Best regards, Gio.

**Comment by cviebrock** [comment]
Thanks for the heads up!

**Comment by giovannipds** [comment]
Hello! You're welcome.
But, ... it seems it is still failing. I wouldn't close the issue, if I were you :laughing:.
Best wishes, Gio.

**Comment by cviebrock** [comment]
Fixed it now.  Damn case-sensitive file systems. :)

**Comment by giovannipds** [comment]
o/ passing! Great, that's essential for attracting other developers to use the project. :smiley:

**Comment by giovannipds** [comment]
Hello. @cviebrock, build is failing again. =T

**Comment by cviebrock** [comment]
Yeah, if you figure out what, that'd be great. :)

Tests run fine locally, so I'm not sure if it's something about the Travis environment.

Any help is appreciated.

**Comment by giovannipds** [comment]
Oh, no, I'm sorry, I haven't used this project, specifically because of the build failure. =T

**Comment by cviebrock** [comment]
FWIW, the builds were failing because Laravel 5.3 doesn't support PHP 5.5 or HHVM and I didn't update the `.travis.yml` file accordingly.

Things are good now, so feel free to use the project. ;)
