### ISSUE TITLE
Strange problem with Persian(Arabic) characters

### ISSUE THREAD

**Issue by fmmajd** [cviebrock/eloquent-sluggable#253]
hi

I'm saving slugs from users' username, and usernames are mostly in Persian, something like:
دکتر.علیرضا.شیری
when I sluggify users, slugs are in a strange format, something like this:
d-tr-aal-rd-sh-r
the strangest part is, although they are in two different languages, the reshaped English slug kinda sounds like the Persian word when pronouncing.
what's happening? and is there a way I can slugs in my own language?

**Comment by cviebrock** [comment]
By default, the package uses [cocur/slugify](https://github.com/cocur/slugify) to build slugs.  It's mostly a transliteration package -- meaning that the resulting slug is supposed to "sound" like the input.  At least that's my interpretation.

If you want to swap out that "engine" for something else, you are free to do so. Take a look [here](https://github.com/cviebrock/eloquent-sluggable#getslugengine) or [here](https://github.com/cviebrock/eloquent-sluggable#method) for how to use a different method.  Alternatively, it may be you just need to add different rules to Slugify, in which case you can do something like I do in [this test](https://github.com/cviebrock/eloquent-sluggable/blob/master/tests/models/PostCustomEngine.php).

Or, just build up a [ruleset](https://github.com/cocur/slugify/tree/master/Resources/rules) for slugify and submit a pull request to them. It doesn't look like they have a Persian rule set, so I'm sure they'd appreciate it!

**Comment by omidgholami074** [comment]
i used this function in my Post model but rules not applied:
`    public function customizeSlugEngine(Slugify $engine, $attribute)
    {
        $engine->activateRuleSet('persian');
        return $engine;
    }`
