### ISSUE TITLE
Question: Override config for specific usecase

### ISSUE THREAD

**Issue by canfiax** [cviebrock/eloquent-sluggable#255]
I have sluggable for my User model, for the `slug` parameter. However, I also have a `Username` field, that I would like to ensure is unique, if not, it should prepend a `-1` like it uses to.

Is there someway in a method to temporary override the configs, just for a specific usecase? I.e. to change "build from" to `username`.

**Comment by canfiax** [comment]
My fix:

	            	/**
	            	 * Well leverage Sluggable to generate a unique username. We will temporarily change the behavior for this purpose
	            	 * @var [type]
	            	 */
	            	
		            	$originalSluggableConfigs = $this->sluggable; // store
		            	$this->sluggable = [
		            		'build_from' => 'slug',
		            		'save_to' => 'username',
		            		'seperator' => ''
		            	];

		            /**
		             * Sluggify.
		             */

	            		$this->resluggify()->save();

	            	/**
	            	 * Revert changes to default behavior
	            	 */

						$this->sluggable = $originalSluggableConfigs; // revert

**Comment by cviebrock** [comment]
So you build to `slug` normally, and then build _from_ `slug` to `username`?

**Comment by canfiax** [comment]
Yeah

**Comment by cviebrock** [comment]
That seems ... odd.  But okay.

I think you'd be able to do this in version 4.0 which supports multiple slugs per model.  You'd just need to define the config for `slug` first, then `username`:

```php
public function sluggable() {
    return [
        'slug' => ['source' => 'whatever' ],
        'username' => ['source' => 'slug'],
    ];
}
```

**Comment by cviebrock** [comment]
Try on version 4.0 and re-open if you are still having issues.
