### ISSUE TITLE
"No seperator" not possible

### ISSUE THREAD

**Issue by canfiax** [cviebrock/eloquent-sluggable#256]
It is not currently possible to chose to have no separator. If I set config like this:

		            	$this->sluggable = [
		            		'build_from' => 'slug',
		            		'save_to' => 'username',
		            		'seperator' => ''
		            	];

It will believe 'separator' is NULL, and revert to default behaviour that is a dash `-`.

I use the following helper in my projects to detect if a string is NOT empty, not to confuse with NULL or a negative value.

**Comment by cviebrock** [comment]
This is fixed in the `rewrite` branch which I'll release shortly.
