### ISSUE TITLE
Not working if the language is Russian

### ISSUE THREAD

**Issue by iwbace777** [cviebrock/eloquent-sluggable#257]
I am using this `package` for slug. But this is working well for English. But not working well for Russian, Korean, Chinese, Japanese and etc.
Do you have any suggestion for this?
Regards.

**Comment by cviebrock** [comment]
You would need to modify the underlying `Cocur\Slugify` object to handle this.  Doing this is now supported in version 4.0.0 via the `customizeSlugEngine` method.
