### ISSUE TITLE
return null getExistingSlugs

### ISSUE THREAD

**Issue by andregaldino** [cviebrock/eloquent-sluggable#263]
the method getExistingSlugs this returns null or a string and not one collection,I changed the method for lists and worked up correctly. 
sorry for my English

SlugService.php

```
protected function getExistingSlugs($slug, $attribute, array $config)
    {
        $includeTrashed = $config['includeTrashed'];

        $query = $this->model->newQuery()
            ->findSimilarSlugs($this->model, $attribute, $config, $slug);

        // use the model scope to find similar slugs
        if (method_exists($this->model, 'scopeWithUniqueSlugConstraints')) {
            $query->withUniqueSlugConstraints($this->model, $attribute, $config, $slug);
        }

        // include trashed models if required
        if ($includeTrashed && $this->usesSoftDeleting()) {
            $query->withTrashed();
        }
        // get the list of all matching slugs
        return $query->lists($attribute, $this->model->getKeyName()); //here
    }
```

**Comment by cviebrock** [comment]
Laravel's `lists()` method is an alias of `pluck()` so changing one for the other shouldn't make a difference.  Plus, `lists()` is deprecated since Laravel 5.2.

**Comment by roshangautam** [comment]
I have the same problem of getting a null from this method.

In this case $query is an instance of query builder and not a collection. For a collection 'lists' is an alias of 'pluck' but for a query builder its not hence returning null. Changing it to lists does work.

**Comment by cviebrock** [comment]
Hmm ... do you happen to be using Laravel 5.1?

In 5.2, `\Illuminate\Database\Query\Builder::lists()` is a (deprecated) alias for `\Illuminate\Database\Query\Builder::pluck()`.  In 5.1, it appears that `lists()` has the correct functionality, whereas `pluck()` is a (deprecated) alias for `value()`.

And, to make it worse, `lists()` is gone entirely in 5.3 and `pluck()` is what we should use.

So, I stand by my use of `pluck` in the package.  But if we want it to work with Laravel 5.1, I'll need to figure out a switch in that method.

**Comment by roshangautam** [comment]
Yes, i am using 5.1

**Comment by cviebrock** [comment]
Can you try `dev-master`? I just pushed a check for the Laravel/Lumen version so it will use `lists()` or `pluck()` where appropriate.

**Comment by roshangautam** [comment]
Your fix is working. On a different note, I Just realized theres no onUpdate config any more ?

**Comment by cviebrock** [comment]
No.  First, it was problematic, trying to figure out all the scenarios where onUpdate would and wouldn't apply.

Second, I think for the majority of users, onUpdate was left as false: if a slug is already set, then don't try and re-slug the model.  This makes sense: you don't want URLs, or other things based on slugs, etc. changing randomly in your app.

Third, if you really want to reslug your model, just do `$model->slug = null` before saving.

**Comment by roshangautam** [comment]
That in fact makes sense. 

In a different method but seems like a similar version compatibility issue which might require L5.1 check

SlugService@getExistingSlugs

This function is returning a list of array in L5.1 if similar slugs exist in database. I am using route model binding if that helps.

**Comment by roshangautam** [comment]
the changes you made to getExistingSlugs recently is causing it to return array instead of collection in L5.1 which is causing an issue in makeSlugUnique method as you can't call $list->contains($slug) on an array hence resulting in the following error:

> Call to a member function getKey() on string

**Comment by cviebrock** [comment]
Are you sure that's the issue? Because `getExistingSlugs` uses `pluck`, which returns a Collection in both 5.1 and 5.2 (and 5.3).

Can you paste some code that reproduces the issue?

**Comment by roshangautam** [comment]
Here's my model class

http://laravel.io/bin/6LKzV

**Comment by cviebrock** [comment]
Found the bug. Pushing a fix shortly.

**Comment by roshangautam** [comment]
Great. Thanks.
