### ISSUE TITLE
Wrong service provider class name

### ISSUE THREAD

**Issue by shadoWalker89** [cviebrock/eloquent-sluggable#266]
In the README you are using 

Cviebrock\EloquentSluggable\ServiceProvider::class,

But in the code the class is 'SluggableServiceProvider'

Same for the configuration publishing command

**Comment by shadoWalker89** [comment]
There is something wrong.

I installed the package using the command in the readme file but the file structure of the downloaded package is different from the one in github.

I have all of the files in one directory, there is no SlugService class ...

**Comment by cviebrock** [comment]
`composer require cviebrock/eloquent-sluggable:4.*`

- Colin

**Comment by shadoWalker89** [comment]
Is it possible for you do update the README ??

**Comment by cviebrock** [comment]
I've updated the readme on master.
