### ISSUE TITLE
Slug not created on create

### ISSUE THREAD

**Issue by Mochaka** [cviebrock/eloquent-sluggable#267]
For some reason the slug isn't being created on a new item. I check the query logs and it's not running any slug queries. So when i add an item i've had to do $item->resluggify(); $item->save(); to create it. 

Running Laravel 5.2.

Thanks

**Comment by cviebrock** [comment]
Well, version 4.0 of the package doesn't have a `resluggify()` method anymore, so I'm assuming you are using the 3.* version?

Can you upgrade with `composer require cviebrock/eloquent-sluggable:~4.0@dev` and re-open if the problem persists?

**Comment by ijunaidali** [comment]
what is the alternative of resluggify() then?

**Comment by cviebrock** [comment]
You shouldn't need `resluggify` to create a slug on a new item, so I suspect there is something else going on.

But, doing `$model->slug = null; $model->save();` is the equivalent

**Comment by ijunaidali** [comment]
yes you are right I was using resluggify() in migration to make slug of existing records but now I am doing following:

foreach ($rates as $rate) {
            //$rate->resluggify();//depricated in eloquent-sluggable 4.1
           $rate->slug($rate);
             $rateRepository->save($rate);
         }
