### ISSUE TITLE
Slugging does not occur If the sluggable field and the source are the same

### ISSUE THREAD

**Issue by shadoWalker89** [cviebrock/eloquent-sluggable#270]
Hi,

Slugging does not occur If the sluggable field and the source are the same

**Comment by cviebrock** [comment]
Nor should it, I would think.  How would that work?

**Comment by shadoWalker89** [comment]
I have a form field for the slug. In my case the slug is not derived from another field but the value of the slug field it self in the form is the one being slugged.

In my project i have a pages module where the user will specify the uri of the page using the slug field.

The user can say something like "contact us" and it should be transformed to "contact-us"

I think you shouldn't make such restrictions and let the user choose decide freely what is the source field.

**Comment by cviebrock** [comment]
I get what you're trying to do.  But then I don't think this package is what you need.

My idea was to make it easy to _automatically_ generate slugs based on other fields in the model (e.g. generate the URI from the page's title field, etc.). What you are discussing is having users _manually_ specify the field ... in which case you can get away with Laravel's built in validation rules to ensure uniqueness, and built in functions like `Str::slug` to make the strings URI-friendly.

If you can submit a PR that allows the source field for a slug to be the same as the destination field, and some related tests, I'd be happy to consider it.  But I do feel that what you are asking is outside the scope of this package.

**Comment by shadoWalker89** [comment]
@cviebrock My table, model have a field called "slug". I am actually saving the slug into the database.
So this shouldn't make any difference for you.

The only difference in my case, is that i'm using the same field for the source and destination instead of using the title field.
If i make another field and call it "slug_raw" and use it as a source for the "slug" field in my model things will work again. But this is not a clean way to go about it.

By the way i'm using you package in my articles module where i have the title as the source for the slug.
But in my pages module, i wanted to have the possibility to have the title different from the slug, and that is why i have a slug field on my form.

**Comment by jordanade** [comment]
Would be useful for me too. The main use for me is the checking existing slugs and generating unique ones. In my case I don't actually want to store the source string at all.
