### ISSUE TITLE
How to create slug from title or slug field

### ISSUE THREAD

**Issue by ideasvn** [cviebrock/eloquent-sluggable#272]
Hello,

I want automatic create slug from title or slug field. How to config it?

**Comment by shadoWalker89** [comment]
Well you can do this, as i did

```php
public function sluggable()
    {
        return [
            'slug' => [
                'source' => ! empty($this->slug) ? 'slug' : 'title'
            ]
        ];
    }
```

But the problem is that the package doesn't support having the source and destination field the same.
I actually opened an issue about this https://github.com/cviebrock/eloquent-sluggable/issues/270

**Comment by cviebrock** [comment]
Again, I'm not sure why you want to create a slug from a slug field.  If you did `source=>title`, then it would store the generated slug in the slug field.  If you save the model again (changing some other attribute), then the slug field will remain the same.

The package won't slug a model if the destination attribute has a value.  This is to prevent slugs from constantly being calculated (and possibly overwritten) in cases where they shouldn't be.  You don't want your post URLs changing randomly, right? ;)

If you want to regenerated a slug field from the source, set `$model->slug = null` before saving.

See #270 for more discussion on source and dest fields being the same.  I'm still not convinced this is a use-case for the package.
