### ISSUE TITLE
FindBySlugOrIdOrFail not available

### ISSUE THREAD

**Issue by dashracer** [cviebrock/eloquent-sluggable#273]
Hi, I've updated the library to the latest version for laravel 5.1.
But there is an error

`
BadMethodCallException in Builder.php line 2093:
Call to undefined method Illuminate\Database\Query\Builder::findBySlugOrIdOrFail()
`

How can I fix this?

[https://github.com/cviebrock/eloquent-sluggable](url)

**Comment by cviebrock** [comment]
https://github.com/cviebrock/eloquent-sluggable/blob/master/UPGRADING.md#other-changes

`findBySlugOrIdOrFail()` has been removed from the package.  You'll need to reimplement it in your application code.
