### ISSUE TITLE
Count on null

### ISSUE THREAD

**Issue by dashracer** [cviebrock/eloquent-sluggable#275]
Hi, I've found new error
can you help me?
`
FatalThrowableError in SlugService.php line 244:
Call to a member function count() on null
`

**Comment by cviebrock** [comment]
Sounds similar to #274.  What version of Laravel are you using?

**Comment by dashracer** [comment]
5.1

**Comment by cviebrock** [comment]
Can you test the `dev-master` version of the package (as opposed to `4.0.0-beta`).  I made some changes to account for the differences between L5.1 and 5.2 yesterday.

**Comment by dashracer** [comment]
I'ts working

Thanks

**Comment by cviebrock** [comment]
Cool!  Actually, if you wouldn't mind updating the package again, I simplified the code that handles 5.1/5.2 differences in a40261428f2bbbe567b842deae389dc58a9f664a.  Would love to confirm it works for you as well. :)

**Comment by dashracer** [comment]
Slug not changing when updating eloquent object.
I've set on_update to true in general config and specific model

**Comment by cviebrock** [comment]
`on_update` doesn't exist anymore.  The general idea is that if you have a slug already for an object, you likely don't want to regenerate it.

If you do, simply do `$model->slugField = null` before saving/updating.

**Comment by dashracer** [comment]
Okay

The library is working perfectly :bow:

**Comment by cviebrock** [comment]
💃

**Comment by sinamiandashti** [comment]
how can i update my lib?
composer update works?

**Comment by sinamiandashti** [comment]
@cviebrock

**Comment by dashracer** [comment]
Yes you can use composer update and set the library using dev-master

**Comment by cviebrock** [comment]
The package is out of beta right now, so this should work:

```sh
composer require cviebrock/eloquent-sluggable:^4.0
```

**Comment by ELBOUDALI4257** [comment]
what is the solution for that error ?

Builder->__call('findSimilarSlugs', array(object(Post), 'slug', array('source' => 'title', 'maxLength' => null, 'method' => null, 'separator' => '-', 'unique' => true, 'uniqueSuffix' => null, 'includeTrashed' => false, 'reserved' => null, 'onUpdate' => true), 'hi-my-love')) in SlugService.php


         "php": ">=5.5.9",
        "laravel/framework": "5.3.31",
        "cviebrock/eloquent-sluggable": "4.0"

**Comment by cviebrock** [comment]
I'm not sure what error you are having ... the same as OP?

If so, please start with the latest version of the package for your version of Laravel.  This should figure out the right version for you:

```sh
composer require cviebrock/eloquent-sluggable
```

If that doesn't work, and you are indeed on Laravel 5.3, then version `^4.1` of the package should work.  That version is four years old now, however, so it's no longer maintained.
