### ISSUE TITLE
slug arabic language 

### ISSUE THREAD

**Issue by abanoubsamaan** [cviebrock/eloquent-sluggable#276]
it works fine but when i am trying to use Arabic title , i see the generated slug in English characters 
how can i make the slug in Arabic as well ?

**Comment by cviebrock** [comment]
Because the package uses https://github.com/cocur/slugify as the underlying slug engine, you would need to add rules via the [customizeSlugEngine](https://github.com/cviebrock/eloquent-sluggable#customizeslugengine) configuration.

(FWIW, this appears to the be file that's used: https://github.com/cocur/slugify/blob/master/Resources/rules/arabic.json)

**Comment by abanoubsamaan** [comment]
i have modified it to Arabic instead of English characters and now it generates "-1 , -2 , -3"

**Comment by cviebrock** [comment]
Can you post some of your code here? Specifically your sluggable configuration for your model or anything else you've customized?

**Comment by abanoubsamaan** [comment]
i have found the problem in this line , the Regex doesn't allow Arabic characters
`const LOWERCASE_NUMBERS_DASHES = '/([^A-Za-z0-9]|-)+/';`
i have tried to change it to `'/([^أ-يA-Za-z0-9]|-)+/' but i am not sure how can i handle this

**Comment by abanoubsamaan** [comment]
i mean in this file 
`Slugify.php`

**Comment by abanoubsamaan** [comment]
I've solved it by changing the Regex to 
 `/([^\p{Arabic}a-zA-Z0-9]+|-+)/u`
thanks

**Comment by cviebrock** [comment]
You might want to raise an issue with the https://github.com/cocur/slugify package and let them know.

**Comment by c1t1zen** [comment]
'method' => function ($string, $separator) {
                $arabic = 'اأآؤءئبتثجحخدذرزسشـصضطظعغفقكلمنهوية';
                return strtolower(preg_replace('/[^a-z0-9~%.:_-'.$arabic.']+/i', $separator, $string));
                },

**Comment by TnCoders** [comment]
@c1t1zen  where you place that code ?

**Comment by TnCoders** [comment]
I Got it @c1t1zen  it's in Sluggable.php config file

**Comment by cviebrock** [comment]
See #338:

```php
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    $engine->activateRuleset('arabic');
    return $engine;
}
```

**Comment by AmrAlmagic** [comment]
this [solution ](https://github.com/Nodekits/Eloquent-sluggable-Arabic)works well with me.

**Comment by WaelMz** [comment]
> 
> 
> ```
> 'method' => function ($string, $separator) {
>             $arabic = 'اأآؤءئبتثجحخدذرزسشـصضطظعغفقكلمنهوية';
>             return strtolower(preg_replace('/[^a-z0-9~%.:_-'.$arabic.']+/i', $separator, $string));
>             },       
> ```

located in config\sluggable.php

thanks @c1t1zen
