### ISSUE TITLE
NotFoundHttpException when using Route-Model-Binding

### ISSUE THREAD

**Issue by PENDOnl** [cviebrock/eloquent-sluggable#277]
Hi,

strange issue: I'm using your package on two projects, both copied from the same source project, using the same Laravel version (5.1.37 LTS) and the same Eloquent-Sluggable version (^3.1). Both have the service provider in config/app.php, both have the same Content.php model, both even have the same routes (in the same group, same middelware). But still, one project is working as it should while the other throws a NotFoundHttpException when visiting the route.

The route is pretty simple:
```php
Route::get('{content}', ['as' => 'content.show', 'uses' => 'ContentController@show']);
```

The RouteServiceProvider contains:
```php
// This does work
router->bind('content',       function($value) {
            return \App\Content::findBySlugOrIdOrFail($value);
});

// This does not work
$router->model('content',       \App\Content::class);
```

The model is pretty basic:
```php
    class Content extends Model implements SluggableInterface
    {
        use SluggableTrait;

        protected $table = 'pages';

        protected $sluggable = [
            'build_from'    => 'menu_text',
            'save_to'       => 'slug',
            'on_update'     => true,
        ];
```

Creating a new 'Content' works, it also sets the slug in the database. However calling the route throws an error in one project and shows the page on another. As you can see I've made another binding for the model in RouteServiceProvider that does work, so I can go on with the project. However, I still want to find out where the error comes from as there are (as far as I know) no differences in the project.

If there's anything else you'd need to know, just let me know. Thanks for your time.

**Comment by yohannca** [comment]
Hi @PENDOnl 

With version 3.1 you may need add the following in `bootstrap/app.php`

```php
$app->singleton(
    'router',
    Cviebrock\EloquentSluggable\SluggableRouter::class
);
```

**Comment by PENDOnl** [comment]
Thanks @yohannca, did I miss that in the docs? That was indeed the single difference between both projects! Problem solved.
