### ISSUE TITLE
`on_update` function for the newest version of your package

### ISSUE THREAD

**Issue by UnrulyNatives** [cviebrock/eloquent-sluggable#278]
Hi, 
the `on_update` option, or just ability to regenerate a slug for any istance of a model was extremely useful to me. It disappeared in the newest version of your package.

 I had this crude way of making sure all models have an updated slug after manual edits by moderators:

        foreach($object as $o) {
            $o->save();
        }
Can you please help me - I cannot find it in the docs:
how regenerate a slug?

**Comment by fede91it** [comment]
+1 here

**Comment by cviebrock** [comment]
Does this not work:

```php
foreach($object as $o) {
    $o->slug = null;
    $o->save();
}
```

**Comment by antennaio** [comment]
+1 I'd be great to have this feature added back

**Comment by cviebrock** [comment]
I don't think I'll be adding it back unless someone comes up with a PR for it.  The logic behind trying to figure out when and when not to re-slug a model was full of problems and edge cases.

In my opinion, it's was easier to just have you set the field to `null` before saving.  That will force a re-slug.

**Comment by antennaio** [comment]
Fair enough @cviebrock, thanks for your explanation.

**Comment by dees040** [comment]
Simple solution: add an updated event to the model. Like so:

```
public static function boot()
{
    parent::boot();

    static::updated(function($model) {
        $isModified = (new SlugService())->slug($model, true);
        $model->save();
    });
}
```

**Comment by cviebrock** [comment]
Or upgrade the package to v4.0.2 where I added `onUpdate` back in.  :)
