### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by hiendv** [cviebrock/eloquent-sluggable#284]
Hi, I'm sorry for not keeping up with the discussions for major changes of v4 but could you please document some release notes?
E.g. The reason behind changes of naming convention for the provider and trait, the removal of interface? Why did it come to `sluggable()` method instead of the traditional `$sluggable` attribute?
It is actually not an issue, I'm just learning. Sorry for the inconvenience.

**Comment by cviebrock** [comment]
The README.md, CHANGELOG.md, and UPGRADING.md files document _what_ changed.  There isn't anything that documents _why_ things changed, however.

I can say that part of the reasoning behind the rewrite was to move logic out of the model and into a separate service class, and to remove redundancy in the naming of things when the namespace already tells you information (e.g. `Cviebrock\EloquentSluggable\SluggableServiceProvider` => `Cviebrock\EloquentSluggable\ServiceProvider`).  This seems to be "standard" among many other high-quality packages that I've looked at and used lately, so I tried to emulate them.

As for the change from a `$sluggable` property to a `sluggable()` method ... the main reason being that a method is more flexible.  You can't have function calls inside a property declaration, so if your model's sluggable configuration needs to change based on the return of some other function, you can only do that in a method.

Hope that helps!

**Comment by hiendv** [comment]
Thank you very much.
