### ISSUE TITLE
How can I do by slug or id?

### ISSUE THREAD

**Issue by curtsheller** [cviebrock/eloquent-sluggable#285]
Can't figure this one out.

I used the 3.x version and it worked and then upgraded to 4.x package and can't figure this out.

Examples:

/lessons/1
/lessons/1/edit
/lessons/tuning-your-ukulele

Using

    public function getRouteKeyName()
    {
        return 'slug';
    }

and slug works. Without and id works.

**Comment by cviebrock** [comment]
Personally, I think trying to do route model binding with slug-or-id is a Bad Thing (tm), which is why I removed `findBySlugOrId` from the package.

A quick look at Laravel's documentation (5.2), makes me think you'd need to do something like this in your `RouteServiceProvider.php` file (untested code):

```php
public function boot(Router $router)
{
    parent::boot($router);

    $router->bind('lesson', function ($value) {
        if ($lesson = App\Lesson::findBySlugOrFail($value)) {
            return $lesson;
        }
        return App\Lesson::findOrFail($value);
    });
}
```

Let me know if this works, and I'll update the docs.

**Comment by dees040** [comment]
Just tested it. Works perfectly (with fully qualified namespace).

```
public function boot(Router $router)
{
    parent::boot($router);

    $router->bind('lesson', function ($value) {
        if ($lesson = \App\Lesson::findBySlug($value)) {
            return $lesson;
        }
        return \App\Lesson::findOrFail($value);
    });
}
```

**Comment by curtsheller** [comment]
Doesn’t work when using route model bindings. 		

	$router->model('lessons’, 'App\CSP\Models\Lesson’);

that I’m using.

This is my RouteServiceProvider.php file

public function boot(Router $router)
{
	parent::boot($router);

	$router->bind('lesson', function ($value) {
           if ($lesson = \ App\CSP\Models\Lesson::findBySlug($value)) {
	     return $lesson;
	   }
	   return \ App\CSP\Models\Lesson::findOrFail($value);
	});	

	// https://laracasts.com/series/laravel-5-fundamentals/episodes/18 <https://laracasts.com/series/laravel-5-fundamentals/episodes/18>
	//
	$router->model('assets’, 'App\CSP\Models\Asset');
	$router->model('books’, 'App\CSP\Models\Book');
	$router->model('lessons’, 'App\CSP\Models\Lesson');
	$router->model('listings’, 'App\CSP\Models\Listing');
	$router->model('loginusers’, 'App\CSP\Models\LoginUser');
	$router->model('series’, 'App\CSP\Models\Series');
	$router->model('songs’, 'App\CSP\Models\Song');

	$router->model('instruments’, 'App\CSP\Models\Instrument');
	$router->model('subjects’, 'App\CSP\Models\Subject');

	$router->model('topsites’, 'App\CSP\Models\TopSite');

	// http://laravel.com/docs/5.1/routing#parameters-regular-expression-constraints <http://laravel.com/docs/5.1/routing#parameters-regular-expression-constraints>
    	$router->pattern('id', '[0-9]+');
}

Tried the code as is and after the model bindings. Can’t get both to work.



> On Jun 27, 2016, at 9:44 AM, Dees Oomens <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Just tested it. Works perfectly (with fully qualified namespace).
> 
> public function boot(Router $router)
> {
>     parent::boot($router);
> 
>     $router->bind('lesson', function ($value) {
>         if ($lesson = \App\Lesson::findBySlug($value)) {
>             return $lesson;
>         }
>         return \App\Lesson::findOrFail($value);
>     });
> }
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/cviebrock/eloquent-sluggable/issues/285#issuecomment-228749232>, or mute the thread <https://github.com/notifications/unsubscribe/AACrSdX6RMcDPedC0EKjjJJLBWeJBv6uks5qP9OggaJpZM4I8O6E>.
> 



- - - -
Curt Sheller
Curt Sheller Publications






curt@curtsheller.com <mailto:curt@curtsheller.com>
www.curtsheller.com <http://www.curtsheller.com/>
www.learningukulele.com <http://www.learningukulele.com/>
www.howaboutmoreuke.com <http://www.howaboutmoreuke.com/>

Cell: 484 942 8040
Studio: 610 326 7295
Funky Frets: 942 415 9677

**Comment by cviebrock** [comment]
"lessons" or "lesson"?  You have one in your RouteServiceProvider, and the other in `$router->model(...)`.

**Comment by curtsheller** [comment]
It’s ‘lessons’ and I also tried ‘lessons’ in the $router->bind() call.

**Comment by cviebrock** [comment]
I suspect if you use `router->bind` with custom resolution logic in the RouteServiceProvider, then you shouldn't also be using `router-model`.

**Comment by curtsheller** [comment]
I sort of thought the same thing and will have to dive in and and see how I’m actually using ‘router-model’.

**Comment by cviebrock** [comment]
Closing this, as I think the initial issue has been resolved.  If you have more comments, feel free to add them.

**Comment by naumanahmed19** [comment]
@cviebrock  thanks for tip for me this worked in 5.3

```
Route::bind('product', function ($param) {

    if ($product = Product::whereSlug($param)->first()) {
        return $product;
    }
        return Product::findOrFail($param);
});
```
