### ISSUE TITLE
Use alternate field if source would generate an empty slug

### ISSUE THREAD

**Issue by rickselby** [cviebrock/eloquent-sluggable#286]
I've got an odd case - I'm pulling in user names from an external source. One of them comes through as '??', which slugs to an empty string. In the case of empty names, I'm using the model id as the source instead. In this case, though, the name itself is not empty.

I tried the following:

```
    public function sluggable()
    {
        // The name might generate an empty slug; so use the ID if this is the case
        $possibleSlug = SlugService::createSlug(self::class, 'slug', $this->name);
        return [
            'slug' => [
                'source' => $possibleSlug ? 'name' : 'id',
            ]
        ];
    }
```

but this results in an infinite loop, as trying to generate the slug calls sluggable()...

Is there a way to 'preview' the slug (even if it bypassed the valid / unique checks)?

**Comment by cviebrock** [comment]
Wouldn't something like this work:

```php
public function sluggable() {
  return [
    'slug' => [
      'source' => $this->name == '??' ? $this->id : $this->name
    ]
  ];
}
```

**Comment by rickselby** [comment]
I could, but that would only catch this one case. If I get any other names that resolve to an empty slug, it'd miss them.

**Comment by cviebrock** [comment]
What about a custom model attribute that handles your logic:

```php
class MyModel extends Model {

  public function sluggable() {
    return [
      'slug' => [
        'source' => 'slug_source'
      ]
    ];
  }

  public function getSlugSourceAttribute() {
    // custom logic goes here
   return $someCondition ? 'name' : 'id';
  }

}
```

**Comment by rickselby** [comment]
Yes, that's pretty much what I'm trying to do. The custom logic, in my mind, would be to test what the slug of the ``name`` would be. But I can't do that, because calling ``createSlug`` calls ``sluggable``...

**Comment by cviebrock** [comment]
Ah ... I get it.  Yeah, that isn't going to work.

I think you'd need to use some other logic, other than a call to `createSlug` to test what the slug will be.  Unless you're doing something fancy with the slug engine, maybe a simple regex match would work?

**Comment by cviebrock** [comment]
A possible solution would be for me to add an optional fourth argument to `SlugService::createSlug()` that is the array of configuration values to use for previewing a slug.  That way, if that array is sent, the method won't need to call `sluggable()` on the model again, and will prevent the infinite loop.

Let me push something to a branch and maybe you can test?

**Comment by cviebrock** [comment]
Try `dev-master` now, or wait for 4.0.3 in a few minutes.

**Comment by rickselby** [comment]
That's perfect. Thank you!
