### ISSUE TITLE
Replicate method conflit

### ISSUE THREAD

**Issue by opheliadesign** [cviebrock/eloquent-sluggable#287]
Greetings,

The `replicate()` method conflicts with the same method in `sofa/eloquence` -
```
Trait method replicate has not been applied, because there are collisions with other trait methods on App\Skill
```

Really need both packages. Ideas?

**Comment by cviebrock** [comment]
http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict

**Comment by SergioGregorutti** [comment]
@opheliadesign I'm having the same issue. If you solved the problem can you share what you did? Thanks in advance!

**Comment by opheliadesign** [comment]
@SergioGregorutti I didn't find the linked documentation to be very helpful, I'm not clear on what exactly happens when the suggestions are used. Here is what I added to my model:
```
use Sluggable, Eloquence {
        Sluggable::replicate insteadof Eloquence;
    }
```
I have no idea what this is doing to Eloquence, if its `replicate` method is now unreachable. @cviebrock  can you elaborate on this a bit? Or perhaps rename this method? No issues until the latest version.

**Comment by SergioGregorutti** [comment]
@opheliadesign Yes, I'm on the same page. Both packages are great and very popular. A clear solution will be very appreciated.

**Comment by opheliadesign** [comment]
@SergioGregorutti +1

**Comment by cviebrock** [comment]
So, obviously, you can't have a class that uses two traits, each of which have a method with the same name.  So my pacakge's `replicate` method conflicts with Eloquence's method.

I took a quick look at the other packages source code, and I have no idea what their `replicate` method is actually doing, so I can't suggest how to get the two to work together nicely.  It does seem related to the `Metable` trait, so if you don't need that, then try disabling it and things might work.

In my package, the method simply runs Eloquent's `replicate` method to create a duplicate model, and then re-slugs it.  So, my suggestion would be setting up your models to ignore my package for replication, and then handle the slugging manually.  Something like (untested code):

```php
class MyModel extends EloquentModel {
    use Sluggable, Eloquence {
        Eloquence::replicate insteadof Sluggable;
    }
}

...

// start with some model
$model = MyModel::find(1);

// replicate it (doing whatever Eloquence does)
$new = $model->replicate();

// re-slug it, either this way:
(new Cviebrock\EloquentSluggable\Services\SlugService())->slug($new, true);
// or simply setting the slug field to null and saving.
$new->slug = null;
$new->save();
```

**Comment by SergioGregorutti** [comment]
@cviebrock Thanks for taking time on this and make a suggestion.

I think that is close to be 100% functional. But, now when I make for example:

```
User::findBySlugOrId($slug);
```

I get this error:

```
Call to undefined method Sofa\Eloquence\Query\Builder::findBySlugOrId()
```

I think that is because it's using Eloquence instead of Sluggable. Any idea?

By the way, it's a pity that this two so popular packages have this conflict. It will be great if this issue is fixed "out of the box".

I'll try to tell this problem to the Eloquence owner. Maybe is easiest for him to make a fix.

Thanks again for your help!

**Comment by Younesi** [comment]
@cviebrock It would be awesome to rename replicate method to another name to avoid such conflicts.
Thanks for your cool package.

**Comment by cviebrock** [comment]
Sadly, I suspect either of us renaming the method would cause a lot of BC issues for user who only use one of the packages.  This is best solved using aliases: http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict

**Comment by TitarS** [comment]
I had a similar problem with the Nestedset package, I got to solve it like this:

```
     use NodeTrait {replicate as private replicateNodeTrait;}
     use Sluggable {replicate as private replicateSluggable;}

     public function replicate (array $ except = null)
     {
         $ this-> replicateNodeTrait ();
         $ this-> replicateSluggable ();
     }
```

ps I do not know if this decision is correct

**Comment by vunguyen91** [comment]
@TitarS thank you! it worked

**Comment by kakajansh** [comment]
PHP 8

```php
use NodeTrait, Sluggable {
    NodeTrait::replicate as replicateNodeTrait;
    Sluggable::replicate as replicateSluggable;
}

public function replicate(array $except = null)
{
    $this->replicateNodeTrait();
    $this->replicateSluggable();
}
```
