### ISSUE TITLE
How to use it for different model like Posts and Category model.

### ISSUE THREAD

**Issue by HasanSabuj** [cviebrock/eloquent-sluggable#290]
my category model- 
namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
class Category extends Model
{
	use Sluggable;
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'category_name'
            ]
        ];
    }

    protected $table='tblcategory';
    protected $primaryKey='cat_id';
    protected $fillable=[
		'category_name',
		'slug',
		'created_at',
		'updated_at'
    ];
}

my Posts model- 
namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
class Posts extends Model
{
    use Sluggable;
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'post_title'
            ]
        ];
    }
    protected $table='tblposts';
    protected $primaryKey='post_id';
    protected $casts = [
        'post_categories' => 'array',
    ];
    protected $fillable = [
	    'post_title',
	    'post_content',
	    'post_categories',
	    'post_tags',
	    'post_status',
        'slug',
        'post_image',
        'thumb_image',
        'small_image'
    ];
}
when i run this code i got a error - 
1st mysql.exe stop working
PDOException in Connector.php line 55: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

**Comment by cviebrock** [comment]
The SQL error appears to be unrelated to this package.

As for having different configurations for different models, that's easy!  Just have different `sluggable()` methods for each model.
