### ISSUE TITLE
Slug for a text in Persian language is not generated correctly

### ISSUE THREAD

**Issue by sasanbabai** [cviebrock/eloquent-sluggable#291]
Hi,
Thanks for the great package. I used it for my multilingual site and I realized that the slugs for the texts in Persian are not generated correctly. For example suppose the text "بسته اقفصادی" so the slug would be "بسته-اقتصادی" but it generates "basth-kfs-d"

**Comment by cviebrock** [comment]
You will need to look the underlying slug library, [cocur/slugify](https://github.com/cocur/slugify) to see why it's not working for you.

A quick look at https://github.com/cocur/slugify/tree/master/Resources/rules, and I don't think they have any rules for Persian.  I guess it's probably using the Arabic rules instead, which I'm guessing aren't 'exactly the same.

I'd recommend making a PR for cocur/slugify to add a Persian ruleset.
