### ISSUE TITLE
Unique not working

### ISSUE THREAD

**Issue by xoco70** [cviebrock/eloquent-sluggable#292]
Hi, 

In config/sluggable.php, I have set     'unique' => true ( default )

and I my migration, I have set a unique constraint on this field.

But when I save 2 items with the same slug, I get : 

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'qqqqqq' for key 'tournament_slug_unique'

When the next one should be with an incremental suffix 

I double checked that this unique constraint is for slug field only, so I guess incremental suffix is not working.

Any Idea why is it happening?

Laravel 5.2 - Eloquent-sluggable 3.1.4

**Comment by cviebrock** [comment]
Can you post all of your configuration, and the `sluggable()` method from your model?

Also, you said:

> But when I save 2 items with the same slug, I get ...

I assume you mean that you have 2 items with source fields that are the same. If you manually assign the slug to your model (e.g.. `$model->slug='foo'`, then the entire sluggable process is bypassed, so the unique checks are skipped.

**Comment by xoco70** [comment]
Now, I get it working without changing anything.
Sorry for bothering! You component rocks!
