### ISSUE TITLE
Slug don't update

### ISSUE THREAD

**Issue by Sprunkas** [cviebrock/eloquent-sluggable#296]
Hi. I have in sluggable.php file changed from 'onUpdate' => false to 'onUpdate' => true and in database table set slug to null as said in documentation like this:
```
        Product::where('id', $id)->update([
            'slug'          => null,
            'category_id'   => $request->input('category_id'),
            'product'       => $request->input('product'),
            'image'         => $request->input('image'),
            'price'         => $request->input('price'),
            'description'   => $request->input('description'),
        ]);
```

But slug don't update. Slug changes only when I change from `null` to `SlugService::createSlug(Product::class, 'slug', $request->input('product'))`

P.S I'm using Laravel 5.2 and 4.0^ sluggable

**Comment by cviebrock** [comment]
You might have to break that down into steps, setting the slug to null _before_ performing the update.

```php
$product = Product::findOrFail($id);
$product->slug = null;
$product->update($request->only(['category_id', 'product', 'image', 'price', 'description']));
```

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.

**Comment by vinhtruong94** [comment]
I enabled onUpdate = true for Article, 'source' is 'title'.But what if I still want to manually update my slug without changing the 'source'  ? Is there a way to do this ?

**Comment by cviebrock** [comment]
If you want to manually set the slug, then personally I wouldn't turn on `onUpdate`.

Alternatively, I think you can do `$model->update(['slug'=>'my-slug-name']);`.  I'm not 100% sure that will work (not somewhere I can check right now), but give it a try and let me know.

**Comment by vinhtruong94** [comment]
it will not work with onUpdate turned on. However, after considering the benefits of onUpdate, I will use it instead of changing anything. Thank you for your reply !
