### ISSUE TITLE
slug history with 301 redirect

### ISSUE THREAD

**Issue by oozrafa** [cviebrock/eloquent-sluggable#297]
How would you go about using this whilst keeping the slug history?
For example; I have an article with the slug "my-article", and now the slug has been updated to "my-best-article". What I want is the previous slug(s) for this article to 301 redirect to the newest slug.

So, "www.example.com/articles/my-article" will 301 redirect to "www.example.com/articles/my-best-article" - this isn't limited just to the last slug, but for all slugs for this article/

Thanks!

**Comment by oozrafa** [comment]
Also how could I get the history to work with multiple types of content?
For example; my site has blogs, articles, and gallery.
www.example.com/blogs/{slug}
www.example.com/articles/{slug}
www.example.com/gallery/{slug}
 
Also note that each content type has their own table, and so they can have the same ID across different tables (eg: a blog, an article and a gallery can all have an ID of 24).

**Comment by cviebrock** [comment]
You might want to look into one of the packages that tracks changes to Eloquent models and use that data somehow.  Something like https://github.com/Devitek/eloquent-loggable maybe.
