### ISSUE TITLE
Slug source year of date column

### ISSUE THREAD

**Issue by maesklaas** [cviebrock/eloquent-sluggable#300]
I would like to add the year of a date column to the slug. But i can not figure out how to do this. So i have a column title and a column date in my database and i would like the slug to be constructed by the title and only the year of the date.

Thanks!

**Comment by cviebrock** [comment]
Probably the easiest way is to make an accessor on your model that generates the source string and use that:

```php
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    use Sluggable;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'slug_source'
            ]
        ];
    }

    public function getSlugSourceAttribute()
    {
        return $this->title . '-' . date('Y', $this->date);
    }
}
```
