### ISSUE TITLE
eloquent-sluggable with Laravel 5.3

### ISSUE THREAD

**Issue by dees040** [cviebrock/eloquent-sluggable#302]
Is it me or does eloquent-sluggable not work with Laravel 5.3. I just updated my project from 5.2 to 5.3 and it seems that models are empty when loading a page which get the model through the slug from the route.

**Comment by dees040** [comment]
Not sure it this is a bug from the package. Because if I do it be ID I get the same results.

**Comment by dees040** [comment]
Fixed, see: https://github.com/laravel/framework/issues/14830

**Comment by cviebrock** [comment]
Reopening this as a reminder to update my docs when I get back from holiday.

**Comment by xoco70** [comment]
I have the same issue, but the solution presented in [laravel/framework#14830](https://github.com/laravel/framework/issues/14830) didn't work for me :(

**Comment by tabacitu** [comment]
Same here. v3.x doesn't seem to work on Laravel 5.3
Any solutions?

**Comment by cviebrock** [comment]
I can guarantee that v3.x won't work on Laravel 5.3.

Have you both implemented the middleware as per https://github.com/cviebrock/eloquent-sluggable/blob/master/ROUTE-MODEL-BINDING.md#laravel-53-note ?

**Comment by tabacitu** [comment]
My problem was that I was running v3.x. After updating to v4.x on a fresh Laravel 5.3 installation I can confirm it works like a charm. You can close the issue from my perspective.

Thank you for a great package and keep up the good work.
Cheers!

**Comment by cviebrock** [comment]
Thanks for the info @tabacitu.  @xoco70 ... are you still having issues?

**Comment by xoco70** [comment]
When I update to v4.x, I get a new error.

PHP Fatal error:  Uncaught ReflectionException: Class auth does not exist in /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Container/Container.php:734

When I revert to v.3, it passes, but still the same issue.

**Comment by cviebrock** [comment]
That error doesn't appear to have anything to do with my package. 😟 

Maybe post a bit more detail in order to help debug the issue:

* your model, or at least the `public function sluggable()` method
* contents of your `app/config/sluggable.php`
* some snippet of code where you save/update a model that triggers the error

**Comment by xoco70** [comment]
sluggable.php without comments

<?php

return [
    'build_from' => null,
    'save_to' => 'slug',
    'max_length' => null,
    'method' => null,
    'separator' => '-',
    'unique' => true,
    'include_trashed' => false,
    'on_update' => false,
    'reserved' => null,
];

I use it in 2 models, here are my 2 sluggable variables:
User.php:
protected $sluggable = [
        'build_from' => 'email',
        'save_to' => 'slug',
    ];

Tournament.php:
    protected $sluggable = [
        'build_from' => 'name',
        'save_to' => 'slug',
    ];


For the log, the only thing I have is : 

php artisan optimize
PHP Fatal error:  Uncaught ReflectionException: Class auth does not exist in /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('auth')
#1 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('auth', Array)
#2 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(699): Illuminate\Container\Container->make('auth', Array)
#3 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Container/Container.php(1182): Illuminate\Foundation\Application->make('auth')
#4 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(176): Illuminate\Container\Container->offsetGet('auth')
#5 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(145): Illuminate\Support\Facades\Facade::resolveFacadeInstance('auth' in /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
PHP Fatal error:  Uncaught ReflectionException: Class auth does not exist in /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('auth')
#1 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('auth', Array)
#2 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(699): Illuminate\Container\Container->make('auth', Array)
#3 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Container/Container.php(1182): Illuminate\Foundation\Application->make('auth')
#4 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(176): Illuminate\Container\Container->offsetGet('auth')
#5 /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(145): Illuminate\Support\Facades\Facade::resolveFacadeInstance('auth' in /home/vagrant/Code/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
Script php artisan optimize handling the post-update-cmd event returned with error code 255

I have no clue where is issue. In fact, my code should already be 5.3 compatible :( I have already solved my auth issues, changing my 5.1 auth files to 5.3 structure, so it should not be that neither....

**Comment by xoco70** [comment]
I fixed it using v3, and changing just one reference from lists to vendor in SluggableTrait.php

As I said, if I use v4, I get the auth class error. :(

**Comment by cviebrock** [comment]
You said:

> I use it in 2 models, here are my 2 sluggable variables:
> User.php:
> protected $sluggable = [
> 'build_from' => 'email',
> 'save_to' => 'slug',
> ];
> 
> Tournament.php:
> protected $sluggable = [
> 'build_from' => 'name',
> 'save_to' => 'slug',
> ];

The configuration has changed significantly between 3.x and 4.x.  Please see [UPGRADING.md](https://github.com/cviebrock/eloquent-sluggable/blob/master/UPGRADING.md) for all the details.

For starters, config options are now camelCase instead of snake_case, and per-model configuration is handled in a method, not a property.  

Republish the [global configuration file](https://github.com/cviebrock/eloquent-sluggable/blob/master/resources/config/sluggable.php), and then something like this in your models should help you:

```php
// User.php:
public function sluggable() {
  return [
    'slug' => [
      'source' => 'email',
    ]
  ];
}

// Tournament.php:
public function sluggable() {
  return [
    'slug' => [
      'source' => 'name',
    ]
  ];
}
```

**Comment by sharif-codder** [comment]
Hello, I have updated the sluggable version from 3.0 to 4.1.2 and every thing is configured as said in the update documentation but after updating i can't create any post when i create a post an error show in builder.php ( ErrorException in Builder.php line 1231: count(): Parameter must be an array or an object that implements Countable). I have searched a lot in google for this solution but did't get any solution but after removing  the slugg i can create easily post there was no error. Please help me to fixed this issu
