### ISSUE TITLE
Error in tests

### ISSUE THREAD

**Issue by Luddinus** [cviebrock/eloquent-sluggable#303]
Hi,

I cannot test a slug, it gives this errors:

```
ErrorException: explode() expects parameter 2 to be string, array given

C:\Users\Luddinus\AppData\Roaming\Composer\vendor\illuminate\support\helpers.php:404
C:\wamp\www\testing\vendor\laravel\framework\src\Illuminate\Support\Arr.php:369
C:\wamp\www\testing\vendor\laravel\framework\src\Illuminate\Support\Collection.php:476
C:\wamp\www\testing\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:1231
```

Normal code that works outside of test:

```
$user = User::first();
$casting = new Post;
$casting->user_id = $user->id;
$casting->title = 'Hello World';
$casting->save();
```

// Post sluggable (basic stuff)
```
return [
    'slug' => [
       'source' => 'title',
    ]
];
```

Why is that?

Thx.

**Comment by cviebrock** [comment]
The "normal" code you posted seems fine, and the configuration seems fine as well.

The error message you posted doesn't show any of my package's files, so I'm not sure where the error is being thrown.  Also, posting the test code that causes the error would be helpful.

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.

**Comment by Luddinus** [comment]
@cviebrock Sorry, I didn't remember this issue.

The error was that I was using a laravel helper function somewhere ("array_last" I think). Switching to Arr::last fixed the error.
