### ISSUE TITLE
SluggableScopeHelpers Trait

### ISSUE THREAD

**Issue by msonowal** [cviebrock/eloquent-sluggable#305]
Trait 'Cviebrock\EloquentSluggable\SluggableScopeHelpers' not found

in my modal
```
use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;

class BlogPost extends Model
{
    use Sluggable;
    use SluggableScopeHelpers;
```
I want to use find by slug scope helper etc, it's not working m using latest version "cviebrock/eloquent-sluggable": "4.0"

Please help

**Comment by cviebrock** [comment]
Make sure you are on the latest version (4.0.3) by running `composer require cviebrock/eloquent-sluggable`, and make sure your autoloader is updated with `composer dump-autoload`.

The class name you have seems fine, so it's something that's just causing that class to not be found.
