### ISSUE TITLE
[5.3.1] array_merge(): Argument #1 is not an array

### ISSUE THREAD

**Issue by DeeJaVu** [cviebrock/eloquent-sluggable#307]
Hello after upgrading my laravel 5.3.0 project to laravel 5.3.1 i get this error when creating a new category

**Comment by DeeJaVu** [comment]
ohhh this error is because the app\config\sluggable.php did not exist in my config folder !!

**Comment by cviebrock** [comment]
You can publish the configure with the artisan command.
