### ISSUE TITLE
Can't create slugs in L5.3

### ISSUE THREAD

**Issue by ChristianGiupponi** [cviebrock/eloquent-sluggable#310]
I have installed the `^4.0` version of the package and followed the docs but I'm not able to make it work.

I have added the `trait`, the `provider` and added the `sluggable` method in my Model.

Now with this code, the package fails:

```
$data = [
    'title' => 'My title'
];
MyModel::create($data);
```

**Comment by ChristianGiupponi** [comment]
Sorry, my fault with the sluggable method

**Comment by cviebrock** [comment]
How does it fail?  Can you provide a bit more information, like your model class (including the `sluggable` configuration method)?

Also, did you publish the config with:

```sh
php artisan vendor:publish --provider="Cviebrock\EloquentSluggable\ServiceProvider"
```

**Comment by cviebrock** [comment]
Ah ... ok!
