### ISSUE TITLE
L 5.3 - Call to undefined method Illuminate\Database\Query\Builder::findBySlugOrFail()

### ISSUE THREAD

**Issue by kayyyy** [cviebrock/eloquent-sluggable#312]
I updated my Application to Laravel 5.3

Unfortunately i cant get my Records by the Slug. If i go to my Slug Record i am getting the above Error. With my Laravel 5.1 Application it was all working. Some Details which may help:

**My Model**

```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Tutorial extends Model
{
    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug'
        ];
    }
```

**My TutorialController Method**

```
public function show($slug)
    {
        $tutorial = Tutorial::findBySlugOrFail($slug);
        return view('tutorials.show', compact('tutorial'));
    }
```

**My Routes**

```
Route::group(['as' => 'tutorials.', 'prefix' => 'tutorials'], function () {
    Route::get('/', [
        'as' => 'index', 'uses' => 'TutorialController@index'
    ]);
    Route::get('{slug}',[
        'as' => 'show', 'uses' => 'TutorialController@show'
    ]);
});
```

The Table Column Name  `slug` exists. The default Config is also published.

Can someone help me to fix this Error?

**Comment by cviebrock** [comment]
https://github.com/cviebrock/eloquent-sluggable/blob/master/SCOPE-HELPERS.md

**Comment by bto132** [comment]
Thanks a lot for the documentation, I had the same problem, but now everything is clear, we must use the helper "whereSlug ()", Thanks cviebrock!

**Comment by uzairs** [comment]
Thanks a lot cviebrock

**Comment by rpaez861125** [comment]
Thanks a lot cviebrock
