### ISSUE TITLE
Doesn`t work with L5.3

### ISSUE THREAD

**Issue by Malin88** [cviebrock/eloquent-sluggable#316]
Hi, 
probably, this will be very small problem.

I have Laravel 5.3 nad want to generate slugs for users.

composer - done
publish - done

my code:
```
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Cviebrock\EloquentSluggable\Sluggable;


class User extends Authenticatable
{
    use Notifiable, Sluggable;
```

end dafinition my class is underline with message:

> Class must by declared abstract or implement method 'sluggable'

I tried to add **implements Sluggable** but nothing has changed.

What am I doing wrong ?

**Comment by isurindu** [comment]
add this function 


       /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

**Comment by Malin88** [comment]
omg sorry for that, big THX!

**Comment by cviebrock** [comment]
Thanks @isurandu!

**Comment by cviebrock** [comment]
@Isurindu, I mean. :)

**Comment by isurindu** [comment]
he he @cviebrock welcome
