### ISSUE TITLE
Unique slug group by category

### ISSUE THREAD

**Issue by subhendugiri** [cviebrock/eloquent-sluggable#318]
I have a Model as Post and wanted to "Title" as unique slug . But the condition is that I have multiple categories and Title Slug should be unique for that particular categories.

That means.
for CategoryA slug will be this-is-my-title, this-is-my-title-1
for CategoryB slug will be this-is-my-title, this-is-my-title-1

My Router has
	Route::get('post/{category-slug}/{post-slug}', 'PostController@getPostbyCategory');

My Model has
    class Posts extends Model {
        //protected $primaryKey = 'id';
        //protected $table='posts';
        protected $fillable = [
            'title,
            'body',
            'slug',
            'category_id',
            'user_id'
        ];
    }

I am using the version Laravel 5.1.x. Would like to have unique slug group by category or other fields.

**Comment by cviebrock** [comment]
You probably want to specify a [scopeWithUniqueSlugConstraints](https://github.com/cviebrock/eloquent-sluggable#scopewithuniqueslugconstraints) in your model that adds a `where(...)` condition to limit the unique constraint per category.

Take a look at https://github.com/cviebrock/eloquent-sluggable/blob/master/tests/Models/PostWithUniqueSlugConstraints.php for an example using posts and authors.  Your solution would be identical, except it would be categories instead of authors.

**Comment by subhendugiri** [comment]
Thank you @cviebrock. I missed that part in the docs

**Comment by insight-media** [comment]
I'm also using this scope method, because i want to scope a certain language when creating a unique slug.

    public function scopeWithUniqueSlugConstraints(Builder $query, Model $model, $attribute, $config, $slug)
    {
        if($model->locale)
        {
            return $query->where('locale', $model->locale);
        }
        else {
            return $query;
        }
    }

But how does this work when i want to create a slug manually with the 'createSlug' method ?

When i use the scopeFindSimilarSlugs scope, model->locale returns null.

    public function scopeFindSimilarSlugs(Builder $query, Model $model, $attribute, $config, $slug)
    {
        dd($model->locale);
    }

**Comment by fatoskurtishi** [comment]
> I'm also using this scope method, because i want to scope a certain language when creating a unique slug.
> 
> ```
> public function scopeWithUniqueSlugConstraints(Builder $query, Model $model, $attribute, $config, $slug)
> {
>     if($model->locale)
>     {
>         return $query->where('locale', $model->locale);
>     }
>     else {
>         return $query;
>     }
> }
> ```
> 
> But how does this work when i want to create a slug manually with the 'createSlug' method ?
> 
> When i use the scopeFindSimilarSlugs scope, model->locale returns null.
> 
> ```
> public function scopeFindSimilarSlugs(Builder $query, Model $model, $attribute, $config, $slug)
> {
>     dd($model->locale);
> }
> ```

Did you find any solution ? Still have same problem when i use: **SlugService::createSlug()** manually for check slug and this happens only when model is not created or updated.
