### ISSUE TITLE
Eloquent-Sluggable

### ISSUE THREAD

**Issue by oscaraa** [cviebrock/eloquent-sluggable#319]
Hi, I have a problem, I tried to use sluggable for a project in Laravel, the problem is when I used in my model
```
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;


class Article extends Model implements SluggableInterface
{
     
  use SluggableTrait;


    protected $sluggable = [
          'build_from' => 'title',
          'save_to' => 'slug'
      ];
```
I put the command php artisan make:migration it showed an error
[Symfony\Component\Console\Exception\RuntimeException]
Not enough arguments (missing: "name")

And I don't know why :C

**Comment by cviebrock** [comment]
Please use the most recent version of the package.  It looks like the above is for an older version.
