### ISSUE TITLE
Cross-model slugs

### ISSUE THREAD

**Issue by qodeboy** [cviebrock/eloquent-sluggable#320]
Hello,

Right now the package is designed to work with slugs withing single model. We are able to define `FindSimilarSlugs` scope and/or `WithUniqueSlugConstraints` on a model and it does the job of finding duplicated slugs.

But I currently can't find a way how to make my slugs unique across all models. So let's say we have an "Article" and a "Product" models (both sluggified). And we want the routing to be prefix-less.

In other word, if particular article is being sluggified with "foo", then it could be loaded in the browser at http://domain.ltd/foo. At the same time, if particular product is being sluggified with "bar", then it could be found at http://domain.ltd/bar. 

This brings uniquness problem. If slugs for article and product will match, only one of them could be loaded/found. 

To fix this, I would like to be able to define an `FindSimilarSlugs` or `WithUniqueSlugConstraints` scope  (or other mechanics) which could look into all sluggable-enabled models to find out if the new slug is already being used on some model.

Is it possible with current design?

Of cource, I can solve this by having an prefix for both models, so that first one will be "articles/foo" and second would be "products/foo", but I would really want to avoid this.

**Comment by cviebrock** [comment]
Off the top of my head, I can't see an easy way to look for all "sluggable" models.

What you might want to try is a new model that is is sluggable, instead of Articles and Products, and define a relation between that and your other models.

I'd have to fiddle for a bit to figure out the mechanics, and I'm on my phone, but i bet you could come up with something that worked that way.

**Comment by qodeboy** [comment]
After investigating this further, I see 2 options available here.

**Option A: Use Slug model and have relations to it from all business models.**

*Quick spec:*
- Create database which will store all slugs. Spec:
  - ```id``` (autoincrements)
  - ```model_id``` (polymorphic)
  - ```model_type``` (polymorphic)
  - ```slug``` (string).
- Create ```Slug``` model for this table.
- Slug model will have ```Sluggable``` trait.
- Slug model will define ```sluggable()``` method which would load related (business) model and pull it's config.

*Problems:*
* The logic becomes non-trivial, as we need to store config in business models, and pull it from Slug model.
* We lose ability to transparently generate slugs on business models with an observer, because business models are not sluggable now (sluggable trait is used only on Slug model).
* The ```getExistingSlugs``` method doesn't work with this approach, because the results returned by the query are keyed by primary key of the Slug model and not business model.
* It is non-trivial to store all slugs in one table, because package supports multiple slug attributes per model, so we would need to support storing this in one table as well. This may be solved by additional ```attribute``` (string) column, but package code is not designed to pick up this change.

**Option B: Store slugs in their respective models and override SlugService to handle cross-model slug uniquness.**

*Quick spec:*
- All business models are sluggable.
- Slugs are stored in the respective business model's tables.
- SlugService should allow override of ```getExistingSlugs``` so that developer may provide own implementation of it, which will look into all models to decide if slug is already used.
- Optional: have centralized "read-only" table which will list all slugs and their models. This just to make querying slugs easier.

*Problems:*
- Additional effort needed from developer, but I guess it is ok, as we are all geeks ;)
- Right now SlugService is not bound to the container, making it impossible to override implementation.

---

For my project, I decided to go with Option B, as level of efforts is a lot lower. I will create an PR to fix problem where SlugService implementation is not overridable.

**Comment by liran-co** [comment]
@qodeboy do you have this implemented yet? Would you be willing to provide your implementation?

**Comment by cviebrock** [comment]
I'm on vacation right now, so not in the mind-set to do anything code-related.  But if someone wanted to update @qodeboy 's MR #322 which binds the SlugService to the container, and resubmit ... that is likely the easiest way to get cross-model slugs working.
