### ISSUE TITLE
separator for model configuration not working

### ISSUE THREAD

**Issue by carloss993** [cviebrock/eloquent-sluggable#323]
Trying to override the default configuration on my model, like so:

        'author-slug' => [
            'source' => ['author.firstname', 'author.lastname'],
            'separator' => '.'
        ],

The source is ok, but the separator key is getting overwritten by the default value in config/sluggable.php

**Comment by cviebrock** [comment]
Did you figure this out?  If so, do you mind posting the solution here for other people?
