### ISSUE TITLE
How to generate slugs for existing model

### ISSUE THREAD

**Issue by timersys** [cviebrock/eloquent-sluggable#324]
Hi! not a bug more a question. I got a table with lot of records and I want to generate the slugs. 
Which would be the good way of creating them ?
I added the field to the tables. There is an artisan  command I can run to generate all of them now?

Thanks

**Comment by tyler36** [comment]
I recently updated mine through the following commands.
```
php artisan tinker
Model::get()->each(function($item){ $item->save(); })
exit
```

It may take some time if you have lots of models

**Comment by timersys** [comment]
Ty, I tried the same but simple on the controller and It didn't work well as I got 300k records. Then I tried with chunks but that didn't work either. Will try your solution... Thanks

**Comment by adriandmitroca** [comment]
I've found a much quicker way to achieve this basically with no coding at all.

```php
config(['sluggable.onUpdate' => true]);
Model::all()->each->save();
```
