### ISSUE TITLE
Slug generation mistake

### ISSUE THREAD

**Issue by KonstantinFilin** [cviebrock/eloquent-sluggable#325]
I have this strange thing:
https://github.com/laravel/framework/issues/16326

Think there is an error in this library too (use it in my project, version 4.1.1)

**Comment by cviebrock** [comment]
Are you using the default slug engine (i.e. [cocur/slugify](https://github.com/cocur/slugify)) or Laravel's `Str::slug`, or something else?

**Comment by KonstantinFilin** [comment]
I use your library with default setting according to default settings (in config/sluggable.php 'method' => null) according to manual

**Comment by cviebrock** [comment]
I just added a test to the package with exactly your settings:

https://github.com/cviebrock/eloquent-sluggable/blob/master/tests/BaseTests.php#L332-L343

And it passes.  So, there must be something else going on if you are seeing the slug being generated as `RDA-125-15/30/45m³/h CAV`.

Can you paste your `config/sluggable.php` file, and your Model file?

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
