### ISSUE TITLE
System onUpdate not working!

### ISSUE THREAD

**Issue by WESLEY-PEARSON** [cviebrock/eloquent-sluggable#326]
I'm trying to use onUpdate System inserting this parameter as said in documentation:

In my model Post

```php
public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'article_title',
				'onUpdate' => true
            ]
        ];
    }
```

In my controller, this function:

```php
public function newPost (Request $request, $id)
 {
            $post= Post::findOrFail($id); 

            $this->validate($request, [
                     'article_title' => 'required',
            ]);

            Post::update([
            'article_title' => $request->input('article_title'),
	]);					
}
```

Instead when I set  the slug to null before performing the update:

```php
$this->validate($request, [
                     'article_title' => 'required',
            ]);

$post= Post::findOrFail($id);
$post->slug = null;

            Post::update([
            'article_title' => $request->input('article_title'),
	]);	
```

I get this Laravel error:

Creating default object from empty value.

**Comment by cviebrock** [comment]
First, please edit your issue to get the code formatting correct.  It makes it harder to understand your questions.

Second, `Post::update([...])` will update *all* the posts in your database.  I'm pretty sure that's not what you want.

```
$post= Post::findOrFail($id);

$post->update([
    'article_title' => $request->input('article_title')
]);
```

should do it.

**Comment by WESLEY-PEARSON** [comment]
Thanks for your reply but I have tried again and the title is updated but not the slug.

**Comment by WESLEY-PEARSON** [comment]
Ok, I have fixed the problem!

I have edited $post = Post::findorFail($id)  with Post::where('slug', $id)->first();

**Comment by cviebrock** [comment]
`Post::findOrFail($id)` searches the primary key of the _posts_ table for the value you pass it.

If you are trying to do Route Model binding, then read [this](https://github.com/cviebrock/eloquent-sluggable/blob/master/ROUTE-MODEL-BINDING.md).

**Comment by WESLEY-PEARSON** [comment]
Thanks!
