### ISSUE TITLE
Storing old slugs to allow redirects to 'canonical' slug

### ISSUE THREAD

**Issue by amitailanciano** [cviebrock/eloquent-sluggable#328]
Would be awesome to see this package functionality extended to include the storage of previous slugs in some polymorphic bridge table, so you can have some middleware to redirect old slugs to the most recent 'canonical' slug

**Comment by alfonsobries** [comment]
+1

**Comment by liran-co** [comment]
+1

**Comment by IllesAprod** [comment]
+1

**Comment by CDNRocket** [comment]
+1

**Comment by cviebrock** [comment]
Long time without any movement on this, but the solution here probably falls into the category of things that could be done if all the slugs were stored in one polymorphic table, as opposed to a field in each model's table.

Adding the `polymorphic-table` milestone to this ... but there is no time frame for doing this, presently.

**Comment by cviebrock** [comment]
Just thinking out loud here ... you could probably also achieve this via the event cycle: listen to the `slugging` or `slugged` event, and storing the old slug in a table when it changes.

**Comment by cviebrock** [comment]
I'm closing this old ticket.  I never did get around to looking into using a polymorphic table for slugs (I may in the future, but I have no burning need for it presently).  I also think similar functionality could be achieved using the event system.
