### ISSUE TITLE
Is it possible to create a unique slug based on account ID?

### ISSUE THREAD

**Issue by AvengersArmy** [cviebrock/eloquent-sluggable#329]
I have two tables as follows:

Accounts Table with fields:
- id
- name

Posts Table with fields:
- id
- account_id
- name
- slug

All Posts above belong to different accounts, hence i would like to generate a unique slug based on the account itself using the name of the post. For instance 'sample-post' could exist twice in the posts table but it needs to be for two different account_id. If it is already used, then 'sample-post-1' should be generated.

Any advice?

**Comment by cviebrock** [comment]
This is a perfect candidate for [scopeWithUniqueSlugConstraints](https://github.com/cviebrock/eloquent-sluggable#scopewithuniqueslugconstraints).

The docs suggest looking at `/Models/PostWithUniqueSlugConstraints.php` for an example.
