### ISSUE TITLE
Slug not generate on creating model?

### ISSUE THREAD

**Issue by lucassena** [cviebrock/eloquent-sluggable#331]
The package generate slug only on saving event for default?

**Comment by cviebrock** [comment]
That is correct. If you want it to generate on an update event, you can set that in your configuration.

Or am I missing something ... what's your issue?

**Comment by lucassena** [comment]
For example, when I use `\App\Models\Status::create([['nome' => 'Teste']]);`, the slug is not generating. Or am I doing something wrong?

**Comment by cviebrock** [comment]
I think you are doing something wrong.  Some quick things to check:

1. `config/app.php` has `Cviebrock\EloquentSluggable\ServiceProvider::class` added to the providers?
2. Published the default config with `php artisan vendor:publish --provider="Cviebrock\EloquentSluggable\ServiceProvider"`?
3. Does your `\App\Models\Status` class `use Cviebrock\EloquentSluggable\Sluggable`?
4. Does your class have a `sluggable()` method that returns the configuration for the slug field?

**Comment by lucassena** [comment]
My bad, the correct code is `\App\Models\Status::create(['nome' => 'Teste']);`
