### ISSUE TITLE
Unique setting not working with Globalscope

### ISSUE THREAD

**Issue by mirzavu** [cviebrock/eloquent-sluggable#332]
When I save the User model, the slug column is set with the name, but the unique config is not working. 

I am using Laravel 5.2 with eloquent-sluggable 4.1

This is my sluggable function
```
public function sluggable()
    {
        return [
            'slug' => [
                'source' => ['name'],
                'unique' => true
            ]
        ];
    }
```

This is my app/config/sluggable.php

```
return [
    'source' => null,
    'maxLength' => null,
    'method' => null,
    'separator' => '-',
    'unique' => true,
    'uniqueSuffix' => null,
    'includeTrashed' => false,
    'reserved' => null,
    'onUpdate' => false,
];
```

The global scope is like this
```
static::addGlobalScope('userStatus', function(Builder $builder) {
            $builder->where('users.status_id', '=', 1);
        });
```

**Comment by biohazardhome** [comment]
What you think is it possible to use this solution for this problems
`static::registerModelEvent('slugged', function() {
    static::addGlobalScope('published', function(Builder $builder) {
        $builder->published();
    });
});`

**Comment by cviebrock** [comment]
I'm closing this old issue because it references an out-of-date version of the package.

Feel free to re-open or comment if you are still having issues with the latest version.

**Comment by benswinburne** [comment]
For anyone else having problems with this, I added the following method to my model in order to remove the global scope(s) while looking for rows with slugs.

    /**
     * Query scope for finding "similar" slugs, used to determine uniqueness.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $attribute
     * @param array $config
     * @param string $slug
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeFindSimilarSlugs(Builder $query, $attribute, $config, $slug)
    {
        return $query->withoutGlobalScope('userStatus');
    }

Obviously this removes a specific scope but you could use either of the following too

    $query->withoutGlobalScopes();

    $query->withoutGlobalScopes(['scope1', ['scope2']);

**Comment by cviebrock** [comment]
Thanks @benswinburne!  Would you care to make a merge request, adding this information to the README file?
