### ISSUE TITLE
How do we get the row id instead of the different numbers?

### ISSUE THREAD

**Issue by cuneydtural** [cviebrock/eloquent-sluggable#335]
For example
http://www.tgrthaber.com.tr/egitim/aof-sinav-giris-yerleri-aciklandi-aof-giris-yerleri-tikla-ogren-158367
news title - news id ?

**Comment by cviebrock** [comment]
Not really sure what you were asking here (and I apologize for not responding earlier).

If `aof-sinav-giris-yerleri-aciklandi-aof-giris-yerleri-tikla-ogren-158367` is your slug, then you can just do a query to find the related model.  Something like:

```php
$model = Model::where('slug', $slugString)->firstOrFail():
```
