### ISSUE TITLE
Find on multiple Slug fields

### ISSUE THREAD

**Issue by prodixx** [cviebrock/eloquent-sluggable#337]
Hello!

I have a model with multiple slug fields setup like this:
`public function sluggable(){

        return [
            'Slug_en' => [ 'source' => 'Name_en' ],
            'Slug_es' => [ 'source' => 'Name_es' ],
            'Slug_fr' => [ 'source' => 'Name_fr' ],
            'Slug_it' => [ 'source' => 'Name_it' ],
            'Slug_de' => [ 'source' => 'Name_de' ],
        ];
}`

I want to findBySlug on all of them, i have tried with slugKeyName but no luck. Is there something im missing?

Thank you

**Comment by cviebrock** [comment]
I think a custom SQL query is your best option here.  Something like:

```
$items = Model::newQuery()->whereRaw('? in (Name_en, Name_es, Name_fr)', $string);
```
