### ISSUE TITLE
Arabic Slug

### ISSUE THREAD

**Issue by TnCoders** [cviebrock/eloquent-sluggable#338]
Hi, Im using this package and the problem is  only english text is slugified while arabic for example is not.

i found this but ut's in persian and 2 years ago:
https://github.com/morilog/eluquent-sluggable-persian

 so  can you please tell me how to to to have arabic slug ?

EDIT: After some search i tried this solution and not working 

in Slugify.php changing the Regex from

const LOWERCASE_NUMBERS_DASHES = '/([^A-Za-z0-9]|-)+/';

to

const LOWERCASE_NUMBERS_DASHES = '/([^\p{Arabic}a-zA-Z0-9]+|-+)/u';

nothing work

i Tried this function in sluggable.php config file and also not working:

'method' => function ($string, $separator) {
            $arabic = 'اأآؤءئبتثجحخدذرزسشـصضطظعغفقكلمنهوية';
            return strtolower(preg_replace('/[^a-z0-9~%.:_-'.$arabic.']+/i', $separator, $string));
            },   

Any Idea ?

**Comment by cviebrock** [comment]
As per the [customizeSlugEngine docs](https://github.com/cviebrock/eloquent-sluggable#customizeslugengine), in your model that uses Sluggable, try adding:

```php
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    $engine->activateRuleset('arabic');
    return $engine;
}
```

**Comment by TnCoders** [comment]
Just Discovered another Problem ::


First when i added the function on My ModelTranslation  nothing work on update

the slug was not updated:

Im combining this Package with Dimsav Laravel Translate :+1: 

foreach (['fr', 'en', 'ar'] as $locale) {

                $grille->translateOrNew($locale)->name = $request->input('name_'.$locale);
            }
ANd this is not Trigering the Slugify


On Create an arabic Tittle was  Like this : ozyr-sh-on-lshb-b-o-lry-d-lsyd-m-gdolyn-lsh-rny-tstkbl-mdyr

So what can i do ?

**Comment by TnCoders** [comment]
Sorry i just found this onUpdate' => true, the update work Good but i have still issu with Arabic.

وزيرة شؤون الشباب والرياضة

Converted to

ozyr-sh-on-lshb-b-o-lry-d-lsyd

SO in my Model I Have this:

`
use Cocur\Slugify\Slugify;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
class GrilleTranslation extends Model
{
    use Sluggable;

    public $timestamps = false;
    protected $fillable = ['name', 'slug'];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name',
                'onUpdate' => true
            ]
        ];
    }
    public function customizeSlugEngine(Slugify $engine, $attribute)
    {
        $engine->activateRuleset('arabic');
        return $engine;
    }

}`

**Comment by cviebrock** [comment]
This sounds like an issue with how Slugify (the engine) is handling Arabic characters.  Can you try something like this:

```php
$string = 'وزيرة شؤون الشباب والرياضة';
$slugify = new \Cocur\Slugify\Slugify();
$slugify->activateRuleset('arabic');
echo $slugify->slugify($string);
```

If you get the same response, i.e. "ozyr-sh-on-lshb-b-o-lry-d-lsyd", then maybe post a bug report over at https://github.com/cocur/slugify/issues.  In fact, it looks like there already is one: cocur/slugify#137

**Comment by TnCoders** [comment]
Hi @cviebrock  Yep the same Problem  the echo show ozyr-sh-on-lshb-b-o-lry-d

**Comment by TnCoders** [comment]
Any news ABout the Arabic Problem ?? any one can help ?

**Comment by cviebrock** [comment]
This really isn't an issue with this package.  It's either an issue with cocur/slugify not transliterating the Arabic characters into the correct ASCII characters (i.e. `مرحبا` -> `marhabaan`), or not converting an Arabic sentence into a URL-friendly version (i.e. `x y z` -> `x-y-z`).

Worst case: update your Sluggable configuration and specify a [custom slug method](https://github.com/cviebrock/eloquent-sluggable#method).

**Comment by mkwsra** [comment]
@cviebrock This is very strange, I have used this library before and it was working fine for Arabic!

**Comment by cviebrock** [comment]
Please open another issue if you are still having problems.  Editing your original comment from 3 months ago doesn't make it easy to follow the flow of the conversation.

**Comment by AmrAlmagic** [comment]
this [solution ](https://github.com/Nodekits/Eloquent-sluggable-Arabic)works well with me.
