### ISSUE TITLE
Disable unique slugs

### ISSUE THREAD

**Issue by Cannonb4ll** [cviebrock/eloquent-sluggable#341]
I temporarly want to disable slugging on a specific model (because i'm doing my custom language queries and such), but how would I go about this?

**Comment by kikky7** [comment]
I am looking for a similar solution. I want my slugs to be unique by default, but I want to disable this option on the certain models (i.e. through the variable $uniqueSlugs = false). I see this is added for the upgrade; so my question is when we can expect this upgrade to be available?

**Comment by cviebrock** [comment]
I'm not sure I understand your question, @kikky7.

For a model, you can disable uniqueness by updating the configuration array:

```php
public function sluggable()
{
    return [
        'slug' => [
            'source' => 'title',
            'unique' => false,
        ]
    ];
}
```

**Comment by shdehnavi** [comment]
`unique` and slug `separator ` don't work in options !
`public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title',
                'separator' => '/',
            ]
        ];
    }`

when `my post` sent as slug, this converted to `my-post`
