### ISSUE TITLE
Slug was not generated on Model updated

### ISSUE THREAD

**Issue by TnCoders** [cviebrock/eloquent-sluggable#342]
Hi All,

I recently want to add the Sluggable on my model,So I added a slug Column and when I updated my slug nothing was generated.
But when I put something in the slug column manually and run my edit it's generated.
So I understand if the slug is empty it will not generate anything on update.

The problem is I have  many data already in the Database And I wanted to add slug to the model

**Comment by yuks** [comment]
You can generate slugs for your existing models. Check this #324

**Comment by cviebrock** [comment]
Did you publish the configuration file, and/or set a `public function sluggable()` method on your model? If so, can you paste both?

Also, make sure your model uses the trait: `use Cviebrock\EloquentSluggable\Sluggable;`

**Comment by TnCoders** [comment]
Yep Everything is well configured.

I just figured out what is wrong.

```
 public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title',
                'onUpdate' => true
            ]
        ];
    }
```

This is my table
![slug_generate](https://cloud.githubusercontent.com/assets/24681177/22446881/6919c962-e74f-11e6-8885-a090ce865605.PNG)

I just added the Slug column to it and it's empty.

1/ I just updated my Data to trigger the sluggable function. But nothing happened.

I manually added something like "test" to slug so maybe it will not generate the slug when it's empty and nothing the slug was not generated correctly.

So I decided to add manually the correct slug to test if it work.
I manually added the correct Slug for "SOCCER FR" like this "soccer-fr". Then I updated my Title to SOCCER FR UPDATE 2" and the slug was correctly generated.

So I think when update you are looking for the slug By Slug to update it.

**Comment by mojoblanco** [comment]
I just tried it and everything seems to work fine. Maybe you should try the installation again and follow the guidelines

**Comment by cviebrock** [comment]
I agree ... this seems like something is misconfigured on your end.

One question though: what is the SQL structure for your table?  Specifically, is the `slug` field set to `DEFAULT NULL` or `DEFAULT ""`?

**Comment by worthers** [comment]
@cviebrock - which should it be? DEFAULT NULL or DEFAULT ""?

We have the exact same problem actually. Interestingly though, the problem occurs on some people's set up and not others. It's as if some slight difference in either PHP or MySQL in how it handles an initial blank value?..

**Comment by cviebrock** [comment]
I'm not sure, actually.  In the tests, I use `$table->string('slug')->nullable();` but I see other projects that use the package and make the field non-nullable.

**Comment by worthers** [comment]
Ok, interesting. I have found that it is some associated code that causes the problem. 

I have the following on the Model which gets run when the app boots up: 
```
class Page extends Model
{
    use Sluggable;
    public static function getTableNameForSitemap()
    {
        return (new static())->getTable();
    }
}
```

**Comment by cviebrock** [comment]
I'm not sure how that code would affect things.  But, how are you running that code when the app boots?

**Comment by andresgutgon** [comment]
> I'm not sure, actually. In the tests, I use $table->string('slug')->nullable();

Hi @cviebrock this is an old issue but is a question I have. I'm reading the README and I see that the field should be `NULLABLE`. Is there in the docs an explanation why?

**Comment by cviebrock** [comment]
@andresgutgon I don't recall offhand ... but I'm pretty sure it has to do with https://github.com/cviebrock/eloquent-sluggable/blob/master/README.md#when-is-a-model-slugged

If you use the method that slugs a model after it's saved, then we need to persist some "pre-slugged" value to the `slug` field when the model is first saved, and then afterwards (when the slug string is generated), that model can just get updated with the new `slug` field.  That "pre-slugged" value would just be the default value in the DB ... in this case, null.  So the field should be nullable.

Does that make sense?

**Comment by andresgutgon** [comment]
> Does that make sense?

Yes, thanks!

In Rails world there's [before_save](https://api.rubyonrails.org/v7.1.1/classes/ActiveRecord/Callbacks/ClassMethods.html) (yes, I'm a Ruby guy loving PHP and Laravel). Doesn't have Eloquent something like this?

**Comment by cviebrock** [comment]
Yes, Laravel has a `saving` event which can also be used. The issue as far as slugging goes, is that if you want to use the model’s primary key as part of the slug, it won’t be available until after it’s persisted to the DB and the `saved` event fires. 

My package supports both via configuration. If you don’t need the PK in your slug, then you can save one DB call by switching to the before-saved configuration.
