### ISSUE TITLE
Which version should I use for Laravel 5.0?

### ISSUE THREAD

**Issue by Mahmoudz** [cviebrock/eloquent-sluggable#344]
The versions table doesn't mention with which eloquent-sluggable does Laravel 5.0 work!?

**Comment by cviebrock** [comment]
I can't recall, but I'm pretty sure there was an issue with L5.0 that prevented this package from working well.  Give the 4.1 version a try, and if that doesn't work, then 4.0.

If neither of those work, then you'll need to upgrade Laravel in order to use this package.  Sorry!

**Comment by Mahmoudz** [comment]
I am trying to upgrade an old project from Laravel 4.2 to 5.4. And I must go through Laravel 5.0 while upgrading..!

**Comment by cviebrock** [comment]
Ok.  So try what I said.  Worst case, just upgrade Laravel from 4.2 to 5.0 then 5.1, then upgrade my package.
