### ISSUE TITLE
Wrong error message : reserved instead of uniqueSuffix

### ISSUE THREAD

**Issue by Lelectrolux** [cviebrock/eloquent-sluggable#345]
In slug service, line [268 to 275](https://github.com/cviebrock/eloquent-sluggable/blob/master/src/Services/SlugService.php#L268) : 

        $method = $config['uniqueSuffix'];
        if ($method === null) {
            $suffix = $this->generateSuffix($slug, $separator, $list);
        } elseif (is_callable($method)) {
            $suffix = call_user_func($method, $slug, $separator, $list);
        } else {
            throw new \UnexpectedValueException('Sluggable "reserved" for ' . get_class($this->model) . ':' .     $attribute . ' is not null, an array, or a closure that returns null/array.');
        }

The exception thrown says reserved instead of uniqueSuffix.

**Comment by Lelectrolux** [comment]
Btw, is their a way to have uniqueness and prevent creation of doubles instead of adding a suffix ?

**Comment by cviebrock** [comment]
Fixed the typo a while back ... thanks!

If you are looking for a way to make a slug that already exists unique, that would be something you code yourself in the `uniqueSuffix` closure.  Just do anything you want in that function to make a new, unique slug.
