### ISSUE TITLE
Define 'save_to' in model?

### ISSUE THREAD

**Issue by xitude** [cviebrock/eloquent-sluggable#347]
Since updating, I can no longer define the `save_to` in my Model to define what field I want the slug to be on.

**Comment by cviebrock** [comment]
The configuration array has changed, and the `save_to` field is now the key of the array (which allows for multiple slugs per model).  Take a look at https://github.com/cviebrock/eloquent-sluggable/blob/master/UPGRADING.md#configuration-changes
