### ISSUE TITLE
Installation problem with laravel 5.3.30

### ISSUE THREAD

**Issue by basith374** [cviebrock/eloquent-sluggable#348]
Problem 1
    - Installation request for cviebrock/eloquent-sluggable ^4.2 -> satisfiable by cviebrock/eloquent-sluggable[4.2.1].
    - Conclusion: remove laravel/framework v5.3.30
    - Conclusion: don't install laravel/framework v5.3.30
    - cviebrock/eloquent-sluggable 4.2.1 requires illuminate/support ^5.4 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.9].
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.3.30
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.3.30
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.3.30
    - Installation request for laravel/framework (locked at v5.3.30, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.30].

**Comment by cviebrock** [comment]
As per the [installation notes](https://github.com/cviebrock/eloquent-sluggable#installation), you should use version ^4.1 of the package if you are on Laravel 5.3.
