### ISSUE TITLE
slug does not get generated when I set it manually to a slug value that is already taken

### ISSUE THREAD

**Issue by nermamax** [cviebrock/eloquent-sluggable#349]
Example there is already slug: "whatever-slug" associated with another model.

I am updating second model and I allow user to set update it's slug, user decides to change it to "whatever-slug" and in my controller I do 

`$post->slug = $request->slug;`

When I try to save the model I get 

Integrity constraint violation: 1062 Duplicate entry 'whatever-slug' for key 'posts_slug_unique' (SQL: update `posts` set `slug` = whatever-slug, `updated_at` = 2017-03-17 14:18:56 where `id` = 31)

What I would like to happen when I set slug to a value that is not unique, I would like it to generate slug
'whatever-slug-1'

Is this configurable or is this not implemented right now? Would it be possible to implement?

**Comment by cviebrock** [comment]
This isn't supported right now.  The main purpose of the package is to _auto-generate_ slugs based on other field values, not handle manual settting of slugs.

If you are doing validation on the incoming request data, then just adding a `unique:models,slug` constraint in your rules should help.

**Comment by nermamax** [comment]
ok thanks I understand, I have come up with another solution since I need users to be able to manually set the slug if they want and get a unique slug back
