### ISSUE TITLE
Not working on unicode

### ISSUE THREAD

**Issue by vtxmg** [cviebrock/eloquent-sluggable#350]
I have a unicode base website and while using sluggable it convert unicode title into slug in english with funny :) way. Is there any tweak to use unicode slug.?

**Comment by cviebrock** [comment]
All strings are passed through (cocur/slugify)[https://github.com/cocur/slugify] to generate the slug string.  Depending on what language you are using, you probably want to set that in a [customizeSlugEngine](https://github.com/cviebrock/eloquent-sluggable#customizeslugengine) method in your model.  e.g.

```php
/**
 * @param \Cocur\Slugify\Slugify $engine
 * @param string $attribute
 * @return \Cocur\Slugify\Slugify
 */
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    $engine->activateRuleset('turkish');  // or whatever ruleset
    return $engine;
}
```

(Sadly, it doesn't look like there is a Nepali ruleset, unfortunately.  I'm sure Slugify would love one, if you wanted to contribute!)

**Comment by vtxmg** [comment]
I got it. Now I've used the method option to create slug on Nepali unicode myself.
