### ISSUE TITLE
The letters ö and ü in Turkish are problematic.

### ISSUE THREAD

**Issue by mkoseoglu** [cviebrock/eloquent-sluggable#359]
## ENG:
In Turkish, the letter "ö" appears as "oe" and the letter "ü" appears as "ue". This is wrong.

To fix this: Update the file sluggable.php on line 47.

     'method' => function( $string, $sep  ) {

           return strtolower(str_replace(['ü', 'Ü', 'ö', 'Ö',' '], ['u', 'u', 'o', 'o','-'], $string));
         },

## Turkish: 

Türkçe'de, "ö" harfi  "oe" ve "ü" harfi "ue" şeklinde gözükmektedir. Bu hatalıdır.

Bunu düzeltmek için: sluggable.php dosyası içerisine 47. satırda güncelleme yapalım.

     'method' => function( $string, $sep  ) {

           return strtolower(str_replace(['ü', 'Ü', 'ö', 'Ö',' '], ['u', 'u', 'o', 'o','-'], $string));
         },

**Comment by cviebrock** [comment]
You should really raise this issue with [cocur/slugify](https://github.com/cocur/slugify) since that's the underlying engine that handles slug generation.

That said, it looks like it should be slugging those characters correctly, based on this ruleset: https://github.com/cocur/slugify/blob/master/Resources/rules/turkish.json

I think what you should be doing is adding the following in your model:

```php
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    return $engine->activateRuleset('turkish');
}
```

**Comment by mkoseoglu** [comment]
Great! The method worked. Thank you so much dude.

composer require cocur/slugify

`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Cocur\Slugify\Slugify;
class Article extends Model
{
    use Sluggable;

    protected $table = "articles";

    protected $fillable = [
      'title' , 'body'
    ];

    public function customizeSlugEngine(Slugify $engine, $attribute) {
      return $engine->activateRuleset('turkish');
    }

    public function sluggable()
   {
       return [
           'slug' => [
               'source' => 'title'
           ]
       ];
   }


}
`

**Comment by oLDu67** [comment]
Laravel is not supporting  closure method in config files for route cache..

>   [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Call to undefined method Closure::__set_state()

 i solved this problem 

**`'method' => ['\\Patchwork\\Utf8', 'toAscii'],`**

you should **install Patchwork** plugin.
