### ISSUE TITLE
Japonese slug is empty

### ISSUE THREAD

**Issue by xoco70** [cviebrock/eloquent-sluggable#360]
Hi, 

I recently translated my app to japonese. 

But now, all slug from japonese names are empty.

What should be the solution for that??

**Comment by xoco70** [comment]
It seems to have been already discussed on  issue #338 

Now, I will need Japonese and Korean, how should I handle both???

**Comment by xoco70** [comment]
Now, I can see Slugify does not manage Japonese characters... So I'm a bit lost about how should I manage it. Any idea?

**Comment by cviebrock** [comment]
Hrmm .. you are right.  Slugify doesn't seem to support ideographic languages like Japanese.

You could find a package that can convert a Japanese or Korean string of characters into a "roman alphabet" equivalent (i.e. a transliterator).  Maybe [JpnForPHP](https://packagist.org/packages/mbilbille/jpnforphp) would be helpful?

Basically, once you have a class/method that can convert from Japanese to a roman alphabet, you'd just use a custom `method` in your sluggable configuration .. something like:

```php
'method' => function ($string, $separator) {
   return MyTransliteratorClass::convertJpToEn($string, $separator);
}
```

**Comment by xoco70** [comment]
is posible to make it simpler, that in case of Korean or Japonese, I just use id in slug field? I didn't find how to do it in docs.

**Comment by xoco70** [comment]
The problem is Kanji is not supported with JpnForPHP and it will difficulty be... Only Katagana. Right now, I have a case of Kanji.

**Comment by cviebrock** [comment]
Yeah, that's going to be hard.  A bit of googling turns up the following, which might help:

* http://kakasi.namazu.org/index.html.en
* https://developer.yahoo.co.jp/webapi/jlp/furigana/v1/furigana.html

As for using the id field, that's possible, but not for new models (since the slugging happens before the model is saved).

**Comment by xoco70** [comment]
Ok, So I will generate a random string  in those case. 

Now, I can see 'method' param in config will be applied to all slugs, but that is not what I want.

What I would need is something like: 

```
public function customizeSlugEngine(Slugify $engine, $attribute)
    {
        if (isArabic($this->name))
            $engine->activateRuleset('arabic');
        elseif (isJaponese($this->name)) // Or Korean, or any unsupported language
         // Change method to generate a random string
        return $engine;
    }
```

I guess this is not the good method to change it... Where should I put my conditions???

**Comment by cviebrock** [comment]
I think your best bet is to make an entirely new class that implements `Cocur\Slugify\SlugifyInterface` to hand your Japanese strings.  Then, you could do:

```php
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    if (isArabic($this->name)) {
        $engine->activateRuleset('arabic');
    } elseif (isJaponese($this->name)) // Or Korean, or any unsupported language
         // change the engine entirely
        $engine = new JapaneseSluggingEngine();
    }
    return $engine;
}
```

This might require a bit of code changes in the core class (type-hinting SlugifyInterface instead of Slugify), but should work.  If you get a working version, let me know and I'll update the core.

**Comment by xoco70** [comment]
Ok, I wrote the engine that will generate a 12 random chars. It is not the best solution, but right now, it will fix the bug for all non managed languages.  

But I am not connected to your git. It's my first PR so I don't really know how this is working. Right now, I directly modified the code in vendor. 

Should I PR from there? Or should I pull the code in another folder ( but in this case, I should rewrite a lot of things to be able to test??? )

**Comment by cviebrock** [comment]
Ideally, you should follow the instructions in https://github.com/cviebrock/eloquent-sluggable/blob/master/CONTRIBUTING.md to fork the project, make your changes, and submit a PR.

If it's too much, you can just drag-and-drop the changed files here, and I'll figure it out.

Thanks!

**Comment by xoco70** [comment]
I just sent you a PR. Tell me if anything is wrong with it!

**Comment by xoco70** [comment]
One question: 

> Don't ask us to pull from your master branch

What is the difference between pulling from a feature or my master for you? In fact, I didn't see the point of creating a branch to make a PR.

**Comment by cviebrock** [comment]
If you aren't doing anything else except submitting PRs, then it doesn't matter.
