### ISSUE TITLE
registerModelEvent not behaving as expected

### ISSUE THREAD

**Issue by spacecomx** [cviebrock/eloquent-sluggable#361]
I use a base model that all the other models extend as per example below. This work fine if all models have a slug in the migration with a slug of "name". I then override the the sluggable method on any extended model that use an alternative slug, such as "title". This works.

```php
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class BaseModel extends Model
{
    use Sluggable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = ['meta' => 'array'];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => ['source' => 'name']
        ];
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }
}
```

What I have is a model that has no slug in the migration. But the model extends the BaseModel. So I use the code below in the model that requires no slug. This works, as the slug is then not required.

```php
class Question extends BaseModel
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'questions';

    public static function boot()
    {
        static::registerModelEvent('slugging', function() {
            return false;
        });
    }
}
```

But I want the move the registerModelEvent boot function to the base model and do the evaluation for which model requires a slug and which models do not. I cannot get this to work. The if statement is not been evaluated as per you documentation. See below: 

```php
class BaseModel extends Model
{
   public static function boot()
    {
        $name = strtolower(class_basename(static::class)); // "App\Question" when creating a record

        static::registerModelEvent('slugging', function() use ($name) {
            if($name == 'question') {
                return false;
            }
        });
    }
}
```

**Comment by cviebrock** [comment]
(I fixed the formatting in your original comment, for legibility.)

In your code, are you sure that `$name` equals `question`?  I wonder if it's the difference between using `static::class` and `self::class`.

You could also (maybe) avoid the use of `use ($name)` by just putting the `$name` definition inside the function closure directly?

**Comment by cviebrock** [comment]
Actually ... in short, you have a `BaseModel` that uses sluggable, but for one of your app models that extends the base model, you _don't_ want to use sluggable ... correct?

I think you could just do it with this in the "odd" class:

```php
/**
 * Override the package boot method to cancel the observer.
 */
public static function bootSluggable() {
    return null;
}
```

**Comment by waynegibson** [comment]
Using bootSluggable did the trick in the "odd" class and you right, it does not require a slug. 

On a side note: The  ```BaseModel``` class when using ```self::class``` will return the base model itself, where as ```static::class``` returns the class that extends the ```BaseMode```l class in this case.

**Comment by waynegibson** [comment]
As per the original question @cviebrock. The project has many classes extending the ```BaseModel```, and I want have all related code to live in the ```BaseModel```. The method you suggested does work, but that means I must add the ```bootSluggable``` to all the "odd" classes. 

Is there a way to do this, what do you suggest @cviebrock?

**Comment by cviebrock** [comment]
Off-hand, the only options I can thing of are to:

* make a `BaseModelWithoutSlugging` class and use that for the "odd" models.
* make a `NegateSluggable` trait and `use` that in the "odd" models.
