### ISSUE TITLE
Usage with constructor

### ISSUE THREAD

**Issue by oozrafa** [cviebrock/eloquent-sluggable#363]
How do I use this when I have a constructor for my model? Because when I do then the slug is always empty.

Thanks

**Comment by cviebrock** [comment]
That shouldn't make a difference, as long as your constructor calls the parent Eloquent constructor.

**Comment by oozrafa** [comment]
Sorry for the nubism, but what do you mean by that?

**Comment by cviebrock** [comment]
Can you post your code for your model? At least the relevant parts: the class name and any `extends ...` stuff, any `use ...;` directives, the `__constructor()` method, and the `sluggable()` method.

**Comment by oozrafa** [comment]
`
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;

class Track extends Model
{		
    use Sluggable;
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ],
            'slug_en' => [
                'source' => 'title_en'
            ],
            'slug_ru' => [
                'source' => 'title_ru'
            ]
        ];
    }

    public $mador;
    public function __construct()
    {
        $mador = \App\Mador::find(2);
        $this->mador = $mador;
       	
    }

}
`

**Comment by cviebrock** [comment]
```php
public function __construct()
{
    parent::__construct();   // <--- ADD THIS LINE

    $mador = \App\Mador::find(2);
    $this->mador = $mador;
}
```

**Comment by oozrafa** [comment]
Ah, amazing. Works great now.
Thank you very much!
