### ISSUE TITLE
Re-slugging the children.

### ISSUE THREAD

**Issue by santoshachari** [cviebrock/eloquent-sluggable#365]
I hope this example explains the case. 

`Brands` have outlets `outlets`. 

The outlet's slug is defined as: 
```php 
public function sluggable()
    {
        return [
            'slug' => [
                'source' => ['brand.name','area']
            ]
        ];
    }
```

When the Brand's name is updated, the outlet's slug is not. 

How to update the slugs for children?

**Comment by cviebrock** [comment]
There isn't a mechanism to handle this automatically, so you'll have to loop through the brand's outlets and slug them manually.  One way would be something like this:

```php
$brand->name = 'New name';
$brand->save();

$brand->outlets->each(function($outlet) {
    $outlet->slug = null; // forces reslugging
    $outlet->save();
});
```

**Comment by santoshachari** [comment]
Works! Thank you.
