### ISSUE TITLE
how solve That?

### ISSUE THREAD

**Issue by farshidrezaei** [cviebrock/eloquent-sluggable#367]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'articles.id' in 'field list' (SQL: select `a_slug`, `articles`.`id` from `articles` where (`a_slug` = مقاله-شماره-یک or `a_slug` LIKE مقاله-شماره-یک-%))

what is articles.id
i define a_id how change id to a_id ?

**Comment by cviebrock** [comment]
In your Article model, you need to change the primary key:

```php
class Article extends \Illuminate\Database\Eloquent\Model
{
    // ...

    $primaryKey = 'a_id';

    // ...
}
```
