### ISSUE TITLE
phpunit acceptance tests using a model with sluggable failing

### ISSUE THREAD

**Issue by ajoy39** [cviebrock/eloquent-sluggable#368]
Attempting to write an acceptable test using a model that includes sluggable, getting the following error message. It's failing during the setUp function. 

```
  public function setUp(){
    $user = User::create([
      'first_name' => 'Admin',
      'last_name' => 'User',
      'email' => 'admin@user.corn',
    ]);

    $role = Role::create([
      'name' => 'Admin',
      'slug' => 'admin',
      'description' => 'An Admin'
    ]);
    $role->save();
    $user->attach($role);
  }

```

And the error 

```

1) EditUserTest::test_add_property_function
Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Events\Dispatcher] is not instantiable while building [Cviebrock\EloquentSluggable\SluggableObserver].

```
The error occurs on line that creates the user, which is the model that includes sluggable. Removing that step gets rid of the error (though obviously causes a new one as there is no user to attach the role too). 

If this isn't enough information let me know, wasn't really sure what else to include

Laravel version 5.3, sluggable 4.1, phpunit 5.7.20

**Comment by cviebrock** [comment]
I'll be totally honest: I don't know what to suggest.

The event system is a bit untested in the package itself, mostly because I'm not sure how to unit test it myself.  You could try disabling events, maybe? (https://laravel.com/docs/5.3/mocking#mocking-events)  Or maybe you are supposed to mock them?

I'm sorry I don't have a good answer for you.  Let me know what you do figure out ... or hopefully someone else will stumble on this issue and comment.

**Comment by ajoy39** [comment]
Event::fake() worked, though it can't be used in the setup method so I had to create another function. $this->withoutEvents(); does not work, it looks like you Mockery relies on the packages themselves to provide some kind of template to fake. Here's the error:

BadMethodCallException: Method Mockery_0_Illuminate_Contracts_Events_Dispatcher::until() does not exist on this mock object;

that error message is produced on the line calling the model with sluggable attached, and it's just the user model, so I think the error is with sluggable not the User model. 

Event::fake() does what I needed it to do to get around the error at least, so thank you for recommending that! I will do some research over the weekend and see if I can find out how to make event mocks, obviously, it'd be preferable to just skip the events that are failing so I can still test with the rest of them. 

Thanks for your helping and for writing sluggable!

**Comment by asivaneswaran** [comment]
The Event::fake() does not work anymore on Laravel 5.5.... The slug just isn't created...

**Comment by willemo** [comment]
I just ran into this issue as well. As described above, using `Event::fake()` doesn't work. When trying to use `Event::fake()` elsewhere in my test I get the following error:

```
Argument 1 passed to Illuminate\Support\Testing\Fakes\EventFake::__construct() must implement interface Illuminate\Contracts\Events\Dispatcher, null given, called in /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/Facades/Event.php on line 21
```

Does anyone have a solution or does this mean I can't test any code that uses models that have slugs? That would be pretty bad...

**Comment by murilobd** [comment]
I'm facing the same issue! Using Laravel 5.4 here!

**Comment by pierrocknroll** [comment]
Resolved for me : if you have a setUp method, be sure to call parent::setup() as the first statement in that function.

**Comment by wvervuurt** [comment]
I am having the same issue under Laravel Framework 5.8.8, not sure why this issue was closed

**Comment by rossanoua** [comment]
@wvervuurt  can you please give little bit more info?
Example code maybe.
I can not undarstand how to solve it.
Thankyou.

**Comment by wvervuurt** [comment]
If you're having the same issue as me, adding `$this->refreshApplication();` as the first line to the DataProvider will solve the error. If that doesn't help, maybe you forgot to put `Event::fake()` in your TestCase's `boot` method. If that doesn't help, your issue is different than mine and I don't know what could be going wrong.. hope this helps!

**Comment by rossanoua** [comment]
Short update from my side.
Sorry for possible offtopic.
I'm using codeception framework.
So when I created the cest like so:
`codecept g:cest unit TestingPostModel`
the error not appear any more for model where I'm using sluggable.
Codeception have a module Laravel5, so I guess he doing some magic before execution tests, like booting app etc...
Hope this info can help someone.

**Comment by wvervuurt** [comment]
This topic is about PHPUnit tests failing, Codeception is a different testing framework altogether, so now I understand why previous comments didn't seem to help you. Thanks for adding that info, maybe it helps other Codeception users who test Sluggable models.

**Comment by mheap** [comment]
A few years on but I found this issue when I hit the same binding resolution issue.

Using Laravel 8, the solution is to extend `Illuminate\Foundation\Testing\TestCase` rather than `PHPUnit\Framework\TestCase` and add the `\Tests\CreatesApplication` trait:

```php
<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\TestCase;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\CreatesApplication;

class YourTestName extends TestCase
{

    use RefreshDatabase;
    use CreatesApplication;

    /** @test */
    public function itDoesAThing()
    {
        // Your code that creates a slug
    }
}
```

**Comment by mheap** [comment]
Yes, that’s correct
