### ISSUE TITLE
Question: How would you update models already in production?

### ISSUE THREAD

**Issue by Payetus** [cviebrock/eloquent-sluggable#375]
So in my case I have a group of models that I am binding using the id. I want to change that for a slug of the models name. The thing is how  would you go about generatint the slug for each of the old models once I have installed eloquent-sluggable.

**Comment by CodeBradley** [comment]
#324

**Comment by JosephMendez** [comment]
how? no answer?

**Comment by cviebrock** [comment]
I think the answer is given in #324 : basically, loop through all the models and "resave" them to trigger the slugging.
