### ISSUE TITLE
How to insert a NULL value for slug

### ISSUE THREAD

**Issue by RuubR** [cviebrock/eloquent-sluggable#376]
I am creating a 5 level deep menu for my website. 3 levels always need a unique slug, but 2 levels do not need a slug.
How can I insert a row in my database without executing the Sluggable event, when, for example, my $request->level == 2. 

`public function store( StoreMenu $request ) {

if( $request->level == 2) {
 //Insert without sluggable
}else{
insert with sluggable
}
}
`

**Comment by cviebrock** [comment]
Untested, but I think this would work:

1. Set the `source` of your slug to be a custom method on your model via config:

```php
public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'customSource'
            ]
        ];
    }
```

2. Configure that function to handle the logic, returning `NULL` in the case where you don't need a slug and the real field when you do (e.g. the "title" of your model):

```php
public function getCustomSourceAttribute()
{
    if (\Request::get('level') == 2) {
        return null;
    }

    return $this->title;
}
```

Let me know if that works!

**Comment by RuubR** [comment]
It works exactly how you described it! Thanks!
