### ISSUE TITLE
Sluggable on a pivot table (no model)

### ISSUE THREAD

**Issue by notflip** [cviebrock/eloquent-sluggable#378]
Since we include

    use Sluggable;

in the Model, What about pivot table? 
I have a table shop_products and I woud like to create a slug for the description field
Is it possible using pivot tables?

Thank you!

**Comment by cviebrock** [comment]
You mean you want to slug a field on the pivot table?  I've not tried that. :)

If you have a custom pivot model, you could try using Sluggable on it and see what happens.

**Comment by lloricode** [comment]
any updates here?

**Comment by lloricode** [comment]
this is solve of mine

```php
public function sluggable()
{
    return [
        'title-slug' => [
            'source' => 'title'
        ],
        'author-slug' => [
            'source' => ['author.firstname', 'author.lastname'],
            'separator' => '_'
        ],
    ];
}
```


the `author` is the relation model .

**Comment by cviebrock** [comment]
Is `PackageTransaction` the pivot model? It would extend `Pivot` I think, no?

**Comment by lloricode** [comment]
yes, it's a pivot.

**Comment by cviebrock** [comment]
Ok, so you can `use Sluggable` on a custom pivot model it sounds like, right @lloricode ?

If so, there's your solution @notflip !

**Comment by notflip** [comment]
Thanks @lloricode and @cviebrock !
