### ISSUE TITLE
Unique slugs for all models in the project

### ISSUE THREAD

**Issue by php-rock** [cviebrock/eloquent-sluggable#379]
I need to ensure the uniqueness of the slugs throughout the project.

I have some tables - blogs, posts, users, cities, etc.
How about add config option, where you can list all the tables in which you should ensure the uniqueness of the slug.
Example:
`tables = ['users','posts','cities'];`

What do you think about this feature?

**Comment by liran-co** [comment]
Anyone know the simplest way to add this functionality?

**Comment by cviebrock** [comment]
#322 would make this easy (easier) by letting you override the method to determine uniqueness.

However, I would warn against making DB checks against a whole bunch of tables.  A better solution (and one I think I'll add to the next re-write) would be to have a separate table that only stores slugs (and probably model class names), and that becomes the source-of-truth for uniqueness.

**Comment by Shpartko** [comment]
It does not seem to me a problem to make 10 requests to different models when slug changes.
But when creating a separate table with slugs, it is possible to break integrity in case of changes made manually.
At the same time, one table with all slugs of the project looks like a tempting offer. It will be easy to organize a single entry point for different models and their representations.

**Comment by lightframes** [comment]
Are you going to implement this request in the near future?

**Comment by cviebrock** [comment]
A new job is taking up most of my time these days.  It's on my list of things to look into, but there is not ETA right now.

**Comment by lightframes** [comment]
Ok thank you @cviebrock

**Comment by bloggervista** [comment]
@cviebrock  I like the idea of slugs in one table. I know it may increase query but it will be more data centric. Like Vue JS is more data centric 🗡 

Will be waiting for this feature :)
Thanks

**Comment by mafftor** [comment]
Hello everyone!
I've found the solution :)

It will work if
*  your tables have the same primary keys 'ID'
* and have the same name of slug field 'slug'

P.S. PK and slug name can be different but should stay the same for all tables that you want to check for unique slug


First of all you need to inherit package Trait (**Sluggable**) and name it for example **CustomSluggable.php**
```php
<?php

namespace App\Traits;

use App\Models\AttractionDescription;
use App\Models\CityDescription;
use App\Models\CountryDescription;
use App\Models\ExcursionDescription;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

/**
 * Class Sluggable
 *
 * @package Cviebrock\EloquentSluggable
 */
trait CustomSluggable
{
    use Sluggable;

    public function scopeWithUniqueSlugConstraints(Builder $query, Model $model, $attribute, $config, $slug)
    {
        $query->unionAll(CountryDescription::where($attribute, $slug)->select([$attribute, 'id']));
        $query->unionAll(CityDescription::where($attribute, $slug)->select([$attribute, 'id']));
        $query->unionAll(ExcursionDescription::where($attribute, $slug)->select([$attribute, 'id']));
        $query->unionAll(AttractionDescription::where($attribute, $slug)->select([$attribute, 'id']));

        return $query;
    }
}
```

Then you need to use your own created trait to all Models that must be unique
```php
<?php

namespace App\Models;

use App\Traits\CustomSluggable;
use Illuminate\Database\Eloquent\Model;

class ExcursionDescription extends Model
{
    use CustomSluggable;

    protected $fillable = [
        'name',
        'description',
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name',
                'onUpdate' => true,
            ]
        ];
    }
}

```

You can add a new table to this list but don't forget to duplicate new query line in CustomSluggable trait and use it in new Model file as well

**Comment by tmtung144** [comment]
> It does not seem to me a problem to make 10 requests to different models when slug changes.
> But when creating a separate table with slugs, it is possible to break integrity in case of changes made manually.
> At the same time, one table with all slugs of the project looks like a tempting offer. It will be easy to organize a single entry point for different models and their representations using a single query.

I support controlling all slug in one table, for now I still have to customize it myself without using this package, manual repairs can be bound by the primary key between the tables.

**Comment by shirshak55** [comment]
@tmtung144 regarding query i think u need 2 query one to find slug and other to find resources. So isn't query increased by 1? Because i think slug lookup is done to find associated resources for general use case.

**Comment by cviebrock** [comment]
Long time without any movement on this, but the solution here probably falls into the category of things that could be done if all the slugs were stored in one polymorphic table, as opposed to a field in each model's table.

Adding the polymorphic-table milestone to this ... but there is no time frame for doing this, presently.

**Comment by cviebrock** [comment]
Closing this ticket, as I have no pressing need to refactor the package to use a polymorphic table.  I might in the future, but that would be a fairly large breaking change ... so don't hold your breath.

In the meantime, I think @mafftor's comment [above](#issuecomment-602739766) is a reasonable solution.
