### ISSUE TITLE
Laravel config:cache leads to exception when there is closure in the config

### ISSUE THREAD

**Issue by tsunamilx** [cviebrock/eloquent-sluggable#380]
In the config sluggable.php, it allows to use closure as a method to generate slug, the problem is that laravel treat this as a bad design, and throws exception after making config:cache.

More on https://github.com/laravel/framework/issues/9625

So I guess it is possible to change the slug method to a literal string presenting a method or a class to be called when needed?

**Comment by cviebrock** [comment]
I agree: if you want to cache your configuration, then don't use a closure.

However, as described in the [documentation](https://github.com/cviebrock/eloquent-sluggable#method), you can already use a callable to define the class/method or function to call, or you can [customize the slug engine](https://github.com/cviebrock/eloquent-sluggable#customizeslugengine) itself.
