### ISSUE TITLE
slug field is empty, if source not in english !

### ISSUE THREAD

**Issue by eliyas5044** [cviebrock/eloquent-sluggable#381]
Thanks guys for your great package :) 
if i use slug source as `english`, slug create nicely. But if i use another language, slug field is empty.
my slug source, `english` or `bangla` or `both` in same source.
if i edit `method` like this
```
'method' => function( $string ) {
      return $string;
}
```
slug generate with `bangla` language, but don't have `separator`, white space between all words. 
So please guys help me how to create slug for different language.

**Comment by cviebrock** [comment]
You will need to [configure the underlying cocur/slugify engine](https://github.com/cviebrock/eloquent-sluggable#customizeslugengine) to tell it what language you are using.  Adding something like this to your models should work:

```php
/**
 * @param \Cocur\Slugify\Slugify $engine
 * @param string $attribute
 * @return \Cocur\Slugify\Slugify
 */
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    $engine->activateRuleset('bangla');

    return $engine;
}
```

Unfortunately, it doesn't look like Slugify has a Bangla ruleset though.  Take a look at the [contributions](https://github.com/cocur/slugify#contributing) section of their repository.  I'm sure they would appreciate adding a new language to their package!

In the meantime, you could replace the `activateRuleset` call above with a series of `addRule` calls.  Something like:

```php
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    $engine-> addRule('ক', 'ka');
    $engine-> addRule('খ, 'kha');
    $engine-> addRule('গ', 'ga');
    // ...etc.

    return $engine;
}
```

(I don't speak or write Bangla or Bengali, so apologies if I am confusing two distinct languages.  Those examples were taken from https://www.loc.gov/catdir/cpso/romanization/bengali.pdf, which might be of help if you are creating a ruleset for Slugify.)

**Comment by eliyas5044** [comment]
@cviebrock thanks bro for your great reply :)
I temporarily fixed my issue by adding this method in `config` file
`'method' => function ($string, $sep) {
        return preg_replace('/[?]|\p{P}|\s+/u', $sep, trim($string));
    },`
It create both `english` and `bangla` slug, but in english, i couldn't convert slug into `lowercase`

**Comment by cviebrock** [comment]
Can you run that whole result through `mb_strtolower()`?

**Comment by eliyas5044** [comment]
@cviebrock sorry for late reply. It's working :)
Now method like this - 
`'method' => function ($string, $sep) {
        return mb_strtolower(preg_replace('/[?]|\p{P}|\s+/u', $sep, trim($string)));
    },`
It create both `english` and `bangla` and also all lowercase in english.
Thanks for your great package.

**Comment by cviebrock** [comment]
Awesome!  But also feel free to make a PR to Slugify so that they have more language support!

**Comment by eliyas5044** [comment]
@cviebrock sorry for commenting on the closed issues. I have been using this approach in a while to make slug in both English and Bangla. But problem is, as I had to modify `config` file, I can't use `php artisan config:cache` due to the closure method in the configuration file.
Do you have any better idea, how to solve this problem?

Appreciate your help :)
