### ISSUE TITLE
Support Laravel 5.5

### ISSUE THREAD

**Issue by tabuna** [cviebrock/eloquent-sluggable#382]
Kind time of the day, tell me when you plan to support laravel 5.5?

**Comment by Lelectrolux** [comment]
Not cviebrock, but it should work out of the box. The version constraint is compatible, and I can't think of any features in this package that would break.

**Comment by cviebrock** [comment]
FWIW, I'm going through my packages to make sure they work with 5.5.  Expect a new version tagged shortly, although @Lelectrolux is right in that the current latest should be fine.

**Comment by tabuna** [comment]
I updated my project and did not encounter any problems

**Comment by royduin** [comment]
Same here, but maybe update the readme?

**Comment by tabuna** [comment]
No, I do not have the same behavior

**laravel 5.4:**
```php
$slug = SlugService::createSlug(Post::class, 'slug', 'Simple text')
// return simple-text
```
**laravel 5.5:**
```php
$slug = SlugService::createSlug(Post::class, 'slug', 'Simple text')
// return -1 (Negative recording increment)
```


You can help me?

**Comment by cviebrock** [comment]
Can you try the `dev-master` branch right now?  I've upgraded stuff for 5.5.

**Comment by vknyvz** [comment]
yea seems to work ok in 5.5

**Comment by royduin** [comment]
When is the new release coming for Laravel 5.5 @cviebrock?

**Comment by cviebrock** [comment]
It's out now! Version 4.3 of the package is Laravel 5.5 ready.

**Comment by royduin** [comment]
Awesome 💪 thanks!
