### ISSUE TITLE
Unique slugs per parent model

### ISSUE THREAD

**Issue by marcreichel** [cviebrock/eloquent-sluggable#383]
Thank you for this great package!

I have quite a small issue I think.
I want to generate slugs to be unique per parent model. So I have a model "Posts" for example. These Posts belong to a parent model "Site" (referenced by a "site_id"-column in the posts-table).
Now I want to be able to create a post called "My awesome Post" for site 1 which should generate a slug like "my-awesome-post". Nothing special for now.
Next I want to create another post called "My awesome Post" but for site 2 which should also generate the slug "my-awesome-post" because the slug is unique for the parent model "site".

I can't figure out what I have to do to get this result.
I hope it's clear what I want to achieve and someone can help me 😊

**Comment by marcreichel** [comment]
Found the solution myself 🙈

**Comment by pierrocknroll** [comment]
Hi @marcreichel 
What's this solution please ? :)

**Comment by marcreichel** [comment]
@pierrocknroll filter the "parent" accordingly to https://github.com/cviebrock/eloquent-sluggable#scopewithuniqueslugconstraints
