### ISSUE TITLE
Installation issue 5.4

### ISSUE THREAD

**Issue by sicsol** [cviebrock/eloquent-sluggable#384]
When i tried to install this package i'm getting the following information

```
Problem 1
    - Installation request for cviebrock/eloquent-sluggable ^4.3 -> satisfiable by cviebrock/eloquent-sluggable[4.3.0].
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - cviebrock/eloquent-sluggable 4.3.0 requires illuminate/database ~5.5.0 -> satisfiable by illuminate/database[v5.5.0, v5.5.2].
    - don't install illuminate/database v5.5.0|don't install laravel/framework v5.4.36
    - don't install illuminate/database v5.5.2|don't install laravel/framework v5.4.36
    - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].
```

**Comment by cviebrock** [comment]
If you are using Laravel 5.4, then install the 4.2 version of this pacakge:

```sh
composer require cviebrock/eloquent-sluggable:^4.2
```

**Comment by extremealex** [comment]
I am using Laravel 5.2, I'm trying to install it using the following command line

composer require cviebrock/eloquent-sluggable

which does not work obviously!
any suggestions?

**Comment by cviebrock** [comment]
There definitely is a 4.2 version of the package ... several, in fact, the latest being https://packagist.org/packages/cviebrock/eloquent-sluggable#4.2.5

You could try `composer require cviebrock/eloquent-sluggable:4.2.5` or `4.2.*` and see if that works.  Otherwise, there is something else going on.

**Comment by AmrAlmagic** [comment]
@cviebrock for laravel 5.4 
composer require cviebrock/eloquent-sluggable:^4.2.*
works well with me
thanks

**Comment by lekhad** [comment]
Please. it is not working for Laravel 5.2

**Comment by cviebrock** [comment]
@lekhad https://github.com/cviebrock/eloquent-sluggable/tree/4.2#installation

**Comment by samanrezaie** [comment]
composer require cviebrock/eloquent-sluggable:^4.2.5
