### ISSUE TITLE
Relations not used when generating slug for a new record

### ISSUE THREAD

**Issue by joshuadegier** [cviebrock/eloquent-sluggable#390]
*Steps to reproduce*
- Create a model with a relationship
- Generate the slug from relation fields
- Create a new record

*Example slugabble()*:
```php
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => ['merk.merknaam','modelserie.modelserienaam','type']
            ],
        ];
    }
```

### What happens?

After creating a new record, the slug only exists of the type field. The relationfields are left empty. This occurs when the relation is freshly created, but also when the relation already exists and is just connected using the existing ID.

For instance, using the data `merk.merknaam=Fiat`, `modelserie.modelserienaam=Punto`, `type=1.8 HGT` you get the result `slug=1-8-hgt`.

### Expected outcome

Based on the example above, you'd expect `slug=fiat-punto-1-8-hgt`.

### Fix

I'm currently working out a fix for this, it seems that the relation has to be saved first before the slug can be generated.

**Comment by joshuadegier** [comment]
I've tested what happens in these 2 cases:

```
$car->brand_id = 3; // used to be 2
$car->save();
```

and

```
$car->update(['brand_id' => 2]);
```

But it has very random results of saving the correct relation or even not updating anything in general..

**Comment by cviebrock** [comment]
Sorry for the delayed response.  I think the issue (for new models at least) is that the slug is generated before the model is saved.  In that case, those relations might not be populated/hydrated.  Similarly, for existing models with newly changed relations, the new data might not be hydrated at the time of slugging.

Running something like `$car->load('brand')` before saving would likely help.

**Comment by joshuadegier** [comment]
Makes sense! Thanks for replying!
