### ISSUE TITLE
What column name should be added for the slug?

### ISSUE THREAD

**Issue by aaronpk** [cviebrock/eloquent-sluggable#391]
The docs say:

> Of course, your model and database will need a column in which to store the slug. You will need to add this manually via your own migration.

I assume the column name should be `slug` but it would be nice if the docs made that explicit. I'm happy to send a PR updating this sentence if my assumption is correct. Thanks!

**Comment by cviebrock** [comment]
It doesn't need to be named `slug`. You could name it anything you want: `url` maybe, if that's what you use slugs for.

**Comment by aaronpk** [comment]
Is that defined in the config file or something? I just wanted to point out that the readme was ambiguous on this.

**Comment by cviebrock** [comment]
You define it in the configuration method in your model, e.g.:

```php
    public function sluggable()
    {
        return [
            'url' => [
                'source' => 'title'
            ]
        ];
    }
```

The key in that array (i.e. `url`) is the slug field you will need to add to your model.

Also note that you can have more than one sluggable field in your model, so your configuration array would have more than one key, and your model would need fields for both.

**Comment by aaronpk** [comment]
So what I was trying to point out was that the example `sluggable` method is unclear. It was not clear that the `slug` string below is referring to the column name, and isn't just some hard-coded string the module needs.

```php
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
```

I would have understood quicker what to do if this first example clarified that the column name is the key of the configuration array.
