### ISSUE TITLE
No slug created for Chinese characters

### ISSUE THREAD

**Issue by TheDude70** [cviebrock/eloquent-sluggable#392]
Am making a slug of a `title` column in a database table. When the title is English the slug is created successfully, but when the title is Chinese it fails to generate a slug.

**Comment by cviebrock** [comment]
You will need to [customize your model](https://github.com/cviebrock/eloquent-sluggable#customizeslugengine) to tell the underlying slug engine that the source string is in a different language.

Unfortunately, cocur/slugify does not support Chinese currently.  I think it's rather difficult to transliterate Chinese characters into Latin characters.  There is a [pending PR for it](cocur/slugify#158) so maybe vote over there?

If it's accepted, then adding this to your model will probably do the trick:

```php
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    $engine->activateRuleSet('chinese');

    return $engine;
}
```

Until then, you would have to manually figure out how each character is meant to be translated:

```php
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    $engine->addRule("腌", "yan");
    $engine->addRule("嗄", "a");
    // etc.

    return $engine;
}
```

**Comment by xralphack** [comment]
@cviebrock this works, however I just want to use dash to replace space rather than translate
how can I achieve this in customizeSlugEngine function?

**Comment by cviebrock** [comment]
Then you probably want a different slugging method than the default.  Something like:

```php
                'method' => function ($string, $separator) {
                    return mb_strtolower(
                        preg_replace('/[?]|\p{P}|\s+/u', $separator, $string)
                    );
                }
```

**Comment by xralphack** [comment]
@cviebrock  thanks~

**Comment by sornbarang** [comment]
it will error when i cache config
`php artisan config:cache`
atal error: Uncaught ReflectionException: Class config does not exist in project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767

**Comment by cviebrock** [comment]
Yeah @sornbarang, you can't cache closures.  You should make a helper class that implements that code, then reference that in the config.  e.g.

```php
<?php

namespace App;

class MySlugHelper {
    public static function slug($string, $separator) {
        $slug = mb_strtolower(
            preg_replace('/([?]|\p{P}|\s)+/u', $separator, $string)
        );
        return trim($slug, $separator);
    }
}
```

```php
// config/sluggable.php

'method' => [ App\MySlugHelper::class, 'slug' ],
```

**Comment by hamedsrk** [comment]
@cviebrock 
i had the same problem when i want to cache the config . i just follow your solution and it works fine! but i have another problem now
i find this code for persian and arabic slugs and i put it in my function

```

namespace App;


class MySlugHelper
{
    function slug($string, $separator = '-') {
        $_transliteration = ["/ö|œ/" => "e",
            "/ü/" => "e",
            "/Ä/" => "e",
            "/Ü/" => "e",
            "/Ö/" => "e",
            "/À|Á|Â|Ã|Å|Ǻ|Ā|Ă|Ą|Ǎ/" => "",
            "/à|á|â|ã|å|ǻ|ā|ă|ą|ǎ|ª/" => "",
            "/Ç|Ć|Ĉ|Ċ|Č/" => "",
            "/ç|ć|ĉ|ċ|č/" => "",
            "/Ð|Ď|Đ/" => "",
            "/ð|ď|đ/" => "",
            "/È|É|Ê|Ë|Ē|Ĕ|Ė|Ę|Ě/" => "",
            "/è|é|ê|ë|ē|ĕ|ė|ę|ě/" => "",
            "/Ĝ|Ğ|Ġ|Ģ/" => "",
            "/ĝ|ğ|ġ|ģ/" => "",
            "/Ĥ|Ħ/" => "",
            "/ĥ|ħ/" => "",
            "/Ì|Í|Î|Ï|Ĩ|Ī| Ĭ|Ǐ|Į|İ/" => "",
            "/ì|í|î|ï|ĩ|ī|ĭ|ǐ|į|ı/" => "",
            "/Ĵ/" => "",
            "/ĵ/" => "",
            "/Ķ/" => "",
            "/ķ/" => "",
            "/Ĺ|Ļ|Ľ|Ŀ|Ł/" => "",
            "/ĺ|ļ|ľ|ŀ|ł/" => "",
            "/Ñ|Ń|Ņ|Ň/" => "",
            "/ñ|ń|ņ|ň|ŉ/" => "",
            "/Ò|Ó|Ô|Õ|Ō|Ŏ|Ǒ|Ő|Ơ|Ø|Ǿ/" => "",
            "/ò|ó|ô|õ|ō|ŏ|ǒ|ő|ơ|ø|ǿ|º/" => "",
            "/Ŕ|Ŗ|Ř/" => "",
            "/ŕ|ŗ|ř/" => "",
            "/Ś|Ŝ|Ş|Ș|Š/" => "",
            "/ś|ŝ|ş|ș|š|ſ/" => "",
            "/Ţ|Ț|Ť|Ŧ/" => "",
            "/ţ|ț|ť|ŧ/" => "",
            "/Ù|Ú|Û|Ũ|Ū|Ŭ|Ů|Ű|Ų|Ư|Ǔ|Ǖ|Ǘ|Ǚ|Ǜ/" => "",
            "/ù|ú|û|ũ|ū|ŭ|ů|ű|ų|ư|ǔ|ǖ|ǘ|ǚ|ǜ/" => "",
            "/Ý|Ÿ|Ŷ/" => "",
            "/ý|ÿ|ŷ/" => "",
            "/Ŵ/" => "",
            "/ŵ/" => "",
            "/Ź|Ż|Ž/" => "",
            "/ź|ż|ž/" => "",
            "/Æ|Ǽ/" => "E",
            "/ß/" => "s",
            "/Ĳ/" => "J",
            "/ĳ/" => "j",
            "/Œ/" => "E",
            "/ƒ/" => ""];
        $quotedReplacement = preg_quote($separator, '/');
        $merge = [
            '/[^\s\p{Zs}\p{Ll}\p{Lm}\p{Lo}\p{Lt}\p{Lu}\p{Nd}]/mu' => ' ',
            '/[\s\p{Zs}]+/mu' => $separator,
            sprintf('/^[%s]+|[%s]+$/', $quotedReplacement, $quotedReplacement) => '',
        ];
        $map = $_transliteration + $merge;
        unset($_transliteration);
        return preg_replace(array_keys($map), array_values($map), $string);
    }
}
```
and when i run the app i god this error message

> call_user_func() expects parameter 1 to be a valid callback, non-static method App\MySlugHelper::slug() should not be called statically

can you help me in this situation please ?

**Comment by hamedsrk** [comment]
> @cviebrock
> i had the same problem when i want to cache the config . i just follow your solution and it works fine! but i have another problem now
> i find this code for persian and arabic slugs and i put it in my function
> 
> ```
> 
> namespace App;
> 
> 
> class MySlugHelper
> {
>     function slug($string, $separator = '-') {
>         $_transliteration = ["/ö|œ/" => "e",
>             "/ü/" => "e",
>             "/Ä/" => "e",
>             "/Ü/" => "e",
>             "/Ö/" => "e",
>             "/À|Á|Â|Ã|Å|Ǻ|Ā|Ă|Ą|Ǎ/" => "",
>             "/à|á|â|ã|å|ǻ|ā|ă|ą|ǎ|ª/" => "",
>             "/Ç|Ć|Ĉ|Ċ|Č/" => "",
>             "/ç|ć|ĉ|ċ|č/" => "",
>             "/Ð|Ď|Đ/" => "",
>             "/ð|ď|đ/" => "",
>             "/È|É|Ê|Ë|Ē|Ĕ|Ė|Ę|Ě/" => "",
>             "/è|é|ê|ë|ē|ĕ|ė|ę|ě/" => "",
>             "/Ĝ|Ğ|Ġ|Ģ/" => "",
>             "/ĝ|ğ|ġ|ģ/" => "",
>             "/Ĥ|Ħ/" => "",
>             "/ĥ|ħ/" => "",
>             "/Ì|Í|Î|Ï|Ĩ|Ī| Ĭ|Ǐ|Į|İ/" => "",
>             "/ì|í|î|ï|ĩ|ī|ĭ|ǐ|į|ı/" => "",
>             "/Ĵ/" => "",
>             "/ĵ/" => "",
>             "/Ķ/" => "",
>             "/ķ/" => "",
>             "/Ĺ|Ļ|Ľ|Ŀ|Ł/" => "",
>             "/ĺ|ļ|ľ|ŀ|ł/" => "",
>             "/Ñ|Ń|Ņ|Ň/" => "",
>             "/ñ|ń|ņ|ň|ŉ/" => "",
>             "/Ò|Ó|Ô|Õ|Ō|Ŏ|Ǒ|Ő|Ơ|Ø|Ǿ/" => "",
>             "/ò|ó|ô|õ|ō|ŏ|ǒ|ő|ơ|ø|ǿ|º/" => "",
>             "/Ŕ|Ŗ|Ř/" => "",
>             "/ŕ|ŗ|ř/" => "",
>             "/Ś|Ŝ|Ş|Ș|Š/" => "",
>             "/ś|ŝ|ş|ș|š|ſ/" => "",
>             "/Ţ|Ț|Ť|Ŧ/" => "",
>             "/ţ|ț|ť|ŧ/" => "",
>             "/Ù|Ú|Û|Ũ|Ū|Ŭ|Ů|Ű|Ų|Ư|Ǔ|Ǖ|Ǘ|Ǚ|Ǜ/" => "",
>             "/ù|ú|û|ũ|ū|ŭ|ů|ű|ų|ư|ǔ|ǖ|ǘ|ǚ|ǜ/" => "",
>             "/Ý|Ÿ|Ŷ/" => "",
>             "/ý|ÿ|ŷ/" => "",
>             "/Ŵ/" => "",
>             "/ŵ/" => "",
>             "/Ź|Ż|Ž/" => "",
>             "/ź|ż|ž/" => "",
>             "/Æ|Ǽ/" => "E",
>             "/ß/" => "s",
>             "/Ĳ/" => "J",
>             "/ĳ/" => "j",
>             "/Œ/" => "E",
>             "/ƒ/" => ""];
>         $quotedReplacement = preg_quote($separator, '/');
>         $merge = [
>             '/[^\s\p{Zs}\p{Ll}\p{Lm}\p{Lo}\p{Lt}\p{Lu}\p{Nd}]/mu' => ' ',
>             '/[\s\p{Zs}]+/mu' => $separator,
>             sprintf('/^[%s]+|[%s]+$/', $quotedReplacement, $quotedReplacement) => '',
>         ];
>         $map = $_transliteration + $merge;
>         unset($_transliteration);
>         return preg_replace(array_keys($map), array_values($map), $string);
>     }
> }
> ```
> 
> and when i run the app i god this error message
> 
> > call_user_func() expects parameter 1 to be a valid callback, non-static method App\MySlugHelper::slug() should not be called statically
> 
> can you help me in this situation please ?

sorry that was my mistake - i had forgotten to use public static keyword !
i correct it and it work fine 
thank you so much
