### ISSUE TITLE
Nothing happened?

### ISSUE THREAD

**Issue by CaptainCannabis** [cviebrock/eloquent-sluggable#393]
I am using Laravel 5.5.* and sluggable ^4.3.

I installed via composer and changed my migration file. I did a rollback and migrated. Everythink like expected. A new column with the name "slug" was added. 

I also inserted the public function sluggable and configured it to use the slug column with source "name" (yeah it exists on the table).

However - if i add a new dataset, there is no slug. First it threw an exception claiming that "slug" has no default value. So i changed it to nullable. When i checked again there is no exception but a NULL in the "slug" column.

What am I missing here?

My model:

```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Baum extends Model
{	
	use Sluggable;

    protected $table = 'baum';
    public $timestamps = false;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
}
```

My migration file (guess i can remove the "nullable"):

```
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Baum extends Migration
{
    public function up()
    {
        Schema::create('baum', function(Blueprint $table) {
            $table->increments('id');
            $table->string('name', 255);
            $table->string('slug', 255)->nullable();
        });
    }
    public function down()
    {
        Schema::drop('baum');
    }
}
```

Saving is done in controller like this:

```
$bid = $Baum->insertGetId(
    ['name' => $PostData['name']]
);
```

**Comment by CaptainCannabis** [comment]
It works when i use the save method instead of insertGetId. Why is that?

```
$Baum = new App\Baum([
	'name' => $PostData['name']
]);
$Baum->save();
```

**Comment by cviebrock** [comment]
I'm not sure ... but I suspect that `insertGetId` doesn't fire the `eloquent.saving` method, maybe?

**Comment by cviebrock** [comment]
Yeah, it `insertGetId` is a Builder method, not an Eloquent method, so it doesn't fire any of the Eloquent methods (which is what we hook into in order to build slugs).

You will need to use the slightly more verbose `save()` method you posted above in order for it to work.
