### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::findSimilarSlugs()  

### ISSUE THREAD

**Issue by lucaydaniel** [cviebrock/eloquent-sluggable#395]
Hey there!

I am having an issue while using this library inside a factory. Basically I am trying to use the `createSlug `service method but it's returning an error of:

`Call to undefined method Illuminate\Database\Query\Builder::findSimilarSlugs()  `

Should I include anything else? In the documentation I don't see other things getting included :)

My code is the following:

```php
use Faker\Generator as Faker;
use \Cviebrock\EloquentSluggable\Services\SlugService;
use App\Category;

$factory->define(App\Category::class, function (Faker $faker) {

    return [
        'name' => $faker->name,
        'cover' => $faker->image($dir = '/tmp'),
        'slug' => SlugService::createSlug(Category::class, 'slug', $faker->name)
    ];

});
```
Thanks guys for the assistance!

**Comment by cviebrock** [comment]
Does `App\Category` use the Sluggable trait?

(You probably also want to do `$name = $faker->name` outside of the return array.  Otherwise I think you will get a slug that doesn't match the name ... if that matters to you.)

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.

**Comment by aaxc** [comment]
Just to add, I had the same issue and `Use Sluggable;` healped me here.
But just to let you know, it's not in the documentation.

Other than that - thank you, nice library.
