### ISSUE TITLE
Laravel 5.5. resluggify alternative

### ISSUE THREAD

**Issue by Norgul** [cviebrock/eloquent-sluggable#397]
I had an old version of the package which was able to use `resluggify()` method which is no longer present. 

Is there some alternative to this?

The reason I'm asking is because before I had a model which would make slug out of the model ID and title, and now the ID get's omitted from the slug because the model isn't created yet in the time when the slug is being assigned.

The problem was circumvented before by doing a `resluggify()` but now I can't do that anymore. 

Is there a way to attach model ID to slug with the new version?

**Comment by cviebrock** [comment]
Because you can now have multiple slug fields in your model, it was difficult to decide a good behaviour for `resluggify()`.  To reslug your model, simply set the slug field to `null` and re-save:

```php
$model->slug = null;
$model->save();
```
