### ISSUE TITLE
How to establish hasMany() relationship on slug.

### ISSUE THREAD

**Issue by nripendrasingh94** [cviebrock/eloquent-sluggable#401]
Hello Guys,
I had created slugs for my Table: categories, subcategories, and product. Obviously **categories** has many subcategories and products, **subcategories** has many products and each product belongs to categories and subcategories, I established a relationship on behalf of its foreign key primary kye respectively, category_id and subcategory_id.
**My Problem:** But I want to establish a relationship on behalf of slugs.
Thanx in advance

**Comment by cviebrock** [comment]
I'm not sure I fully understand the question.  But I would also ask _why_ you want to establish relationships using the slugs if you already have the relationships defined via primary keys?

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
