### ISSUE TITLE
FatalErrorException Class 'Cviebrock\EloquentSluggable\SluggableServiceProvider' not found

### ISSUE THREAD

**Issue by jhqm67** [cviebrock/eloquent-sluggable#406]
For some reason when trying to migrate my Laravel 5.3 project to Laravel 5.4 I missed this error, and I noticed that SluggableServiceProvider does not exist anymore.
How can this problem be solved?
Thank you!!

**Comment by cviebrock** [comment]
The service provider is now `Cviebrock\EloquentSluggable\ServiceProvider`.
