### ISSUE TITLE
convert apostrophe to nothing

### ISSUE THREAD

**Issue by dingman** [cviebrock/eloquent-sluggable#412]
Hi! Thanks for a killer package, I really appreciate it.

I'm running into a case where apostrophe's are turning into a dash instead of null.

So,

```Project Mc2 Experiments with Adrienne's Lemon Soap```

is converting to

```project-mc2-experiments-adrienne-s-lemon-soap```

whereas I would like it to convert to 

```project-mc2-experiments-adriennes-lemon-soap```

Is this possible to do?

**Comment by cviebrock** [comment]
Yup! Add this to your model:

```php
public function customizeSlugEngine(Slugify $engine, $attribute) {
    $engine->addRule('\'', '');
    return $engine;
}
```


- Colin

**Comment by cviebrock** [comment]
Yup! Add this to your model:

```php
public function customizeSlugEngine(Slugify $engine, $attribute) {
    $engine->addRule('\'', '');
    return $engine;
}
```
