### ISSUE TITLE
can i use sluggable with eloquent and slim 3???

### ISSUE THREAD

**Issue by shevetonline** [cviebrock/eloquent-sluggable#413]
can i use sluggable with eloquent and slim 3???
what needs to be changed to do it?

**Comment by cviebrock** [comment]
I've never used Slim, so I don't know.  I suspect you'd just need to make sure the Service Provide is registered so that the right Eloquent events are listened for.

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
