### ISSUE TITLE
Product's category title in slug

### ISSUE THREAD

**Issue by SabaTD** [cviebrock/eloquent-sluggable#414]
Hi, I installed your package and it works great, thanks for it :)  now about my issue i need to use products's category title in slug like this,    .../parentCatTitle/productName.  

Is this possible any way ?

**Comment by cviebrock** [comment]
I think you’d have an easier time slugging your Category and Product separately, and then making a “getURL” method on your Product that generated the correct string.

**Comment by SabaTD** [comment]
Yes you are right i used separate slugging for category and products, for links on products i used this : 
`{{ url('/product/'. $prodCategoryDetails->slug . '/' . $productDetails->slug) }}`

 In Controller i select products and categories from DB by `Model:: findBySlugOrFail($slug)`.
 I am afraid that it may got errors at some moments, this time it works perfectly but selecting by string `varchar `don't seems to be great.  

What do you think about it?

**Comment by cviebrock** [comment]
I think you'll be fine selecting by `varchar`, esp. if you have an index on that field.
