### ISSUE TITLE
Why provider can't be deferred?

### ISSUE THREAD

**Issue by CDNRocket** [cviebrock/eloquent-sluggable#415]
I'm pretty new to Laravel, so sorry for my newbie question...but I wonder why this provider can't be deferred?
It provides IoC bindings and the docs say:

> If your provider is only registering bindings in the service container, you may choose to defer its registration until one of the registered bindings is actually needed. Deferring the loading of such a provider will improve the performance of your application, since it is not loaded from the filesystem on every request.

Without this, the package will be "loaded" on every request? and then will make the entire application heavier? 
Thanks.

**Comment by cviebrock** [comment]
You can try setting it to be non-deferred, and see if everything still works.

Offhand, I don't know why I coded it like that, but it may have been a leftover from the original Laravel 3 bundle I wrote to do something similar.

In any case, if you feel it still works when deferred, and want to submit a MR (with tests), I'd happily review and add it!

**Comment by CDNRocket** [comment]
Seems that this can't be done, because the provider merges config file.
