### ISSUE TITLE
Creating unique slug on multiple table

### ISSUE THREAD

**Issue by mdasiff** [cviebrock/eloquent-sluggable#417]
Suppose I have 2 table **Products** and **Posts** both table have 'slug' column, I want to create unique slug by matching both table.

**Comment by cviebrock** [comment]
You'd have to add a [scopeWithUniqueSlugConstraints](https://github.com/cviebrock/eloquent-sluggable#scopewithuniqueslugconstraints) method to both models, and have it so that each queries the other's table to check for uniqueness.

**Comment by d4rkr3pt0r** [comment]
@cviebrock Can you give me a clue? I have the same problem but I couldn't find a solution. I have `Post` and `Category` tables and I want my slugs to be unique in `both tables`.
