### ISSUE TITLE
Converting cyrillic characters to latin. 

### ISSUE THREAD

**Issue by rafailml** [cviebrock/eloquent-sluggable#418]
Hi there,
First I want to thank you for great package. 

And I have a question. Now if I have cyrillic text, the package converts cyrillic letters to latin. Is there a way to use cyrillic letters as a result slug? I mean cyrillic words with cyrillic letters. I don't need that conversion.

Thanks!

**Comment by cviebrock** [comment]
You will need to change the method used to convert the source string to a slug, since cocur/slugify does the conversion to latin characters by default.

Something like this in your configuration should work:

```
'method' => ['Illuminate\\Support\\Str', 'slug']
```
