### ISSUE TITLE
Argument #2 is not an array

### ISSUE THREAD

**Issue by Globegitter** [cviebrock/eloquent-sluggable#42]
I am just trying to set up your plugin using Laravel 4.0.x and my user mode looks like this:
![capture decran 2014-07-04 a 16 26 14](https://cloud.githubusercontent.com/assets/2580254/3483465/9006b4a0-038f-11e4-9031-e5e8d4258aed.png)

But for some reason when I try to create and save my user I am getting this error:
![capture decran 2014-07-04 a 16 24 50](https://cloud.githubusercontent.com/assets/2580254/3483457/6f637404-038f-11e4-8a43-736731c584ba.png)

My users table does have the `slug` column as mentioned in the readme.
Any idea what the issue could be?

Edit: Started to investigate a bit more and if I set `$this->sluggable` hardcoded I am getting this error: `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sluggable' in 'field list' (SQL: insert into users....`
Should this have been added automatically? Can't find anything in the readme about that.

**Comment by geding** [comment]
I have this same problem it's because of not setting $sluggable array correctly
should be like this:
```php
 protected $sluggable = array(
        'build_from' => 'title',
        'save_to'    => 'slug',
    );
```

**Comment by DrudgeRajen** [comment]
Yes, i was also having same problem. I also resovle in the same way :D
