### ISSUE TITLE
Post Slug does not show

### ISSUE THREAD

**Issue by Sidney-Dev** [cviebrock/eloquent-sluggable#420]
I was showing my posts using the post_id, the I followed the current docummentation to show my posts using the slug. When I create the post I see the slug is added on the database as well.
When I click on my link to view the post, it takes me to the post using the slug. However I nothing shows but this error that I had never seen before:

Property [title] does not exist on this collection instance. (View: C:\xampp\htdocs\blog\resources\views\post.blade.php)

This is my post model:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
class Post extends Model
{
    use Sluggable;
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
    protected $fillable = ['title', 'content', 'user_id','category_id','photo_id'];

    public function category(){
    	return $this->belongsTo('App\Category');
    }

    public function user(){
    	return $this->belongsTo('App\User');
    }

    public function photo(){
    	return $this->belongsTo('App\Photo');
    }

    public function comments(){
        return $this->hasMany('App\Comment');
    }
}
```

My route: 

```
Route::get('/post/{slug}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']);
```

The post function from the AdminPostsController looks like this:

```
public function post($slug){
        $post = Post::whereSlug($slug)->get();

       // $posts = Post::all();
        $categories = Category::all();
        return view('post', compact('post','categories'));
 }
```

In the view I have this:

```
<h1>{{$post->title}}</h1>
```

Thanks in advance.

**Comment by cviebrock** [comment]
In your controller method, you probably want `first()` instead of `get()` in order to get only one post and not a collection:

```
$post = Post::whereSlug($slug)->first();
```

Alternatively, you can use [route model binding](https://github.com/cviebrock/eloquent-sluggable/blob/master/ROUTE-MODEL-BINDING.md) to make things very clean.

In your model:

```php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Post extends Model
{
    use Sluggable;

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    // ... reset of code as before
```

Your route becomes:

```php
Route::get('/post/{post}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']);
```

And then in your controller, the post model is automatically loaded for you:

```php
public function post(App\Post $post){
        $categories = Category::all();
        return view('post', compact('post','categories'));
 }
```

**Comment by Sidney-Dev** [comment]
It does work. Was completely forgotten that the get() takes an array.

Appreciate the assistance
