### ISSUE TITLE
Slugs for a multi-user website

### ISSUE THREAD

**Issue by valante** [cviebrock/eloquent-sluggable#421]
Consider a website where every user can create posts of his own (under his own subdomain, for example). It makes sense to limit the slug uniqueness to posts of that given user.

I suggest adding to the config a parameter for "unique_within", which will take an array with the following indexes:

- column_name
- model property for value

The query for similar slugs will then limit the search to model records where the column_name equals the model's instance's defined property.

It's a minor modification, but one that I desperately need. Could you please include it?

**Comment by cviebrock** [comment]
Good news: you can already do this with the [scopeWithUniqueSlugConstraints](https://github.com/cviebrock/eloquent-sluggable#scopewithuniqueslugconstraints)!

In fact, the test file [here](https://github.com/cviebrock/eloquent-sluggable/blob/master/tests/Models/PostWithUniqueSlugConstraints.php) does exactly what you want.

**Comment by valante** [comment]
You are brilliant. Thanks so much!
