### ISSUE TITLE
Manage slugs in translations tables?

### ISSUE THREAD

**Issue by anardil** [cviebrock/eloquent-sluggable#422]
Hello,

To explain better my problem.
I have to 2 tables : pages and page_translations

In my table page_translations, I have 3 fields : title, slug and locale
In this table, I want the slug be unique with the title and depends also the locale value.

Example:
'test','test','fr'
'test','test','en' => I want that slug be the same because it's not the same locale

But if I insert a new row with same locale
'test','test-1','fr' => the slug will be different

Is it possible to do that?

Thanks.

**Comment by BTeodorWork** [comment]
Add this to the translation model

```
 /**
     * Query scope for finding "similar" slugs, used to determine uniqueness.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $attribute
     * @param array $config
     * @param string $slug
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeFindSimilarSlugs( Builder $query, string $attribute, array $config, string $slug ): Builder {
        $separator = $config['separator'];
        $locale    = $this->locale;

        return $query->where( function ( Builder $q ) use ( $attribute, $slug, $separator, $locale ) {
            $q->where( $attribute, '=', $slug )
              ->where( 'locale', '=', $locale )
              ->orWhere( $attribute, 'LIKE', $slug . $separator . '%' );
        } );
    }
```

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.

**Comment by jcerdan** [comment]
Hi, 
I've just met the same problem and the function does not solve all cases, as it works for the first record with same slug in several locales, but creates xxx-2, xxx-3, xxx-4, etc... for the second record added with identical slug and so on, on next records saved.
The function should be like this:

`/**
     * Query scope for finding "similar" slugs, used to determine uniqueness.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $attribute
     * @param array $config
     * @param string $slug
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeFindSimilarSlugs( Builder $query, string $attribute, array $config, string $slug ): Builder {
        $separator = $config['separator'];
        $locale    = $this->locale;

        return $query->where( function ( Builder $q ) use ( $attribute, $slug, $separator, $locale ) {
            $q->where( 'locale', '=', $locale )
              ->where(function ($query) use ($attribute, $slug, $separator) {
                    $query->where($attribute, '=', $slug)
                          ->orWhere($attribute, 'LIKE', $slug . $separator . '%');
                });
        });
    }`

Just this comment in case someone needs this also. 
By the way, thanks @cviebrock for this very good package and @teodoriu for first function version ;-)
