### ISSUE TITLE
Performance issue when dealing with a large number of records with identical titles

### ISSUE THREAD

**Issue by weotch** [cviebrock/eloquent-sluggable#423]
Hi! On a project using this package we import data from a source that generates MANY records with identical titles.  As a result with [`getExistingSlugs`](https://github.com/cviebrock/eloquent-sluggable/blob/master/src/Services/SlugService.php#L349) queries the database, it creates a LARGE object with it's `get()` call.  

Would you be open to a PR the work that `makeSlugUnique` into a database query?  I'm imagining a query that orders all of the matches from `findSimilarSlugs` by their slug, so the first item in the list has the highest suffix value.  Then we would only need to return that one, highest suffixed row.

**Comment by cviebrock** [comment]
Sounds great!

**Comment by weotch** [comment]
Cool, I'll close this for now.  If the project requirements go this way, I'll work on it.  Thanks!
