### ISSUE TITLE
Problem install laravel v.5.6

### ISSUE THREAD

**Issue by nkEmperor** [cviebrock/eloquent-sluggable#424]
composer require cviebrock/eloquent-sluggable:^4.5

  Problem 1
    - Installation request for cviebrock/eloquent-sluggable 4.5 -> satisfiable by cviebrock/eloquent-sluggable[4.5.0].
    - Conclusion: remove laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.45
    - cviebrock/eloquent-sluggable 4.5.0 requires illuminate/support ~5.6.0 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/support v5.6.0|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.1|don't install laravel/framework v5.2.45
    - illuminate/support v5.6.10 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.11 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.12 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.13 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.14 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.15 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.16 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.17 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.19 conflicts with laravel/framework[v5.2.45].
    - don't install illuminate/support v5.6.2|don't install laravel/framework v5.2.45
    - illuminate/support v5.6.20 conflicts with laravel/framework[v5.2.45].
    - don't install illuminate/support v5.6.3|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.4|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.5|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.6|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.7|don't install laravel/framework v5.2.45
    - illuminate/support v5.6.8 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.9 conflicts with laravel/framework[v5.2.45].
    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].

**Comment by cviebrock** [comment]
Looks to me like you’ve got Laravel 5.2, not 5.6.

**Comment by bloggervista** [comment]
Yes the package is working. Before posting such issue I guess its wise to check error message.

Can you uninstall laravel and reinstall new one ?
