### ISSUE TITLE
Problem with Persian and Arabic languages

### ISSUE THREAD

**Issue by ali-mhz** [cviebrock/eloquent-sluggable#427]
Hi
I'm using laravel 5.4 and eloquent-sluggable 4.2.5 in one of my apps which is in 2 languages: English and Persian.

This works perfect with English but for Persian it generates strange slugs.
For example if i have "تست" then result is "**tst**" but i expect to get "تست" or
if i have this "این یک تست است" (it means 'this is a test') the result is "**n-tst-st**" but i expect to have this 
"این-یک-تست-است"

**Comment by cviebrock** [comment]
By default, the slugging engine we use does a "transliteration" of the slug into ASCII characters.  The assumption was that people would use this library to generate URLs (which _can_ use UTF characters, but _tend_ to be ASCII-only).

If you want to keep your slugs in Persian, you could probably do something like @DJafari suggested, or just use the following in your config:

```
'method' => function ($string, $separator) {
    $slug = mb_strtolower(
        preg_replace('/([?]|\p{P}|\s)+/u', $separator, $string)
    );
    return trim($slug, $separator);
}
```

**Comment by ali-mhz** [comment]
@cviebrock This works but i cannot **cache** my config file. Any solution?

**Comment by cviebrock** [comment]
You can't cache configs that use closures, correct.

Putting that logic into a helper function or class/method, and then referencing that in the config should work.  See the second example [here](https://github.com/cviebrock/eloquent-sluggable#method).

**Comment by ali-mhz** [comment]
@cviebrock Thank you so much, i searched a lot for this, don't know how i didn't notice it.
