### ISSUE TITLE
Create Slug if

### ISSUE THREAD

**Issue by xron89** [cviebrock/eloquent-sluggable#428]
Is it possible for the model to update and create a slug if another column is true? Could this be done in the configuration file?

As an example; 

`    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
                'where' => 'is_custom' == 1
            ]
        ];
    }`

The reason for this is because I want some pages slug to fixed and never change even if they update the page name.

**Comment by cviebrock** [comment]
I think the easiest way to handle this would be through [Events](https://github.com/cviebrock/eloquent-sluggable#events).  The first example there is pretty much what you want, I think.

Re-open this ticket if you need more help.
