### ISSUE TITLE
does it work where slugs are an editable field with unique?

### ISSUE THREAD

**Issue by jayenne** [cviebrock/eloquent-sluggable#431]
I have it working nicly with 'uniwue' where there is no editable field for slugs, but when i have a user editable field and the user enters a duplicate slug it bails with an sql duplocate entry error. I would have assumed it would (and need it to) create a unique slug from that given in the entry field (fall back to title).

if it ca ndo this, would you have an example usage?
thanks.

**Comment by cviebrock** [comment]
I'm not sure what you mean.  I've tried adding this code to the test suite, and it works as expected:

```php
    public function testIssue431() {
        $post1 = Post::create([
            'title' => 'A post title'
        ]);
        $this->assertEquals('a-post-title', $post1->slug);

        $post2 = new Post;
        $post2->title = 'A post title';
        $post2->save();
        $this->assertEquals('a-post-title-1', $post2->slug);
    }
```

Can you post a test that fails?

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.

**Comment by unlike777** [comment]
Same problem
Сlarify the previous speaker

unique doens't work with already created models
