### ISSUE TITLE
You can also define method as a closure (again, expecting two parameters): not working

### ISSUE THREAD

**Issue by sornbarang** [cviebrock/eloquent-sluggable#433]
`php artisan config:cache`
Fatal error: Uncaught ReflectionException: Class config does not exist in laravel-project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767

**Comment by cviebrock** [comment]
See my comment in #392.  Are you saying that doesn't work?  I just added a test for that syntax, and it seems fine to me.

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
