### ISSUE TITLE
Unique slug by souce title between two tables

### ISSUE THREAD

**Issue by fmcdigital** [cviebrock/eloquent-sluggable#434]
I have a model called SubPage and a model called Page.

Both have `title` and `slug`, how can I generate a unique `slug` on my SubPage Model by check if Page slug already exists?

**Comment by fmcdigital** [comment]
In my controller I solved the problem by using:

`$subPage->slug = SlugService::createSlug($p, 'slug', $subPage->slug);`

**Comment by cviebrock** [comment]
You wanted the SubPage slug to be unique within it's Page parent "scope"?

If so, then [scopeWithUniqueSlugConstraints](https://github.com/cviebrock/eloquent-sluggable#scopewithuniqueslugconstraints) is what you want to add to your SubPage model, and there is even an example in the tests you can probably copy: https://github.com/cviebrock/eloquent-sluggable/blob/master/tests/Models/PostWithUniqueSlugConstraints.php
