### ISSUE TITLE
Access slug value in model.

### ISSUE THREAD

**Issue by marcelotk15** [cviebrock/eloquent-sluggable#442]
I cant use `$this->slug` in my model file, returning empty.

```php
<?php

namespace App\Models;

use App\Traits\SetsSlugRouteKeyName;
use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Club extends Model
{
    use Sluggable;
    use SluggableScopeHelpers;
    use SoftDeletes;
    use SetsSlugRouteKeyName;

    protected $fillable = [
        'name',
        'acronym',
        'slug'
    ];

    protected $dates = ['deleted_at'];

    protected $appends = ['resource_url'];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    /**
     * @return \Illuminate\Contracts\Routing\UrlGenerator|string
     */
    public function getResourceUrlAttribute()
    {
        return url('admin/clubs/' . $this->slug);
    }
}
```

**Comment by cviebrock** [comment]
`SluggableScopeHelpers` gives you `$this->getSlugKey()`, but using `$this->slug` should be fine as well.

What's the contents of `App\Traits\SetsSlugRouteKeyName`?

**Comment by marcelotk15** [comment]
With `getSlugKey()` 

> Return value of App\Models\Club::getSlugKey() must be of the type string, null returned (View: /home/vagrant/Code/ProClubs/resources/views/admin/club/index.blade.php)

```php
<?php

namespace App\Traits;

trait SetsSlugRouteKeyName {
    public function getRouteKeyName()
    {
        return 'slug';
    }
}
```

**Comment by cviebrock** [comment]
Are your models being slugged when saved?

If `getSlugkey()` is returning `null`, then I'm thinking you have some configuration issue (since looking at `SluggableScopeHelpers` that should either return the first key of the configuration array, or the first value if you are using short configs (which you aren't).

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.

**Comment by mikey-gray** [comment]
I know this is a super old issue, but I was having a similar problem with Laravel/Sluggable 10 and specifically using the slug attribute in `$appends`. It threw an error like "`getSlugAttribute` is not defined".

**Comment by cviebrock** [comment]
`slug` should be a "regular" attribute on your model (i.e. there is a database column for it) ... so I'm not sure why you would need to add it to the Eloquent `$appends` property of the model.  It would be included in serialization by default ... no?

**Comment by mikey-gray** [comment]
> `slug` should be a "regular" attribute on your model (i.e. there is a database column for it) ... so I'm not sure why you would need to add it to the Eloquent `$appends` property of the model. It would be included in serialization by default ... no?

🤦 Sorry. Duh. I was refactoring an old solution to use your (excellent) library and got tripped up on it without thinking it through.

**Comment by cviebrock** [comment]
@mikey-gray All good!
