### ISSUE TITLE
use $model->slug or $model->id interchangably? 

### ISSUE THREAD

**Issue by jayenne** [cviebrock/eloquent-sluggable#443]
not a bug, but a help request.
 
I'd like to use $model->id and $model->slug interchangably. is there a way where i can pass either and still get the model i need? ...or do i need to migrate my whole app (currently using $model->id) to use only $model->slug ?

**Comment by cviebrock** [comment]
When you say "use $model->id", what do you mean?  The `id` and `slug` attributes are going to represent two different columns in your database, so they aren't really interchangeable in that regard.

You can use `Model::findBySlug()` and `Model::find()` to do a search for a model.

If you are using route-model binding, and want to be able to do http://example.com/posts/123 and http://example.com/posts/my-post-slug interchangeably, you can do what I did in a recent project and use the `SluggableScopeHelpers` trait in your model, and add something like this to the boot method of your `\App\Providers\RouteServiceProvider`:

```php
    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        Route::bind('post', function ($value) {
            if (is_numeric($value)) {
                return Post::findOrFail($value);
            }
            return Post::findBySlugOrFail($value);
        });
    }
```

**Comment by jayenne** [comment]
excellent. thanks.
I was binding and had doing something similar in my RouteServiceProvider ...
unforutnatly, can't handle and "empty" or "/" slug for my homepage.
