### ISSUE TITLE
No slugging for homepage

### ISSUE THREAD

**Issue by bally86** [cviebrock/eloquent-sluggable#444]
Is there a way to skip slugging for a specific record. My homepage url needs to stay empty instead of "homepage".

**Comment by cviebrock** [comment]
You could write a custom method class/function that generates the slugs, and have the check handled there.

Or, maybe better would be to use the (events)[https://github.com/cviebrock/eloquent-sluggable#events] the package triggers, and put the logic there.  The first example in the documentation linked above is almost exactly what you want.

_Caveat: the event stuff isn't super well tested, so give it a try._
