### ISSUE TITLE
Slug update

### ISSUE THREAD

**Issue by sajaddp** [cviebrock/eloquent-sluggable#445]
Hello,
Currently, I have a post table with many records. I recently added eloquent-sluggable to my project.
The question is that is there a way to update the slugs for all my records?
Since `$this->slug`  in my model returns `null`.

**Comment by bradley-varol** [comment]
Would the following not suffice?

`foreach ($posts as $post) {
    $post->save();
}`

**Comment by sajaddp** [comment]
Dear @bradley-varol,
Thanks, it's worked.
