### ISSUE TITLE
how can set to support persian language?

### ISSUE THREAD

**Issue by rezaatashpeykar** [cviebrock/eloquent-sluggable#447]
Please be sure you include all the relevant information in your issue so we can help you:

- [ ] steps taken to reproduce your issue
- [ ] your configuration file(s), where relevant
- [ ] a copy of your Models that use or extend this package (just the relevant parts!)
- [ ] any other code we might need to help

Please use a descriptive title for your issue.  "Why doesn't this work?" doesn't provide 
other users much information if they are scanning the list of issues.

Also, *please* use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
when pasting more than one line of code.  It makes it so much more readable for everyone!

**Thank you!**

**Comment by cviebrock** [comment]
https://github.com/cviebrock/eloquent-sluggable/issues/427
