### ISSUE TITLE
Combined slug using dimsav/laravel-translatable

### ISSUE THREAD

**Issue by martin-ro** [cviebrock/eloquent-sluggable#452]
I have two models, Page and Category. Using [dimsav/laravel-translatable
](https://github.com/dimsav/laravel-translatable) I had to create separate models for translations as per documentation: PageTranslation and CategoryTranslation. 

I tried using the solution suggested [here](https://github.com/cviebrock/eloquent-sluggable/issues/405): 

```php
class CategoryTranslation {
    use Sluggable;

    public function sluggable() {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
}

class PageTranslation {
    use Sluggable;

    public function sluggable() {
        return [
            'slug' => [
                'source' => 'title'
            ],
            'combined_slug' = [
                'source' => ['category.name', 'title']
            ]
        ];
    }
}
```

But the actual relationship is on the Page and Category models:

```php
class Page extends Model
{
    /**
     * Get the post that owns the comment.
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

class Category extends Model
{
    /**
     * Get the comments for the blog post.
     */
    public function pages()
    {
        return $this->hasMany(Page::class);
    }
}
```

saving a page now only uses the `title` in `combined_slug`. 

Any advice on how to get the category name even though the relationship lives elsewhere? Or did I missed something else?

**Comment by poldixd** [comment]
Do you have any updates on this issue?

**Comment by martin-ro** [comment]
No, I ended up using https://github.com/IsraelOrtuno/permalink <https://github.com/IsraelOrtuno/permalink>,  relatively new package but works great so far. It has this package as dependency.

**Comment by inalto** [comment]
To make it work  you need to apply Sluggable to the Translation table, ex:

if you have a model Report, then you have your translated fields in ReportTranslation model and you have to apply the sluggable to the ReportTranslation model:

my ReportTranslation model:
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class ReportTranslation extends Model
{
    use HasFactory;
    use Sluggable;

    public $table = 'reports_translations';

    protected $fillable = ['title', 'slug','content','excerpt'];
    public $timestamps = false;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
    
}


In my case i use it with livewire and in my livewire component i also add this metod:

public function updatedReportTitle()
    {
        $this->report->slug = SlugService::createSlug(ReportTranslation::class, 'slug', $this->report->title);
    }

To make it update in page.
