### ISSUE TITLE
Deactivate Lowercase on Slug

### ISSUE THREAD

**Issue by Adioz01** [cviebrock/eloquent-sluggable#454]
Hi Colin,

first: thanks for the great package you created!

Here is my issue:
I would like to **deactivate** the auto lowercase functions when a slug is generated. 
To create the slugs, your package relies on [cocur/slugify](https://github.com/cocur/slugify), correct?

They have an option to deactivate the [lowercase function,](https://github.com/cocur/slugify#more-options) e.g.:

```php
$slugify = new Slugify(['lowercase' => false]);
$slugify->slugify('Hello World'); // -> "Hello-World"
```

How can i set this function in your **customizeSlugEngine** function?

```php
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    $engine->????;

    return $engine;
}
```

**Thank you!**

**Comment by cviebrock** [comment]
Hmm ... I don't think it's possible with the current set up I have with cocur/slugify.  It doesn't look like you can deactivate that function (or set any options) other than in the constructor of their class.

I should probably refactor my package to expose this somehow.  Give me a few days, and I should be able to release a new version that lets you customize this.

**Comment by codebyray** [comment]
Not sure if this has been added. But you can add a custom setSlugAttributes function to handle the slugs however you want i your model. I set mine to always be uppercase using the following:

`
public function setSlugAttribute($value)
{
    $this->attributes['slug'] = strtoupper($value);
}
`

You could use ucfirst() or ucwords() or any other php string manipulation function.

Hope this helps.

Regards,
RJ

**Comment by cviebrock** [comment]
@Adioz01 I apologize for taking almost 2 years to get around to implementing this relatively easy fix.  Version 8.0.3 of the package now allows you to do exactly what you wanted.  See https://github.com/cviebrock/eloquent-sluggable/blob/master/tests/Models/PostWithCustomEngineOptions.php#L25-L27 for an example.

**Comment by Adioz01** [comment]
@cviebrock thank you for adding the feature :-)
