### ISSUE TITLE
set numbers instead of words!

### ISSUE THREAD

**Issue by hmahdi-s** [cviebrock/eloquent-sluggable#455]
When i published project on DirectAdmin panel the package just put numbers. 
Laravel version 5.5
eloquent-sluggable 4.3

**Comment by cviebrock** [comment]
I’m not familiar with DirectAdmin, but it sounds like there might not be a `source` configured for your sluggable field.

**Comment by hmahdi-s** [comment]
I wrote this method in my model:
`    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }`
but sluggable not working well on server!

**Comment by hmahdi-s** [comment]
Is there any special extension that this package needs ?

**Comment by cviebrock** [comment]
No special extensions are required. Does your model use the Sluggable trait? Did the service provider get loaded?

**Comment by hmahdi-s** [comment]
In the model i have this method:
`   public function path()
    {
        return "/article/$this->slug";
    }`
in the provider i have this:
`        Cviebrock\EloquentSluggable\ServiceProvider::class,
`
what else should i have?

**Comment by cviebrock** [comment]
Does your model `use Sluggable` and does it have a `sluggable()` method for the configuration?

**Comment by hmahdi-s** [comment]
yes it does.
`  use Sluggable;`
` public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }`

**Comment by hmahdi-s** [comment]
how can i reinstall package to fix this problem?!
Is there any special way to remove package?

**Comment by cviebrock** [comment]
You can remove the package with `composer remove`, and then delete any references to it in your code.

(Re)Installation instructions are in the README.
