### ISSUE TITLE
laravel middleware / eloquent-sluggable problems

### ISSUE THREAD

**Issue by ja-heller** [cviebrock/eloquent-sluggable#456]
I'm facing some problems which I'm currently a bit unsure how to get them solved.
Using eloquent-sluggable for some models inside my application.
For one of these models a controller method (getProduct) exists. This method will have a middleware running before the request. The middleware itself should perform a simple task:

	-checking if the user is logged into
	-inserting a database entry to a model storing the product id and the user id (some "view" counter)

I caused these problems:

1.) I want to be able to redirect the user in case of no product was found to some page with some error message. At the moment the default 404 page is triggered, but I ONLY want this redirect happen on several controller methods (not global).

2.) Is there some way to set the routing key dynamically? As far as I understand the logic it's hard to do so, since in case of the method inside the controller is called, the "model" is already searched before.
For some other controller methods I would like to use the id of product (backend for example), where no search engine friendly slugs are required.
	
	//set inside the product model
    public function getRouteKeyName()
    {
        return 'slug';
    }

3.) Referring to the view counter middleware. Is there any way to get the model inside the middleware OR is the model only "retrieved" AFTER the request is processed by the middleware (meaning the middleware has no knowledge about the product model at this time) -> hen egg problem?

    public function handle($request, Closure $next)
    {

        //perform some logic, check if user has viewed product already...
        if(Auth::user()){

            //this doesn't work, only returns the "slug" part from the request
            dd($request->product);

        }

        return $next($request);
    }

**Comment by cviebrock** [comment]
To address your points:

1. I'm not sure how you do this.  But I'm fairly certain it's not within the scope of this package specifically.

2. Again, I don't think this is a package-specific issue.  I do something similar in a project with the following code in `app/Providers/RouteServiceProvider.php`:

```php
    public function boot()
    {
        parent::boot();

        Route::bind('project', function ($value) {
            if (is_numeric($value)) {
                return Project::where('project_id', $value)
                    ->firstOrFail();
            }
            return Project::findBySlugOrFail($value);
        });
    }
```

In case it's of interest, my model looks like this:

```php
class Project extends Model
{

    use Sluggable,
        SluggableScopeHelpers;

    public function getRouteKeyName(): string
    {
        return $this->getSlugKeyName();
    }

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source'   => 'title',
                'onUpdate' => true,
            ],
        ];
    }

    // other irrelevant code ...
}
```

3. This works for me.  My model:

```php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use Sluggable,
        SluggableScopeHelpers;

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
}
```

My middleware:

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Log;

class LogPostMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        /** @var \App\Post $post */
        $post = $request->post;
        Log::info('Found request for post', $post->attributesToArray());
        return $next($request);
    }
}
```

My routes:
```php
<?php

Route::get('/posts/{post}', function(\App\Post $post) {
    return $post;
})->middleware('test');
```

My database has the following entries:

| id | title | slug | created_at | updated_at |
|----|------------|-------|------------|------------|
| 1 | First post | first | 2019-01-03 04:34:43 | 2019-01-03 04:34:43 |
| 2 | Second post | second | 2019-01-03 04:34:43 | 2019-01-03 04:34:43 |
| 3 | Third post | third | 2019-01-03 04:34:43 | 2019-01-03 04:34:43 |

When I hit `http://127.0.0.1:8000/posts/second` I see the json structure for that post, plus this is written to the log file:

```
[2019-01-03 04:39:14] local.INFO: Found request for post {"id":2,"title":"Second post","slug":"second","created_at":"2019-01-03 04:34:43","updated_at":"2019-01-03 04:34:43"} 
```

**Comment by ja-heller** [comment]
Everything, except point 2 is working fine for me.

My 

> RouteServiceProvider

```
public function boot()
    {

        parent::boot();

        Route::bind('item', function ($value) {
            if (is_numeric($value)) {
                Log::info("here");
                return Product::where('id', $value)->firstOrFail();
            }
            Log::info("out");
            return Product::findBySlugOrFail($value);
        });

    }
```

My 

> Product

 model

```
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;

lass Product extends Model
{
    use Sluggable;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}
```

Using the slug for the route:

/item/slugname works fine, but using the ID, doesn't work (triggering a 404 page).

**Comment by ArnoHolo** [comment]
Thank you cviebrock for this answer.

I had the same issue. It was solved thanks to the boot() method in RouteServiceProvider.php.

I'm quite new to Laravel and I expected this information to be written on the "Configuration" section of the Readme of this library, not hidden in further pages.

Thank you anyway!
