### ISSUE TITLE
Cannot create slug on create

### ISSUE THREAD

**Issue by trieuducthai** [cviebrock/eloquent-sluggable#457]
Slug not created on create because function data_get() inactive as you wish
https://github.com/cviebrock/eloquent-sluggable/blob/456d6a5bb211dbca1c706db226eb5e73ef608ccc/src/Services/SlugService.php#L131
Can replace it with: $value = array_get($this->model->getAttributes(), $key);

**Comment by cviebrock** [comment]
I'm not sure this would be appropriate.  I used `data_get` because the `$key` might not be an actual element of the model's attributes (i.e. it could be a mutator).

If you can put together a PR for your change, along with a test showing how the change fixes it, I'll review.

Thanks!

**Comment by ducthai93** [comment]
It happens when you defining a accessor. Ex:

`public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

public function getNameAttribute()
    {
        // return null
    }`

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
