### ISSUE TITLE
SlugService::createSlug() isn't creating unique slugs

### ISSUE THREAD

**Issue by jordanade** [cviebrock/eloquent-sluggable#458]
I'm using SlugService::createSlug() in one part of my code because I want to override my default configuration and use a specific string "new post" for creating new models, instead of the normal source field "title" which is used elsewhere. But when I do this the string generated isn't unique with respect to existing instances of my model. I tried adding `['unique' => true]` but it didn't help. I want the slug to be incremented normally, i.e. "new-post-1", "new-post-2", etc.

Relevant section of model:
```
class Page extends Model
{
	use Sluggable, NodeTrait
	{
		NodeTrait::replicate as replicateNode;
		Sluggable::replicate as replicateSlug;
	}
	// handle trait collision between NodeTrait and Sluggable
	public function replicate(array $except = null)
	{
		$instance = $this->replicateNode($except);
		(new SlugService())->slug($instance, true);
		return $instance;
	}
	public function sluggable()
	{
		return [
			'slug' => [
				'source' => 'title',
				'maxLength' => 50,
			]
		];
	}
	protected function getScopeAttributes()
	{
		return [ 'site_id' ];
	}
	// ...
}
```

My code:
```
$page = Page::create([
	'site_id' => $this->site->id,
	'parent_id' => $this->page->id,
	'title' => 'Headline',
	'slug' => SlugService::createSlug(Page::class, 'slug', 'new post', ['unique' => true]),
]);
```

The slug created is always "new-post" even if that instance already exists. I can see that the problem is that SlugService::createSlug() isn't aware of site_id—how can I do this?

**Comment by jordanade** [comment]
I guess I can just do this, but it requires two database calls:
```
$page = Page::create([
	'site_id' => $this->site->id,
	'parent_id' => $this->page->id,
	'title' => 'New post',
]);
$page->title = 'Headline';
$page->save();
```

**Comment by cviebrock** [comment]
I'm not sure if this would work, but what about something like:

```php
<?php
public function sluggable()
{
    return [
        'slug' => [
            'source' => 'slug_title',
            'unique' => true,
        ]
    ];
}

public function getSlugTitleAttribute()
{
    return $this->exists ? $this->getAttribute('title') : 'new post';
}
```

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.

**Comment by jordanade** [comment]
In my case I don't want to mess with my model, which is more general than the thing I am working on. (And now I'm hitting this roadblock in a different part of my code). 

I just want SlugService::createSlug() to do what it says on the tin—create unique slugs.

**Comment by jordanade** [comment]
For anyone else reading this, the solution is to pass an instance instead of a class identifier:
Instead of `SlugService::createSlug(Page::class, 'slug', 'new post')`
You do `SlugService::createSlug($page, 'slug', 'new post')`

**Comment by hasnat-we** [comment]
For my case I had 'static' keyword in model event callback like following.
`static::saving(static function(Post $post) {}`
When I removed 'static' keyword then SlugService::createSlug() was able to generate and save unique slug.
Thanks
