### ISSUE TITLE
Support Laravel 5.8

### ISSUE THREAD

**Issue by ChristianKuri** [cviebrock/eloquent-sluggable#459]
Laravel 5.8 was released today, while trying to upgrade my laravel version from 5.7 to 5.8 it doesnt allow me to, since this package is conflicting with the upgrade.

**Comment by mahaverick** [comment]
Please add support to 5.8.

**Comment by sokolnikov911** [comment]
Also need 5.8 support.

**Comment by stefensuhat** [comment]
waiting for this. 🤪

**Comment by cviebrock** [comment]
Version 4.8 of the package will be released shortly with support for Laravel 5.8.  Thanks @tabuna for putting together the PR.
