### ISSUE TITLE
Disallow + (plus) character

### ISSUE THREAD

**Issue by mauxtin** [cviebrock/eloquent-sluggable#461]
Is there a way to replace a character with a different one?

I basically want to replace the + character with "plus". I am basically looking for a way (possibly in the config file) like so:
```
   'custom' => [
        '+' => 'plus'
   ]
```

**Comment by cviebrock** [comment]
In your model, you can configure the slug engine to handle this:

```php
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    $engine->addRule('+', 'plus');
}
```
