### ISSUE TITLE
The hyphen comes to unnecessary places.

### ISSUE THREAD

**Issue by bhdrnzl** [cviebrock/eloquent-sluggable#462]
Hi, there is no problem with the local host, but there is an extra hyphen on the server.

server: 
![Ekran Alıntısı](https://user-images.githubusercontent.com/14258979/54496950-2cb1ec00-4906-11e9-83b5-6542d1b453f8.JPG)
local:
bu-bir-test-blogudur

server: 
![Ekran Alıntısı2](https://user-images.githubusercontent.com/14258979/54496961-40f5e900-4906-11e9-8b1d-8eec3bdfcfb7.JPG)
local: 
antik-tarih-ve-arkeoloji

**Comment by tamert** [comment]
> Hi, there is no problem with the local host, but there is an extra hyphen on the server.
> 
> server:
> ![Ekran Alıntısı](https://user-images.githubusercontent.com/14258979/54496950-2cb1ec00-4906-11e9-83b5-6542d1b453f8.JPG)
> local:
> bu-bir-test-blogudur
> 
> server:
> ![Ekran Alıntısı2](https://user-images.githubusercontent.com/14258979/54496961-40f5e900-4906-11e9-8b1d-8eec3bdfcfb7.JPG)
> local:
> antik-tarih-ve-arkeoloji

https://www.mkoseoglu.com/laravel-5-4-eloquent-sluggable-kullanimi-seo

**Comment by bhdrnzl** [comment]
unfortunately I could not find a document for my problem here.

**Comment by cviebrock** [comment]
As per https://github.com/cviebrock/eloquent-sluggable/issues/359, are you adding this to your sluggable model?

```php
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    return $engine->activateRuleset('turkish');
}
```

If so, I'm not sure why there would be a difference between what you see on localhost and what you see on your deployment server.  I'm assuming both are running the same versions of PHP and the sluggable package, and that the cocur/slugify library is the same on both?

**Comment by jordanade** [comment]
Hi cviebrock, related question...what's the easiest way to tell sluggable to excise a character without putting the separator character in? 

For example it always bugs me when an apostrophe is turned into a separator—I want "Death's Door" to be "deaths-door", not "death-s-door".

Anyway, thanks for the code.

**Comment by cviebrock** [comment]
I think this would do it:

```php
public function customizeSlugEngine(Slugify $engine, $attribute)
{
    $engine->addRule('\'', '');
    return $engine;
}
```

**Comment by jordanade** [comment]
@cviebrock Thanks! Perfect!

**Comment by jordanade** [comment]
For future searchers: the upstream library:
https://github.com/cocur/slugify

**Comment by bhdrnzl** [comment]
What I did didn't solve the problem. There's no problem with another project. I also use the slugify package. # 359 didn't solve my problem.
