### ISSUE TITLE
Not Working in API

### ISSUE THREAD

**Issue by moses-bowman** [cviebrock/eloquent-sluggable#463]
While working on my application's API, I encountered an error in Postman when I tried creating a new model:

`SQLSTATE[HY000]: General error: 1364 Field 'slug' doesn't have a default value`
 
Eloquent Sluggable works perfectly fine with the normal `store` route

**Comment by cviebrock** [comment]
> Of course, your model and database will need a column in which to store the slug. You can use slug or any other appropriate name you want; your configuration array will determine to which field the data will be stored. You will need to add the column manually via your own migration.

I'm guessing you defined the `slug` field as NOT NULL but without a default value.  You probably want the column to be nullable.

**Comment by moses-bowman** [comment]
Sorry, but the `slug` column is meant to be _NOT NULL_.

Here's my setup. I have two `ItemController`s sharing the same `Item` model:

1. `App\Http\Controllers\ItemController.php`
2. `App\Http\Controllers\API\ItemController`

The `Item` model has the `sluggable()` function:
`
public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
`

Eloquent-Sluggable works as it should when storing a new item via the form handled by `App\Http\Controllers\ItemController.php`

The problem is when I submit a new `POST` request to store a new item via API handled by `App\Http\Controllers\API\ItemController`, this error occurs:

`SQLSTATE[HY000]: General error: 1364 Field 'slug' doesn't have a default value`
