### ISSUE TITLE
Override generateSlug method

### ISSUE THREAD

**Issue by yamenarahman** [cviebrock/eloquent-sluggable#469]
The package isn't working for other languages like 'Arabic' in my case. So, how can I override the generateSlug method?

**Comment by cviebrock** [comment]
Have you tried this: https://github.com/cviebrock/eloquent-sluggable/issues/338#issuecomment-273024457

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
