### ISSUE TITLE
Thai character support

### ISSUE THREAD

**Issue by uchamb** [cviebrock/eloquent-sluggable#473]
It doesn't support Thai characters such as: "ไรเดอร์ ฟรี"
It generates an empty slug when unknown characters are used.

**Thank you!**

**Comment by cviebrock** [comment]
There doesn't appear to be a Thai ruleset for cocur/slugify (https://github.com/cocur/slugify/tree/master/Resources/rules).  You can make a PR against that project to add Thai support, or create your own slugging engine and swap that out in this package.

See https://github.com/cviebrock/eloquent-sluggable#customizeslugengine

**Comment by gumpon** [comment]
Config method  :

$string = preg_replace('/[^a-z0-9ก-๙เแ]/i', '-', $string);
