### ISSUE TITLE
Working with Spatie Translatable

### ISSUE THREAD

**Issue by visualight** [cviebrock/eloquent-sluggable#474]
For Laravel 5.4 users : Make Eloquent sluggable working with spatie translatable.
Here is some fix : https://github.com/visualight/spatie-translatable-cviebrock-eloquent-sluggable

Have a nice day

**Comment by cviebrock** [comment]
Thanks for the suggestions!  If you can work them into a PR for this package, I'd be happy to consider merging them in.
