### ISSUE TITLE
do it support duplicate slug in a model?

### ISSUE THREAD

**Issue by vahidalvandi** [cviebrock/eloquent-sluggable#475]
hi
i have post model , and have title,slug , if i create duplicate title do it can create unique slug ?

ex:

hello world
**hello-world**
---
hello world
**hello-world-**

**Comment by cviebrock** [comment]
Yes, it should create unique slugs using the default configuration.

```
hello-world
hello-world-1
hello-world-2
...
```

See https://github.com/cviebrock/eloquent-sluggable#unique
