### ISSUE TITLE
Support Laravel 6

### ISSUE THREAD

**Issue by InfoSecRavindra** [cviebrock/eloquent-sluggable#478]
It is almost Laravel 6 release time.

**Comment by lorvent** [comment]
since there are many people who want to test latest version or work on latest version.

please consider supporting 6.0

**Comment by cviebrock** [comment]
Version 6.0 of the package has just been released.  Try that and let me know if there are any issues.

**Comment by rajeevbhlone** [comment]
There is a problem installing this package in laravel 6

Issue :
Problem 1
    - Installation request for cviebrock/eloquent-sluggable 6.0 -> satisfiable by cviebrock/eloquent-sluggable[6.0.0].
    - Conclusion: remove laravel/framework v5.8.35
    - Conclusion: don't install laravel/framework v5.8.35
    - cviebrock/eloquent-sluggable 6.0.0 requires illuminate/config ~6.0.0 -> satisfiable by illuminate/config[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - don't install illuminate/config v6.0.0|don't install laravel/framework v5.8.35
    - don't install illuminate/config v6.0.1|don't install laravel/framework v5.8.35
    - don't install illuminate/config v6.0.2|don't install laravel/framework v5.8.35
    - don't install illuminate/config v6.0.3|don't install laravel/framework v5.8.35
    - don't install illuminate/config v6.0.4|don't install laravel/framework v5.8.35
    - Installation request for laravel/framework (locked at v5.8.35, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.35].
