### ISSUE TITLE
Request update for Laravel 6.0

### ISSUE THREAD

**Issue by quangvision** [cviebrock/eloquent-sluggable#479]
Hi
Can you please upgrade this package to support Laravel 6.0?
   Thanks :)

**Comment by marcelogarbin** [comment]
This package is wonderful, I'm starting a new project and would like to use it on Laravel 6 LTS. Any predictions to upgrade? Awaiting.

**Comment by cviebrock** [comment]
Version 6.0 of the package has just been released.  Try that and let me know if there are any issues.
