### ISSUE TITLE
updating from laravel 5.8 - laravel 6.0

### ISSUE THREAD

**Issue by Devrandomuser** [cviebrock/eloquent-sluggable#481]
When updating to laravel 6.0 I get this error all the time:

Your requirements could not be resolved to an installable set of packages.

>   Problem 1
    - Conclusion: don't install laravel/framework v6.0.1
    - Installation request for cviebrock/eloquent-sluggable ^6.0 -> satisfiable by cviebrock/eloquent-sluggable[6.0.0].
    - Conclusion: don't install laravel/framework v6.0.0
    - Conclusion: don't install laravel/framework 6.x-dev

composer.json

        "laravel/framework": "^6.0",
        "cviebrock/eloquent-sluggable": "^6.0",

What's the correct version for laravel 6.0?

**Comment by alexanderglueck** [comment]
I think we nead another release featuring [this commit](https://github.com/cviebrock/eloquent-sluggable/commit/86d8ecb4056546ef3cab7356c33a117979c89e7d).
Then it should work just fine

**Comment by cviebrock** [comment]
6.0.1 is out now.  Thanks!
