### ISSUE TITLE
Posts appears more than once after posting

### ISSUE THREAD

**Issue by henrymainforum** [cviebrock/eloquent-sluggable#482]
public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'subject'
            ]
        ];
    }

After doing this and having the slug in my Database, posts appears more than once in my view

**Comment by cviebrock** [comment]
This doesn't seem related to the package at all.  How are are you choosing which posts to display in your view?

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
