### ISSUE TITLE
Installation fail in Laravel 6.0.4

### ISSUE THREAD

**Issue by kindslayer** [cviebrock/eloquent-sluggable#484]
after run composer require, I have this error.
Installation request for laravel/framework (locked at v6.0.4, required as ^6.0) -> satisfiable by laravel/framework[v6.0.4].

**Comment by mickaellapouge** [comment]
same here

**Comment by cviebrock** [comment]
What does your `composer.json` file look like for your project?

**Comment by RichardDern** [comment]
Just use:

```composer install cviebrock/eloquent-sluggable```

Without specifying a version, or:

```composer install cviebrock/eloquent-sluggable:^6.0```

**Comment by mickaellapouge** [comment]
Worked with : 
composer require cviebrock/eloquent-sluggable
thx
