### ISSUE TITLE
Custom separator for multi-fields source

### ISSUE THREAD

**Issue by RichardDern** [cviebrock/eloquent-sluggable#485]
When using multiple fields as a source, like in exemple below, we should be able to specify a custom separator (note that here, "separator" means "between two fields").

```php
public function sluggable()
{
    return [
        'slug' => [
            'source' => ['parent_slug', 'name'],
            'source_separator' => '/'
        ],
    ];
}
```

Currently, what is slugged is the concatenation of 'parent_slug' and 'name', separated with a space, as seen in _Services/SlugService.php_, last line of the _getSlugSource_ method.

What we should be able to do, is to concatenate the slugged string for 'parent_slug' with the slugged string for 'name', using a custom separator (I have the '/' character in mind ATM).

It would be helpful and meaningful with nested categories/posts/etc.

For instance, as for now, using slug against this structure:

```
Dev > Web > PHP > My Libraries > eloquent-sluggable
```

Will produce this slug (for the last model in this chain):

```
{model}/dev-web-php-my-libraries-eloquent-sluggable
```

What I suggest is it can produce the following, depending on a new configuration element:

```
{model}/dev/web/php/my-libraries/eloquent-sluggable
```

**Comment by cviebrock** [comment]
I like this idea.  I don't have a lot of time in the next little while to make this change, but would happily accept a PR with this functionality if you wanted to put one together in the meantime.

**Comment by RichardDern** [comment]
Done here #488 !

**Comment by RichardDern** [comment]
Update: it's here: #489
