### ISSUE TITLE
Your configuration files are not serializable 

### ISSUE THREAD

**Issue by faridmovsumov** [cviebrock/eloquent-sluggable#491]
I tried to use following config option 

```
'method' => function( $string, $sep ) {
        $result = str_slug(\Patchwork\Utf8::toAscii($string));
        if(empty($result)){
            $result = "user".time();
        }
        return $result;
    },
```
and I got the following error while caching configuration files.

```
In ConfigCacheCommand.php line 71:
  Your configuration files are not serializable.
In config.php line 566:
  Call to undefined method Closure::__set_state()
```

![image](https://user-images.githubusercontent.com/1541412/67561518-4ed1df00-f71d-11e9-833c-97f05b72e66e.png)

Laravel config cache is not supporting closures. Do you have any ideas to fix this problem?

**Comment by hamedsrk** [comment]
i did the solution in this issues and it work fine
https://github.com/cviebrock/eloquent-sluggable/issues/392
but then i find another problem that i asked at the end
