### ISSUE TITLE
option like unique or separated don't work

### ISSUE THREAD

**Issue by shdehnavi** [cviebrock/eloquent-sluggable#493]
hi there,
`unique` and slug `separator ` don't work in options !
My code:
`public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title',
                'separator' => '/',
            ]
        ];
    }`

when `my post` sent as slug, this converted to `my-post` not `my/post`

**Comment by pjplonka** [comment]
I have the same in 6.2. Unique slug is not working - all the time I have the same slug.

**Comment by shdehnavi** [comment]
any ideas ?

**Comment by codebyray** [comment]
Same issue in L5.8, if the same slug already exists it does not create a unique slug. I have narrowed it down to an additional conversion I have set in the model:

```php
public function setSlugAttribute($value)
{
    $this->attributes['slug'] = strtoupper($value);
}
```
When I comment out the above in my model I get the desired results (slugs are created as unique). However, by converting the slug like above it breaks and does not create a unique slug when identical information is put in.

Not sure exactly why this causes the issue. Hopefully this helps identify the problem.

Regards,
Ray

**Comment by cviebrock** [comment]
Yeah, you shouldn't use any magic methods on your model to set the slug attribute, as the packages should handle all that for you.

If you really want only upper-case slugs, for instance, then you could do this with a custom `method` in your config, custom getters for the source fields (and then update the `source` config accordingly), or by customizing the Slug Engine.
