### ISSUE TITLE
PHP 7.4.1 issues

### ISSUE THREAD

**Issue by PeterNdeke** [cviebrock/eloquent-sluggable#495]
ErrorException
implode(): Passing glue string after array is deprecated. Swap the parameters

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
:141
C:\xampp\htdocs\foodcash\vendor\cviebrock\eloquent-sluggable\src\Services\SlugService.php:141

**Comment by Stokoe0990** [comment]
Same error here.

@cviebrock

**Comment by VeRJiL** [comment]
same here 
@cviebrock

**Comment by awebmaker** [comment]
same here

**Comment by cviebrock** [comment]
A fix for this was merged back in October, into version 6.0.2 of the package.

**Comment by Stokoe0990** [comment]
@cviebrock So how come so many people are reporting the same issue?

**Comment by PeterNdeke** [comment]
@cviebrock ok sir, so an update to 6.0.2 can fix it

**Comment by PeterNdeke** [comment]
@cviebrock  issue is fixed with an update to version 6.0.2. Thanks
Issue solved and closed

**Comment by veneliniliev** [comment]
can you fix for the old releases

**Comment by marcelogarbin** [comment]
I'm using Laravel 5.5, the PHP 7.4 server. Same mistake here. 

Any news about the fix or how can we make it work?

Version `cviebrock/eloquent-sluggable  4.4.1`
![image](https://user-images.githubusercontent.com/9335588/73801738-25a00080-479a-11ea-92cc-526a2f755873.png)

**Comment by silasrm** [comment]
For 4.5.*, 4.6.* and 4.7.* trying:

https://github.com/silasrm/eloquent-sluggable/releases

Using one of them:
`"cviebrock/eloquent-sluggable": "4.5.2"`
`"cviebrock/eloquent-sluggable": "4.6.1"`
`"cviebrock/eloquent-sluggable": "4.7.1"`


Add in same level of "require" property:

"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/silasrm/eloquent-sluggable"
        }
    ],

**Comment by Vakil-Parth** [comment]
@cviebrock

**Comment by cviebrock** [comment]
@Vakil-Parth , @silasrm , @garbinmarcelo , @veneliniliev  ...

I've pushed versions 4.5.2, 4.6.1 and 4.7.1 to this project which fix the order of arguments for `implode()`.  Sorry this took so long to back-port.  Let me know if you have any issues.
