### ISSUE TITLE
Turkish Character Problem ex. ["Ö", "Ü"]

### ISSUE THREAD

**Issue by furkangiray** [cviebrock/eloquent-sluggable#496]
Hello, first of all thanks for this great package. I have a problem about turkish characters. For example my title is : "E-Ticaret Güvenlik Önlemleri", my slug is : "e-ticaret-guevenlik-oenlemleri" but it should be "e-ticaret-guvenlik-onlemleri" right ? So how can I fix this problem ? Which file should I edit ?

Thanks for replies guys.

**Comment by cviebrock** [comment]
If you aren't customizing the cocur/slugify engine to use the Turkish rules, you should.  In your model:

```php
    public function customizeSlugEngine(Slugify $engine, $attribute)
    {
        $engine->activateRuleSet('turkish');

        return $engine;
    }
```

Taking a quick look at https://github.com/cocur/slugify/blob/master/Resources/rules/turkish.json shows that this should solve your problem and do the correct conversion.
