### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry for Soft Delete

### ISSUE THREAD

**Issue by Dzoni45** [cviebrock/eloquent-sluggable#501]
Hello,

I find issue on  Duplicate entry for unique slugs, 
for example, if you using soft delete on model and 
you want to insert a new record with same title, but you have soft deleted recored with that slug,
that you trying to instert with a new one,
you will get Integrity constraint violation. 
Is there any solution or fix for this?

Thanx,
Nikola

**Comment by zvermafia** [comment]
Did you set to `true` an `includeTrashed` config option?

**Comment by Dzoni45** [comment]
> Did you set to `true` an `includeTrashed` config option?

Thank you.
