### ISSUE TITLE
Add an ability to regenerate slug on model update based on different source field

### ISSUE THREAD

**Issue by xYundy** [cviebrock/eloquent-sluggable#503]
Hello there!

In my application I want give my users an ability to change their page model's slug (like 
I want give my users to ability to manually change slug (permalink) to something different than originally generated by title. ([like Wordpress does](https://hostadvice.com/wp-content/uploads/2019/07/how-to-update-your-old-wordpress-posts-with-gutenberg-block-editor-1.png)).

In WordPress:

- First time (on create) slug will be created based on title (source field)
- If user update slug field with non-null value, it will be parsed to the slug form (lowercase, make unique, replace spaces with dashes etc.)
- if user update slug field with null value, it will be created based on title (source field)

For now I'm doing it like that:

````
/*
     * Slug Configuration
     *
     * Here are all methods and properties needed for slug to work
     */

    protected bool $isManualSlugUpdate = false; // The slug was edited by an user?
    protected bool $isSlugGenerated = false; // Slug was generated by SlugService?

    /**
     * Set slug attribute
     *
     * @param $value
     */
    public function setSlugAttribute($value): void
    {
        if($this->slug !== $value){
            if($this->isSlugGenerated) {
                $this->isSlugGenerated = false;
                $this->attributes['slug'] = $value;
            } else {
                if($value !== null || $value !== '') {
                    $this->isManualSlugUpdate = true;
                }
                $this->attributes['slug'] = $value;
                $this->isSlugGenerated = true;
                (new SlugService())->slug($this, true);
            }
        }

    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => $this->isManualSlugUpdate ? 'slug' : 'title',
                'unique' => true,
            ]
        ];
    }
````

This is not the prettiest piece of code I think. It does the job, but I think this behaviour can be handled by library itself.

Can you add an ability to regenerate slug on model update, based on current slug value instead of the initial source field?

**Thank you very much!**

**Comment by cviebrock** [comment]
I'm pretty sure what you are describing is how the library handles it by default (see https://github.com/cviebrock/eloquent-sluggable#onupdate).

Initially, the slug will be generated and saved.  if `onUpdate` is false (which is the default), then that field won't be updated again automatically.  You can changed it manually with `$model->slug = 'foo'; $model->save();` and it should take the "manual" slug you provided without question.

If you _do_ want it to be automatically generated again, then just set `$model->slug = null` and save.

Or am I missing something?

**Comment by xYundy** [comment]
I’m talking about converting manually provided slug to sluggable form and make it unique like other slugs.

**Comment by cviebrock** [comment]
Sorry for the delayed response.

I think what you are asking for is a bit beyond the scope of the package.  You can take advantage of [SlugService::createSlug](https://github.com/cviebrock/eloquent-sluggable#the-slugservice-class) to generate a "slugged" version of a string, and just use that in your controller to set the slug manually before saving (with onUpdate being false, of course).
