### ISSUE TITLE
Unable to get scopeWithUniqueSlugConstraints() to work propertly with Laravel Policies

### ISSUE THREAD

**Issue by adistoica** [cviebrock/eloquent-sluggable#504]
Hello!

First of all, thank you for developing such an awesome module for Laravel ! 

I'm having some troubles on getting my slugs to work correctly for two existing models using  `scopeWithUniqueSlugConstraints()`

Here is my current setup:

1. **Models**:
1. User -> default from Laravel (columns: id, name, email, etc)
2. Projects 
**Migration**
```
$table->bigIncrements('id');
$table->bigInteger('user_id')->unsigned()->index();
$table->foreign('user_id')->references('id')->on('users')->onDelete('CASCADE');
$table->string('name');
$table->string('slug');
```
**Model**
```php
use Sluggable;
use SluggableScopeHelpers;

public function user() {
        return $this->belongsTo(User::class);
}
public function getRouteKeyName() {
        return 'slug';
    }

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function scopeWithUniqueSlugConstraints(Builder $query, Model $model, $attribute, $config, $slug) {
        $user = $model->user;
        return $query->where('user_id', $user->getKey());
    }
```

2. **ProjectsController**
  ```php
public function show(Project $project) {
        $this->authorize('show', $project);
        return view('projects.view', compact('project'));
    }
```

3. **ProjectPolicies**

``` php
// this is working perfectly without any slugs
public function show(User $user, Project $project) {
        return $user->id == $project->user_id;
 }
```

**Route**
```php
    Route::get('/project/{project}', 'ProjectsController@show')->name('projects');
```

My problem is that if I have the same slug for two different projects, but created with a different user (so different user_id in the Projects model), I will always get a 403 access denied.

If I remove the Policies part, it seems that only one Project object is being thrown, which is not related to the User. 

How should I tackle this topic ? It's been giving me headaches for the past two days, trying multiple variants from the documentation and from the closed tickets, but without any results.

Any help would be highly appreciated.

Thanks,
Adrian

**Comment by xYundy** [comment]
Hey Adrian!

I think it is not problem with eloquent-sluggable. This package works as you wish: creates the same slug because userId is different.

The problem is your route model binding: This looking only by slug and get the first item which meet this criteria. If you wish use route model binding in this particular environment please look at the: [Eloquent Global Scopes](https://laravel.com/docs/5.8/eloquent#global-scopes)

For your problem I will create Scope:

```
<?php

namespace App\Scopes;

use Illuminate\Database\Eloquent\Scope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class UserProjectsScope implements Scope
{
    /**
     * Apply the scope to a given Eloquent query builder.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $builder
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return void
     */
    public function apply(Builder $builder, Model $model)
    {
        $builder->where('user_id', auth()->id());
    }
}
```

And register it in model:
```
<?php

namespace App;

use App\Scopes\UserProjectsScope;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new UserProjectsScope);
    }
}
```

I hope this example and Laravel documentation helps you :)

**Comment by adistoica** [comment]
Many thanks @xYundy for the provided code sample! It is working perfect right now.

Somehow I was thinking that by doing: 
```php
 public function scopeWithUniqueSlugConstraints(Builder $query, Model $model, $attribute, $config, $slug) {
        $user = $model->user;
        return $query->where('user_id', $user->getKey());
    }
```

`eloquent-sluggable` will "filter" the values by the `user_id` column in my `user` model, but I guess I got it wrong.

**Comment by xYundy** [comment]
@adistoica You're right ``eloquent-luggable`` do that, but for **slug building & validation only**.
This library don't interfere in any way with Eloquent methods and Route Model Binding because it's not it's purpose.  That's why you must code it on your own.

**Comment by adistoica** [comment]
Thanks for the clarifications!
I'll close this issue, as it solves my problem.
