### ISSUE TITLE
null slug

### ISSUE THREAD

**Issue by raulinoamaral** [cviebrock/eloquent-sluggable#508]
I'm using `"laravel/framework": "5.6.*"` and `"cviebrock/eloquent-sluggable": "^4.5"`.
Here is the code from a Model and a Controller that doesn't generate the slug.

**News Model**
```
use Cviebrock\EloquentSluggable\Sluggable;
class News extends Model
{
    use Sluggable;

    protected $fillable = [
        'title',
        'slug',
    ];

    public function sluggable()
    {   
        return [
            'slug' => [
                'source' => 'long_slug'
            ]
        ];
    }

    public function getLongSlugAttribute()
    {
        return $this->title . ' ' . $this->id; 
    }
...
}
```

In **News Controller**

```
public function store(NewRequest $request)
    {
        $news = News::create($request->all());
        $news->save();
        return redirect()->action('Admin\NewsController@editImages', [$news->id]);
    }
```
This started to happend when I upgraded to Laravel 5.6. I already ran composer update lots of times and reinstall cviebrock/eloquent-sluggable.
Am I missing something? Can somebody help me? Thanks.

**Comment by raulinoamaral** [comment]
Hey, I realized that the slug wasn't working only in some models, so I compared the models and I found that in those which slug doesn't work, I was using them to generate index data with laravel scout / algolia.

I mean, if I delete the News model from this [algolia aggregator](https://www.algolia.com/doc/framework-integration/laravel/advanced-use-cases/multiple-models-in-one-index/?language=php), the slug start to work in the model.

```
namespace App;
use Algolia\ScoutExtended\Searchable\Aggregator;

class Search extends Aggregator
{
    protected $models = [
        News::class,
        Posts::class,
    ];    
}
```
Do you know if there's some kind of incompatibility with both packages?

**Comment by cviebrock** [comment]
I'm not familiar with that package at all, sorry.
