### ISSUE TITLE
Error under vendor\cviebrock\eloquent-sluggable\tests

### ISSUE THREAD

**Issue by florencebib** [cviebrock/eloquent-sluggable#509]
error when running ./vendor/bin/phpunit

Undefined type 'Orchestra\Testbench\TestCase'.
Undefined method 'artisan'.
Undefined method 'beforeApplicationDestroyed'.
Undefined method 'artisan'.
Undefined type 'Cviebrock\EloquentSluggable\Tests\TestServiceProvider'.

I tried to run composer update but still can't solve it. This happened after I run the install laravel/browser-kit-testing

  "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "1.*",
        "phpunit/phpunit": "^8.0",
        "symfony/css-selector": "4.2.*",
        "symfony/dom-crawler": "4.2.*",
        "laravel/browser-kit-testing": "5.*"
    }

**Comment by cviebrock** [comment]
Sorry for the delay.  This looks like something messed up with your install, or with your composer autoloader maybe?  I'd recommend removing your apps `composer.lock` file and `vendor` directory, and doing a fresh `composer install`.

(Also, you shouldn't be running my package's tests when testing _your_ application.  For starters, most of the test files in eloquent-sluggable are devDependencies, so they aren't usually loaded when you install the package.)

**Comment by florencebib** [comment]
Thanks for your comment, I think it is version conflict issue as I am running an old version of Laravel. I believe reinstallation should work. Thanks!
