### ISSUE TITLE
slug for unicode

### ISSUE THREAD

**Issue by vtxmg** [cviebrock/eloquent-sluggable#511]
I want to make slug for Nepali unicode. (Example:स्पेनका पाँच फुटबल खेलाडीमा कोरोना पुष्टि to 
स्पेनका-पाँच-फुटबल-खेलाडीमा-कोरोना-पुष्टि)
But it convert the unicode into English language.
Can you help?

**Comment by cviebrock** [comment]
Sorry for the delay.  You would need to write your own slugging logic to accomplish this.  Take a look at [the `method` configuration settting](https://github.com/cviebrock/eloquent-sluggable#method).
