### ISSUE TITLE
Unique slug per type

### ISSUE THREAD

**Issue by bally86** [cviebrock/eloquent-sluggable#512]
Hi,

I have a question. My model contains two types of records. Is it possible to define the uniqueness based on an extra column in the model?
So all the records with type A needs to be unique and alle records with type B needs to be unique.

I used the scopeWithUniqueSlugConstraints but it doesnt seem to work. It still appends a -1 to the slug.

`public function sluggable()
    {
        return [
            'folder' => [
                'source' => 'folder',
                'includeTrashed' => true
            ],
        ];
    }`

`public function scopeWithUniqueSlugConstraints(Builder $query, Model $model, $attribute, $config, $slug)
    {
        return $query->where('model', $model->model);
    }`

Thank you in advance.

**Comment by cviebrock** [comment]
This is very doable.  See https://github.com/cviebrock/eloquent-sluggable/blob/master/tests/Models/PostWithUniqueSlugConstraints.php for an example where a slug for a Post is scoped to it's author.

Why it's not working in your case, I'm not sure.  If you can make a test case for the package's test suite that fails, I can take a closer look.

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
