### ISSUE TITLE
Source from local json field

### ISSUE THREAD

**Issue by thanosalexander** [cviebrock/eloquent-sluggable#514]
I've read the docs well, but i didn't find any option to set the source from a local field.
eg i have a local name field (json) which keeps my translations (name->en,name->fr ....)

I tried to  set `  'source' => 'name->en'` but no luck.
The only solution is to create an other getter eg 

```
 public function getSlugNameAttribute($value)
 {
       return $this->name;
 }
```

and then use this in source `  'source' => 'slug_name'`.

But this is not the optimal i'd like!

**Comment by cviebrock** [comment]
Sorry for the delay.

Sadly, using a custom getter (or a callable) is the only way to do what you want right now.  It's only "unoptimal" in that you will need to add that customer getter method to your models (but you could make a trait if you are constantly re-using that method).  It shouldn't be "unoptimal" in terms of how fast your code runs.
