### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'slug' in 'field list' (SQL: select `slug`, `tbl_blog`.`id` from `tbl_blog` where (`slug` = no-is-ok or `slug` LIKE no-is-ok-%))

### ISSUE THREAD

**Issue by ziZily** [cviebrock/eloquent-sluggable#515]
Please be sure you include all the relevant information in your issue so we can help you:

- [ ] steps taken to reproduce your issue
- [ ] your configuration file(s), where relevant
- [ ] a copy of your Models that use or extend this package (just the relevant parts!)
- [ ] any other code we might need to help

Please use a descriptive title for your issue.  "Why doesn't this work?" doesn't provide 
other users much information if they are scanning the list of issues.

Also, *please* use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
when pasting more than one line of code.  It makes it so much more readable for everyone!

**Thank you!**

**Comment by ziZily** [comment]
hi,i have a problam with use this package in laravel,when i have a mysql table with existing rows:
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
class blog extends Model
{
    protected $table = 'tbl_blog';
    use Sluggable;
    public function sluggable()
    {
        return [
            'slug' => [
                'source' =>'blog_title',
            ]
        ];
    }
    public $fillable=[
        'blog_title','blog_title_en','blog_title_tr','blog_title_ar','blog_img','blog_describe','blog_describe_en',
        'blog_describe_tr','blog_describe_ar','blog_group','blog_user_id','blog_register_date','blog_keywords','blog_keywords_en',
        'blog_keywords_tr','blog_keywords_ar','blog_spend_time','blog_podcast','blog_podcast_en','blog_podcast_tr','blog_podcast_ar',
        'blog_status','blog_page_visit'
        ];
    public $timestamps=false;
}
--------------------------------------------------------------------------------------------
        config(['sluggable.onUpdate' => true]);
        blog::all()->each->save();
        $blog=new blog([
                'blog_title' =>'no is ok','blog_title_en' => 'yes is ok','blog_title_tr' =>'yes is ok','blog_title_ar' =>'yes is ok',
                'blog_describe' => 'yes is ok','blog_describe_en' =>'yes is ok','blog_describe_tr' => 'yes is ok','blog_describe_ar' =>'yes is ok',
                'blog_group' =>'yes is ok','blog_spend_time'=>10,
                'blog_keywords'=>'yes is ok','blog_keywords_en'=>'yes is ok','blog_keywords_tr'=>'yes is ok','blog_keywords_ar'=>'yes is ok',
                'blog_register_date' => time(), 'blog_podcast' =>'yes is ok',
                'blog_podcast_en' => 'yes is ok',
                'blog_podcast_tr' =>'yes is ok','blog_podcast_ar' => 'yes is ok',
                'blog_user_id'=>1
            ]);
        $blog->save();

        dd($blog->slug);
-----------------------------------------------------------------------------------------
tanks for any help

**Comment by ziZily** [comment]
my modal:
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
class blog extends Model
{
    protected $table = 'tbl_blog';
    use Sluggable;
    public function sluggable()
    {
        return [
            'slug' => [
                'source' =>'blog_title',
            ]
        ];
    }
    public $fillable=[
        'blog_title','blog_title_en','blog_title_tr','blog_title_ar','blog_img','blog_describe','blog_describe_en',
        'blog_describe_tr','blog_describe_ar','blog_group','blog_user_id','blog_register_date','blog_keywords','blog_keywords_en',
        'blog_keywords_tr','blog_keywords_ar','blog_spend_time','blog_podcast','blog_podcast_en','blog_podcast_tr','blog_podcast_ar',
        'blog_status','blog_page_visit'
        ];
    public $timestamps=false;
}

**Comment by ziZily** [comment]
use Cviebrock\EloquentSluggable\Sluggable; 

   protected $table = 'tbl_blog';
    use Sluggable;
    public function sluggable()
    {
        return [
            'slug' => [
                'source' =>'blog_title',
            ]
        ];
    }
    public $fillable=[
        'blog_title','blog_title_en','blog_title_tr','blog_title_ar','blog_img','blog_describe','blog_describe_en',
        'blog_describe_tr','blog_describe_ar','blog_group','blog_user_id','blog_register_date','blog_keywords','blog_keywords_en',
        'blog_keywords_tr','blog_keywords_ar','blog_spend_time','blog_podcast','blog_podcast_en','blog_podcast_tr','blog_podcast_ar',
        'blog_status','blog_page_visit'
        ];
    public $timestamps=false;

**Comment by ziZily** [comment]
my controller:

        config(['sluggable.onUpdate' => true]);
        blog::all()->each->save();
        $blog=new blog([
                'blog_title' =>'no is ok','blog_title_en' => 'yes is ok','blog_title_tr' =>'yes is ok','blog_title_ar' =>'yes is ok',
                'blog_describe' => 'yes is ok','blog_describe_en' =>'yes is ok','blog_describe_tr' => 'yes is ok','blog_describe_ar' =>'yes is ok',
                'blog_group' =>'yes is ok','blog_spend_time'=>10,
                'blog_keywords'=>'yes is ok','blog_keywords_en'=>'yes is ok','blog_keywords_tr'=>'yes is ok','blog_keywords_ar'=>'yes is ok',
                'blog_register_date' => time(), 'blog_podcast' =>'yes is ok',
                'blog_podcast_en' => 'yes is ok',
                'blog_podcast_tr' =>'yes is ok','blog_podcast_ar' => 'yes is ok',
                'blog_user_id'=>1
            ]);
        $blog->save();

        dd($blog->slug);

**Comment by cviebrock** [comment]
Looks to me like you don't have a `slug` column on that table.  The package doesn't do that migration for you: https://github.com/cviebrock/eloquent-sluggable#updating-your-eloquent-models
