### ISSUE TITLE
Would be possible to concatenate a field with id?

### ISSUE THREAD

**Issue by leandromatos** [cviebrock/eloquent-sluggable#516]
Considering I have a model with `id`, `title` and `slug` fields, would be possible to concatenate the title and id to create a slug?

I expect a result like that:

| Id  | Title | Slug
| --- | --- | ---
| 9a4b13ea-be0d-11ea-b3de-0242ac130004  | Lorem Ipsum  | lorem-ipsum-9a4b13ea-be0d-11ea-b3de-0242ac130004

**Comment by ingoldsby** [comment]
Is this in your model? The default may have been title or something like that. This update to array would do what you want. https://github.com/cviebrock/eloquent-sluggable#source

/**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => ['title', 'id']
            ]
        ];
    }

**Comment by leandromatos** [comment]
@ingoldsby Your suggestion not work.

**Comment by mushtaqx** [comment]
You can create a getter and concatinate anything you want there, then add it as source
```
    public function getSlugSourceAttribute()
    {
        return $this->id . $this->title;
    } 
```

then add it in 
```
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'slug_source'
            ]
        ];
    }
```
