### ISSUE TITLE
Upgrade to Laravel 8

### ISSUE THREAD

**Issue by aminkariminasab** [cviebrock/eloquent-sluggable#518]
I want to upgrade Laravel 7 to 8; But I got the error about slug package version. 
Here is the upgrading documentations : 
[https://laravel.com/docs/master/upgrade](https://laravel.com/docs/master/upgrade)

Please upgrade the package to Laravel 8.
Thanks.

**Comment by prof-usman** [comment]
yes please

**Comment by Believemenot** [comment]
+1

**Comment by LyonelZ** [comment]
Yes please

**Comment by karlosremolina** [comment]
still not working, please update, we appreciate it

**Comment by jaydrogers** [comment]
There are two PRs for this already. We'll just need to watch the status of these:
#524 
#525

**Comment by cviebrock** [comment]
Version 8.0 is available now.

**Comment by jaydrogers** [comment]
Thanks a ton for your work @cviebrock!

**Comment by aminkariminasab** [comment]
Thanks a lot @cviebrock !

**Comment by prof-usman** [comment]
Thanks a lot @cviebrock
