### ISSUE TITLE
how Can we create Slug of an array in eloquent Sluggable ?

### ISSUE THREAD

**Issue by nirmaldangi2004** [cviebrock/eloquent-sluggable#520]
Please be sure you include all the relevant information in your issue so we can help you:

- [ ] steps taken to reproduce your issue
- [ ] your configuration file(s), where relevant
- [ ] a copy of your Models that use or extend this package (just the relevant parts!)
- [ ] any other code we might need to help

Please use a descriptive title for your issue.  "Why doesn't this work?" doesn't provide 
other users much information if they are scanning the list of issues.

Also, *please* use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
when pasting more than one line of code.  It makes it so much more readable for everyone!

**Thank you!**

**Comment by cviebrock** [comment]
If you mean an array or list of model attributes, you can do that by providing them all in an array in the [config](https://github.com/cviebrock/eloquent-sluggable#source):

```php
'source' => ['firstname', 'middlename', 'lastname'],
```

If you have a model attribute that is an array, then I'd suggest making a separate getter to convert it to a string and use that as the source:

```php
'source' => 'slug_source',

...

public function getSlugSourceAttribute()
{
    return implode(' ', $this->myArray);
}
```
