### ISSUE TITLE
how can I make slug without globle scope

### ISSUE THREAD

**Issue by yatin13490** [cviebrock/eloquent-sluggable#521]
Hi,

I have added the global scope with models boot method but I need to make slug unique without globalScope, How can I remove the globalSocpe when the slug generating

**Comment by cviebrock** [comment]
I'm not sure, but I think you would need to add something like this to that model:

```php

/**
 * @param \Illuminate\Database\Eloquent\Builder $query
 * @param \Illuminate\Database\Eloquent\Model $model
 * @param string $attribute
 * @param array $config
 * @param string $slug
 * @return \Illuminate\Database\Eloquent\Builder
 */
public function scopeWithUniqueSlugConstraints(Builder $query, Model $model, $attribute, $config, $slug)
{
    return $query->withoutGlobalScope(MyScope::class);
}
```

See Laravel's docs on [Removing Global Scopes](https://laravel.com/docs/8.x/eloquent#global-scopes) for the possible syntax to use.

Let me know if this works for you!

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
