### ISSUE TITLE
Set Unique Slug Per Tenant 

### ISSUE THREAD

**Issue by lovecoding-git** [cviebrock/eloquent-sluggable#526]
Hi, 

First of all, thank you for such great package.
I have been using it for almost all of my projects.
Is it possible to set unique slug per tenant in multi-tenant app?
I have `tenant_id` column in each table so I need to set unique slugs only per tenant_id.

Any suggestion would be highly appreciated.

Thank you

**Comment by cviebrock** [comment]
Yup!  Take a look at https://github.com/cviebrock/eloquent-sluggable#scopewithuniqueslugconstraints for how to do it.
