### ISSUE TITLE
When the slug value is equal to "0", it will be replaced by auto generate slug

### ISSUE THREAD

**Issue by huiyang** [cviebrock/eloquent-sluggable#527]
To reproduce the issue:
- Create a model using the Sluggable trait
- Add sluggable method as following:
```php
public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
```
- Set the value of the "title property of the model to "example title"
- Set the value of the "slug" property of the model to 0. (Eg: ```$model->slug = '0';``` )
- Save the model, the value of the slug will become "example-title" instead of "0"

This issue is caused at the "needsSlugging" checking which used empty()

https://github.com/cviebrock/eloquent-sluggable/blob/becedfe5634740ee2bc3a3ee5ea01435547ee653/src/Services/SlugService.php#L107

- [x] steps taken to reproduce your issue
- [x] your configuration file(s), where relevant
- [x] a copy of your Models that use or extend this package (just the relevant parts!)
- [x] any other code we might need to help

**Comment by cviebrock** [comment]
I made a few adjustments to your PR, but version 8.0.1 of the package includes your fix.  Thanks!
