### ISSUE TITLE
Japanese language support?

### ISSUE THREAD

**Issue by dishereandy** [cviebrock/eloquent-sluggable#529]
I know that concur/slugify currently does not support Japanese characters. Currently whenever I used Japanese characters, the slug returns as 0 or -1. I'm wondering how to insert a default value such as the ID of the row and etc. whenever an unsupported languages are used or if there's any workaround or fix to this.

**Comment by cviebrock** [comment]
You can always configure a [custom `method`](https://github.com/cviebrock/eloquent-sluggable#method) so that you aren't using cocur/slugify as the engine to generate slugs.  That might be useful if you know that you are always using Japanese characters in the source fields.

Alternatively, you could change the source to a custom getter and handle the logic in there.  So instead of using `title` directly as your source, create a `getCleanTitleAttribute` method and do something like:

```php
class MyModel extends Eloquent
{
    use Sluggable;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'clean_title'
            ]
        ];
    }

    public function getCleanTitleAttribute()
    {
        if (preg_match('/UNSUPPORTED CHARACTER REGEX CHECK/', $this->title))
        {
            return $this->row; // or whatever you want to use as the source
        }

        // no unsupported characters, so we can use the title
        return $this->title;
    }
}
```

**Comment by dishereandy** [comment]
I see, thanks for the answer. Perhaps, I will instead check if the input is supported instead of checking for unsupported characters as there might be character that are not currently supported that I don't know about. Is there any plan or update for this package regarding this kind of problem?

**Comment by cviebrock** [comment]
Apart from switching away from cocur/slugify to some other kind of engine, no I don't have any plans for this.  I think for the majority of users, the current engine works fine.  And for those like yourself where it doesn't, the workaround isn't too onerous/complicated.

I'm totally open to suggestions though!

**Comment by dishereandy** [comment]
I agree that it isn't too complicated. However, it would be nice have something like the solution you've described already included in the package. Maybe a method automatically detects unsupported languages?
Thanks for the suggestion anyhow.
