### ISSUE TITLE
Ampersand symbol to and when slugging?

### ISSUE THREAD

**Issue by kikky7** [cviebrock/eloquent-sluggable#530]
This is not an issue, just a question about possible feature:

I have string "Foo & Bar", created slug will be "foo-bar"; is there an option to add "masks" which can convert "&" to "and" so the final slug would be "foo-and-bar"?

**Comment by cviebrock** [comment]
You can already do this with a custom getter!  Something like this should work:

```php
class Book extends Eloquent
{
    use Sluggable;

    public function sluggable() {
        return [
            'slug' => [
                'source' => ['clean_title']
            ]
        ];
    }
    
    public function getCleanTitleAttribute() {
        return str_replace(
            ['&', '$', '%'],
            ['and', 'dollars', 'percent'],
            $this->title
        );
    }
}
