### ISSUE TITLE
 How do I create a slug without creating a column?

### ISSUE THREAD

**Issue by laotien** [cviebrock/eloquent-sluggable#537]
**I want to create a slug table to store for many other tables, but don't know how to get the slug for each table.

Pls, help me**

**Comment by cviebrock** [comment]
I'm not sure what you are asking.  Currently, the slug values are stored in a column in each models' table.  That is, it's not polymorphic with all the slugs in one table.

That's something I've considered, but haven't implemented (as I'm not yet convinced it's a common enough use case to break previous installs).

I'm sure you can code around it, somewhat, by hooking into the [event system](https://github.com/cviebrock/eloquent-sluggable#events) or one of the other configurable methods.
