### ISSUE TITLE
8.0.3 breaks non-nullable slug column

### ISSUE THREAD

**Issue by KamaZz** [cviebrock/eloquent-sluggable#542]
Hi, 8.0.3 breaks non-nullable column.
Perhaps it will be correct to pre-fill the slug field with an empty line?

**Comment by adamthehutt** [comment]
8.03 broke my code as well, but perhaps the tag has been deleted because I can't find it anywhere.

**Comment by cviebrock** [comment]
Yeah, I removed the tag after some complaints.  The change moves the slugging to happen after the model is first saved, so the slug column would need to be nullable.

I'm working through some fixes now, so stay tuned.
