### ISSUE TITLE
Slugging after save problems

### ISSUE THREAD

**Issue by adamthehutt** [cviebrock/eloquent-sluggable#543]
[This recent change](https://github.com/cviebrock/eloquent-sluggable/commit/01805295b9878b0dde707351222357b91b008d99) caused a serious BC breakage for me related to pre-save model validation. I also question whether it's a good idea from a performance standpoint, since it adds another roundtrip to the database every time a model is saved.

Can this be configurable instead? I would think the default behavior should be to generate the slug prior to saving, but a config setting could allow that to be overridden if necessary.

I can produce a PR for this if you'd like @cviebrock.

**Comment by adamthehutt** [comment]
@cviebrock I don't know how common it is. It's a bit of a departure from the standard Laravel approach to validation. But essentially my models are all self-validating, which ensures that the same data integrity logic is applied regardless of where the model is created (e.g., a form, a webhook, an artisan command, a job, etc.) 

In this context, the validation logic says that a model has to have a slug, so when none is present during validation, the save is aborted. This isn't a huge deal and I could work around it in a few different ways, but I'd prefer not to.

Anyway, let me know what you think and if I can help. Thanks!

**Comment by cviebrock** [comment]
@adamthehutt Any chance you can try the `master` branch now?  Take a look at this:

https://github.com/cviebrock/eloquent-sluggable#when-is-a-model-slugged

Specifically, you'd need to add this to your model:

```php
    public function sluggableEvent(): string
    {
        return SluggableObserver::SAVING;
    }
```

Maybe I'll change it so the default is the old method, and make the breaking change for the next major release.  But if you can let me know if that fixes your issue, I'll move forward.

Thanks!

**Comment by adamthehutt** [comment]
@cviebrock Thank you! This fixes my specific problem, yes. 

However, fixing that issue revealed another, more serious one. [The observer's saving() method now returns false when no slug is generated](https://github.com/cviebrock/eloquent-sluggable/blob/21d0ef10cc8a01eebc6ba0d805c4f5481224fe81/src/SluggableObserver.php#L53) (e.g., because one already exists). When a Laravel observer method returns false it entirely aborts the related event. That means any time that the slugging doesn't happen (including, as far as I can tell, on a regular update) the _save is aborted entirely_. 

I restored the void return in the observer method and everything is back to working perfectly.

**Comment by robbens** [comment]
I have the exact same problem as you @adamthehutt 

This nasty hack did the trick in my translation model.

```php
public function sluggableEvent(): string
{
    return $this->wasRecentlyCreated ? SluggableObserver::SAVING : '';
}
```

**Comment by andrey-helldar** [comment]
I have two options:

#### Option 1: Using the default trait

##### Trait
```php
<?php

namespace App\Concerns\Models;

use Cviebrock\EloquentSluggable\Sluggable;

/** @mixin \Illuminate\Database\Eloquent\Model */
trait HasSluggable
{
    use Sluggable;

    public function sluggable(): array
    {
        return ['slug' => ['source' => 'title']];
    }
}
```

##### Result:
> SQLSTATE[HY000]: General error: 1364 Field 'slug' doesn't have a default value (SQL: insert into `package_spaces` (`user_service_id`, `title`, `updated_at`, `created_at`) values (1, foo, 2021-01-16 22:49:39, 2021-01-16 22:49:39))


#### Option 2: Using a custom trait

##### Trait
```php
<?php

namespace App\Concerns\Models;

use App\Observers\Sluggable as SluggableObserver;
use Cviebrock\EloquentSluggable\Sluggable;

trait HasSluggable
{
    use Sluggable;

    public static function bootSluggable()
    {
        static::observe(app(SluggableObserver::class));
    }

    public static function slugging($callback)
    {
        static::registerModelEvent('slugging', $callback);
    }

    public static function slugged($callback)
    {
        static::registerModelEvent('slugged', $callback);
    }

    public function sluggable(): array
    {
        return ['slug' => ['source' => 'title']];
    }
}
```

##### Observer
```php
<?php

namespace App\Observers;

use Cviebrock\EloquentSluggable\SluggableObserver;
use Illuminate\Database\Eloquent\Model;

class Sluggable extends SluggableObserver
{
    public function saving(Model $model): bool
    {
        return $this->generateSlug($model, 'saving');
    }

    public function saved(Model $model): bool
    {
        return true;
    }
}
```

##### Result
![image](https://user-images.githubusercontent.com/10347617/104824935-8b7c7f80-5867-11eb-931b-407792145bf4.png)

![image](https://user-images.githubusercontent.com/10347617/104824954-a0591300-5867-11eb-8307-6e23240a1a40.png)


#### Called code
```php
<?php

use App\Models\PackageSpace;
use Illuminate\Support\Facades\Artisan;

Artisan::command('foo', function () {
    PackageSpace::create([
        'user_service_id' => 1,

        'title' => 'foo',
    ]);
});
```

#### Schema
```mysql
CREATE TABLE `package_spaces` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_service_id` bigint unsigned NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_user` tinyint(1) NOT NULL DEFAULT '1',
  `is_private` tinyint(1) NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `package_spaces_user_service_id_slug_unique` (`user_service_id`,`slug`)
```

**Comment by cviebrock** [comment]
@adamthehutt I've pushed some more changes to master
- revert to using `saving` as the default event (but keep it configurable)
- fix the return values for the events to prevent event aborting

Mind giving it a test again in your case?  Thanks, and sorry for the hassle!

**Comment by cviebrock** [comment]
@andrey-helldar If you choose to configure the package to do the slugging on the `saved` event (which was going to be the new default, but I've reverted that), then your `slug` column needs to be nullable.

**Comment by andrey-helldar** [comment]
@cviebrock, according to the logic of the application, the `slug` field cannot be null.
This raises a package issue.
I changed the calls from `saved` to `saving` method, thus solving the problem.

**Comment by cviebrock** [comment]
@andrey-helldar I'm still not sure I follow you.

As it stands, the new version I plan on tagging (based on `master` right now) works identically to older versions: the models are slugged on `saving`, so your DB column can be set to `NOT NULL` because the package will set a value for that field before the model is persisted to the DB.

If you change it to use the `saved` method (which I repeat is *not* the default), then you should make your slug column nullable.  This is because the model will be saved first without the slug, then the slug is calculated and saved in a second DB query.  If the column is `NOT NULL`, then that first save will fail.

If you've got a test case that shows that it still isn't working after my most recent changes, I'd be happy to take a look.  Obviously, I don't want to break things for anyone!

**Comment by andrey-helldar** [comment]
@cviebrock, language barrier at its best 😀 (no)

I will try to write so that Google Translate will correctly translate my idea.

So, in the current release, models are slugged after writing to the database. This means I have to make the `slug` field as `NULLABLE`. But I cannot do this.

My solution is override the save methods. My working code is shown above.

In the next release, you will fix this and I will be able to remove my code from the project. And yours will remain :)

PS: Hopefully Google translated it correctly. If not, ignore it. I'll just wait for the next release 🍻

**Comment by adamthehutt** [comment]
Thanks, @cviebrock! Seems to be good now.

**Comment by andrey-helldar** [comment]
> Thanks, @cviebrock! Seems to be good now.

Power of the downgrade 😀

**Comment by cviebrock** [comment]
Thanks for the help everyone.  I've released 8.0.3 which still uses the `saving` event, so nothing should be broken for anyone.  But please: open up a new ticket if you find an issue!

**Comment by dluague** [comment]
Saving still break when updating a model because of [this](https://github.com/cviebrock/eloquent-sluggable/blob/efadd8e1c6ac3591b1ae1fc7e5643d813639ae8a/src/SluggableObserver.php#L53) because it will return true or false, if it return false Laravel will terminate the update.

**Comment by cviebrock** [comment]
@dluague Try 8.0.4 now.

**Comment by dluague** [comment]
Thanks, @cviebrock it works fine now in my end using 8.0.4.
