### ISSUE TITLE
8.0.3 causes a breaking change when applying scopeWithUniqueSlugConstraints via a trait

### ISSUE THREAD

**Issue by fourstacks** [cviebrock/eloquent-sluggable#544]
This is more of a PSA than a bug per se but as it occurred on a non-breaking point release I figured it would be worth sharing here.

In v8.0.3, the `scopeWithUniqueSlugConstraints` method was added to the `Sluggable` trait.  This is fine for anyone who has added a `scopeWithUniqueSlugConstraints` override method directly to their model but in our case we wanted to add this overridden method to multiple models.  We therefore wrapped it in a trait and applied this trait alongside the `Sluggable` trait.  

When using v8.0.3 this causes a fatal error as two traits cannot have the same method.  A couple of ways around this for anyone in a similar boat:

1 - Add a base model and add your `scopeWithUniqueSlugConstraints` override method in that model which your models then extend.

2 - Explicitly say which `scopeWithUniqueSlugConstraints` method you want to use from which trait:

```
Sluggable, // this is the package trait
ScopesSlugsToTenant  { // this is my trait
    ScopesSlugsToTenant::scopeWithUniqueSlugConstraints insteadof Sluggable;
}
```

Hope this helps anyone else in the same boat and thanks again for all your work on this package @cviebrock - I've used it on projects for years and I love working with it!

EDIT - you'll also have to ensure that your `scopeWithUniqueSlugConstraints` matches the method signature of the one in the `Sluggable` trait with the same typehints and return type

**Comment by cviebrock** [comment]
@fourstacks Ah yeah ... I probably should've been more explicit about that change.  I'll add a note to the README file.  Thanks for mentioning it!

**Comment by cviebrock** [comment]
@fourstacks Check out the note I added [here](https://github.com/cviebrock/eloquent-sluggable#extending-sluggable).  I think that'll make it clearer for folks.
