### ISSUE TITLE
Can't update current record 

### ISSUE THREAD

**Issue by d4rkr3pt0r** [cviebrock/eloquent-sluggable#546]
Hi. Here is my Category Model:
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Category extends Model
{
    use HasFactory, Sluggable;

    public $timestamps = false;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
...
```
I'm trying to update a record using the request parameters. If I change slug field to a new one `save()` would work. Otherwise won't:
```
        $category->title = $request->title;
        $category->slug = $request->slug;
        $category->description = $request->description;
        if($category->save()) { // This return false if slug is same as current slug. But it would update with a new slug

```
When I remove sluggable from my Model it's working fine. What the problem?

**Comment by cviebrock** [comment]
Are you using 8.0.4? There was a bug introduced in 8.0.3, which this sounds like.

**Comment by d4rkr3pt0r** [comment]
> 
> 
> Are you using 8.0.4? There was a bug introduced in 8.0.3, which this sounds like.

You were right. I was using 8.0.3. The problem gone by updating package to 8.0.4.
