### ISSUE TITLE
ErrorException Undefined index: slugEngineOptions

### ISSUE THREAD

**Issue by badvan** [cviebrock/eloquent-sluggable#548]
After updating with php composer update, the package stopped working. Worked great before.
I get an error while creating something.
Changed nothing, if the package files are rolled back to an older version, it starts working.
Sorry English is not my real language.

Laravel 8

ErrorException
Undefined index: slugEngineOptions
http://site.com/admin/tags

lluminate\Foundation\Bootstrap\HandleExceptions::handleError
D:\OSPanel\domains\site.com\vendor\cviebrock\eloquent-sluggable\src\Services\SlugService.php:204

        if (!array_key_exists($key, $slugEngines)) {
            $engine = new Slugify($config['slugEngineOptions']);   // line <- 204
            $engine = $this->model->customizeSlugEngine($engine, $attribute);

            $slugEngines[$key] = $engine;
        }

**Comment by cviebrock** [comment]
You probably need to update your project's `sluggable.php` configuration file with the new entries that have been added since your last version.  Just adding this should do it:

```php
    'slugEngineOptions' => [],
```

**Comment by badvan** [comment]
Thanks, helped php artisan config:clear
