### ISSUE TITLE
Want to start counting from "2"

### ISSUE THREAD

**Issue by Tamim26061** [cviebrock/eloquent-sluggable#549]
Hello sir, First of all, I want to thank you for this awesome service. But I think here should be fixed one thing then it will be great.

Suppose, I have a tag which name is "Laravel".
Then I am trying to add another tag with Laravel name then the slug created "laravel-1". But I think the slug should be created "laravel-2" Because In the database there already has "one slug called 'laravel'.
I hope I have explained it properly If not then let me know.

Thank you:) Have a great day.

**Comment by cviebrock** [comment]
That actually makes a lot of sense @Tamim26061 ... thanks!

Version 8.0.5 of the package will start counting at "2" instead of "1" for unique suffixes.  But you can also adjust it via the new `firstUniqueSuffix` configuration.

Thanks again!
