### ISSUE TITLE
Declaration of App\Models\Language::sluggable() must be compatible with Cviebrock\EloquentSluggable\Sluggable::sluggable(): array

### ISSUE THREAD

**Issue by kiwango** [cviebrock/eloquent-sluggable#550]
Am get this error in my project and am think it happen because of compose update, I don't want to make those  change incluse to add "array" how can make my project to work smoth as it 
Symfony\Component\ErrorHandler\Error\FatalError
Declaration of App\Models\Language::sluggable() must be compatible with Cviebrock\EloquentSluggable\Sluggable::sluggable(): array

**Comment by cviebrock** [comment]
You probably just need to add the return type hint to your method.

**Comment by cviebrock** [comment]
Did that solve your issue, @kiwango ?

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
