### ISSUE TITLE
Problems with canceling slugging (fireSluggingEvent)

### ISSUE THREAD

**Issue by Leshkens** [cviebrock/eloquent-sluggable#551]
My case: when the slug attribute is filled in manually, the package should not generate it.

Boot method in model:
```
protected static function boot()
{
    parent::boot();

    self::slugging(function ($model) {

        /**
         * @var Article $model
         */
        if (!is_null($model->slug)) {
            return false;
        }
    });
}
```
Getting an exception:
`Cviebrock\EloquentSluggable\SluggableObserver::fireSluggingEvent(): Return value must be of type ?array, bool returned`

<details>
  <summary>Exception screenshot</summary>
  
![image](https://user-images.githubusercontent.com/8939383/111542406-823e5f00-8793-11eb-886a-6f53c53ddc36.png)
  
</details>

**Temporarily solved the problem by overriding `SluggableObserver`**

```
public function register()
{
   $this->app->bind('Cviebrock\EloquentSluggable\SluggableObserver', 'App\Support\SluggableObserver');
}
```
```
...

protected function fireSluggingEvent(Model $model, string $event): array|bool|null
{
    return $this->events->until('eloquent.slugging: ' . get_class($model), [$model, $event]);
}

...
```

Versions:
PHP: 8.0.3
Laravel: 8.33.1
Eloquent-sluggable: 8.0.5

**Comment by cviebrock** [comment]
I'm not 100% sure, but I think just doing `return;` instead of `return false;` would solve this, no?

**Comment by Leshkens** [comment]
> I'm not 100% sure, but I think just doing `return;` instead of `return false;` would solve this, no?

I've tried using this, but it doesn't work, so does the return null. 

I understand that laravel expects exactly the return of the Boolean false.

**Comment by cviebrock** [comment]
Duplicated in #556 , so I'm closing this issue and moving the discussion there.  I think the suggestion I posted would work, but I'd be interested in a failing test case I can use to ensure it works.
