### ISSUE TITLE
how to use English title translate for slug source?

### ISSUE THREAD

**Issue by nekooee** [cviebrock/eloquent-sluggable#552]
Hi,

for translation, I used this package: https://github.com/Astrotomic/laravel-translatable

I have two models for article and article translation. 
my Article model :

```
class Article extends Model
{
    use Translatable;
    use Sluggable;

    public function sluggableEvent(): string
    {
        return SluggableObserver::SAVED;
    }

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'enTranslate.title'
            ]
        ];
    }

    protected $fillable = ['publish', 'cover'];
    public $translatedAttributes = ['title', 'content'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function enTranslate()
    {
          return $this->hasMany(ArticleTranslation::class)->where('locale','=', 'en')->take(1);
    }
}
```

and ArticleTranslation model is:
```
class ArticleTranslation extends Model
{
    public $timestamps = false;
    protected $fillable = [
        'title','content'
    ];
}
```

but I get this error:
message: "App\Models\Article::enTranslate must return a relationship instance."

how do I use the English title for slug source? please help me
thank you

**Comment by nekooee** [comment]
@cviebrock please help me, I am waiting for you.

**Comment by cviebrock** [comment]
This doesn't sound like an issue with the slug class, and I'm not familiar with that translation package.

However, if `enTranslate` is expected to return a relationship instance, then shouldn't your function look something like:
```php
    public function enTranslate()
    {
          return $this->hasMany(ArticleTranslation::class)->where('locale','=', 'en');
    }
```
i.e. don't return `->first()` or `->take(1)`?

**Comment by nekooee** [comment]
> This doesn't sound like an issue with the slug class, and I'm not familiar with that translation package.
> 
> However, if `enTranslate` is expected to return a relationship instance, then shouldn't your function look something like:
> 
> ```
>     public function enTranslate()
>     {
>           return $this->hasMany(ArticleTranslation::class)->where('locale','=', 'en');
>     }
> ```
> 
> i.e. don't return `->first()` or `->take(1)`?

thank you.
Here are two models that have a one-to-many relationship. This is separate from the translation package. 
The problem is that here, instead of one line, several lines are returned. And when first or take is used, it gives an error in both cases. 
I later found out that when I use SluggableObserver :: SAVED, the slug is not saved under any circumstances. Eventually, I did not learn how to use the package properly and because I was in a hurry I used another method.

**Comment by cviebrock** [comment]
I'm sorry to hear that my package didn't work for you.  Out of curiosity, could you post the `Translatable` trait ... or let me know which package that comes from?  I can try and figure out a solution for other users.

**Comment by cviebrock** [comment]
#
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
