### ISSUE TITLE
Slug Not Saving with  SluggableObserver::SAVED

### ISSUE THREAD

**Issue by haleyngonadi** [cviebrock/eloquent-sluggable#553]
Hi There,

I added the SluggableObserver observer to my model to save slug after a model has been created as I would like to include the primary key (id) in the slug. Without the observer, my slug saved fine but as soon as I added the sluggable observer and ID to the source, it no longer saves.

``` 
   public function sluggable(): array
  {
       return [
      'slug' => [
        'source' => ['id', 'name'],
      ]
    ];
  }

    public function sluggableEvent(): string
  {
   
    return SluggableObserver::SAVED;
  }
```

Am I missing something?

**Comment by haleyngonadi** [comment]
Thanks for your reply. I'm using Laravel Version 8.35.1

**Comment by cviebrock** [comment]
Sadly, I can't seem to duplicate this on my end.

If possible, can you make a PR with a failing test (add it to the end of `tests/BaseTests.php`) and I can investigate from there?
