### ISSUE TITLE
Slug null in view when using SluggableObserver::SAVED

### ISSUE THREAD

**Issue by tmbenhura** [cviebrock/eloquent-sluggable#554]
- Create a model using the Sluggable trait
```
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => ['id', 'surname', 'name']
            ]
        ];
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function sluggableEvent(): string
    {
        return SluggableObserver::SAVED;
    }

```
- From a FeatureTest create Models (via factory)
- Dumping the models within test shows the slug present
- However, in the view, the slug is null (via a dump as well)
- Switching to SluggableObserver::SAVING, everything works correctly excepting missing ID

There are no other observers on the model

Laravel v8.20.1
Eloquent-Sluggable 8.0.5

**Comment by cviebrock** [comment]
Sadly, I can't seem to duplicate this on my end.

If possible, can you make a PR with a failing test (add it to the end of `tests/BaseTests.php`) and I can investigate from there?

**Comment by cviebrock** [comment]
Can you test version 8.0.6 which should fix this.  Reopen if you are still having issues.

**Comment by tmbenhura** [comment]
Confirmed that it is working. Thank you, very much.
