### ISSUE TITLE
err in install

### ISSUE THREAD

**Issue by bad-robo** [cviebrock/eloquent-sluggable#555]
laravel : 6
php : 7.3

This error is displayed when I try to install the package ( localhost).

```
C:\xampp\htdocs\blog>composer require cviebrock/eloquent-sluggable:6.0
./composer.json has been updated
Running composer update cviebrock/eloquent-sluggable
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Root composer.json requires cviebrock/eloquent-sluggable 6.0 -> satisfiable by cviebrock/eloquent-sluggable[6.0.0].
    - cviebrock/eloquent-sluggable 6.0.0 requires illuminate/config ~6.0.0 -> found illuminate/config[v6.0.0, ..., v6.0.4] but these were not loaded, likely because it conflicts with ano
ther require.
Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```
composer.json file

**Comment by bad-robo** [comment]
`{
"name": "laravel/laravel",
"type": "project",
"description": "The Laravel Framework.",
"keywords": [
"framework",
"laravel"
],
"license": "MIT",
"require": {
"php": "^7.2.5|^8.0",
"fideloper/proxy": "^4.4",
"laravel/framework": "^6.20",
"laravel/tinker": "^2.5"
},
"require-dev": {
"facade/ignition": "^1.16.4",
"fakerphp/faker": "^1.9.1",
"mockery/mockery": "^1.0",
"nunomaduro/collision": "^3.0",
"phpunit/phpunit": "^8.5.8|^9.3.3"
},
"config": {
"optimize-autoloader": true,
"preferred-install": "dist",
"sort-packages": true
},
"extra": {
"laravel": {
"dont-discover": []
}
},
"autoload": {
"psr-4": {
"App\": "app/"
},
"classmap": [
"database/seeds",
"database/factories"
]
},
"autoload-dev": {
"psr-4": {
"Tests\": "tests/"
}
},
"minimum-stability": "dev",
"prefer-stable": true,
"scripts": {
"post-autoload-dump": [
"Illuminate\Foundation\ComposerScripts::postAutoloadDump",
"@php artisan package:discover --ansi"
],
"post-root-package-install": [
"@php -r "file_exists('.env') || copy('.env.example', '.env');""
],
"post-create-project-cmd": [
"@php artisan key:generate --ansi"
]
}
}`

**Comment by cviebrock** [comment]
`composer require cviebrock/eloquent-sluggable:^6.0` works for me on a fresh install of Laravel 6.20.0 on PHP 7.3.26.

Maybe try manually adding this to your `composer.json` under `require`:
```
"cviebrock/eloquent-sluggable": "^6.0"
```
then erasing `composer.lock` and the `vendor` directory, and `composer install` again.

**Comment by bad-robo** [comment]
`C:\xampp\htdocs\test.me\new-laravel>composer require cviebrock/eloquent-sluggable:^6.0
./composer.json has been updated
Running composer update cviebrock/eloquent-sluggable
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires cviebrock/eloquent-sluggable 6.0 -> satisfiable by cviebrock/eloquent-sluggable[6.0.0].
    - Conclusion: don't install laravel/framework v6.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.4.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.4.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.5.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.5.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.5.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.6.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.6.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.6.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.7.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.8.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.9.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.10.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.10.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.11.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.12.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.13.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.13.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.14.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.15.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.15.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.16.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.17.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.17.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.6 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.7 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.8 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.9 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.10 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.11 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.12 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.13 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.14 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.15 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.16 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.17 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.18 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.19 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.20 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.21 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.22 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.23 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.24 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.25 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.26 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.27 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.28 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.29 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.30 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.31 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.32 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.33 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.34 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.35 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.36 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.37 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.38 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.39 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.40 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.41 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.42 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.18.43 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.19.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.19.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.6 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.7 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.8 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.9 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.10 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.11 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.12 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.13 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.14 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.15 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.16 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.17 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.18 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.19 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.20 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.21 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.22 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.23 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.24 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.2.0 (conflict analysis result)
    - cviebrock/eloquent-sluggable 6.0.0 requires illuminate/support ~6.0.0 -> satisfiable by illuminate/support[v6.0.0, ..., v6.0.4].
    - Only one of these can be installed: illuminate/support[v4.0.0-BETA2, ..., 4.2.x-dev, v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], lara
vel/framework[v6.2.0, ..., 6.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^6.2 -> satisfiable by laravel/framework[v6.2.0, ..., 6.x-dev].


Installation failed, reverting ./composer.json to its original content.

C:\xampp\htdocs\test.me\new-laravel>
`

**Comment by bad-robo** [comment]
not work

**Comment by bad-robo** [comment]
I used another package.
https://github.com/spatie/laravel-sluggable
This is for a Persian character
https://github.com/pishran/laravel-persian-slug
