### ISSUE TITLE
registerModelEvent hook type error when returning false. Cannot turn off slugging.

### ISSUE THREAD

**Issue by jpmc3630** [cviebrock/eloquent-sluggable#556]
I have a command that uses the model to export a seperate SQLite database and I don't want to include the slug. This from the documentation used to work back on Laravel 6, but am now using Laravel 8.

```        
        Post::registerModelEvent('slugging', function ($post) {
            // the model won't be slugged
            return false;
        });
```

Now this is getting a type error because it's expecting to return an array, and if I return anything else ( including null ) it tries to slug it, and then throws an error because there is no slug column.

I thought I might be able to just unset the slug before saving, but that doesn't work.

This is the sluggable function in the model: 
```
    public function sluggable() :array
    {
        return [
            'slug' => [
                'source' => ['title']
            ]
        ];
    }
```

Versions:
"laravel/framework": "^8.12"
"cviebrock/eloquent-sluggable": "^8.0"

Thanks :)

**Comment by cviebrock** [comment]
I'm not sure I fully understand the issue.  You have a model that is persisted in MySQL (or something) and for that you want it to generate and store slugs ... so the package works just fine.  However, you are also storing the data in sqlite _without_ the slug column?

In whatever method you have to save the data to sqlite, could you not just strip the slug column there?  Something like (untested):

```php
public function saveToSqlite() {
    $data = Illuminate\Support\Arr:except($this->attributes, ['slug']);
    saveData($data);
}
```

**Comment by standaniels** [comment]
I just ran into the same issue.

As mentioned [in the docs](https://github.com/cviebrock/eloquent-sluggable/blob/master/README.md#events) the callback of the `slugging` event must return `false` when you don't want the model to be slugged. But this will result in a `TypeError`

```
TypeError : Cviebrock\EloquentSluggable\SluggableObserver::fireSluggingEvent(): Return value must be of type ?array, bool returned
```

This is because the return type of [the method `fireSluggingEvent`](https://github.com/cviebrock/eloquent-sluggable/blob/master/src/SluggableObserver.php#L93) is `null` or `array`, but on [this line](https://github.com/cviebrock/eloquent-sluggable/blob/master/src/SluggableObserver.php#L78), on which `fireSluggingEvent` is called, its return value is strictly compared to `false`, which can never be true.

**Comment by jpmc3630** [comment]
@cviebrock Yeah, that's the use case.

While we could do something like turn it into an array, it was nice being able to interact with the SQLite with eloquent. 

Here's a simplified example:

```
        $posts = Post::sinceScope($request->since)->get();

        Post::registerModelEvent('slugging', function ($Post) {
            // the model won't be slugged
            return false;
        });

        foreach ($posts as $post) {

            $mobilePostModel = new Post;
            $mobilePost = $mobilePostModel->setConnection('sqlite')->findOrNew($post->id);

            $mobilePost->timestamps = false;

            $mobilePost->id                   = $post->id;
            $mobilePost->title                = $post->title;
            $mobilePost->content         = $post->content;

            $mobilePost->setConnection('sqlite')->save();
        }
```
Anyway I'm actually good now because turns out I needed to change a couple of fields, remove timestamps etc, and have opted to make a dedicated model for the SQLite records.

But anyways, as @standaniels pointed it out, it's from your docs and is probably an easy fix for a handy feature :)

**Comment by cviebrock** [comment]
Sorry it's taken me a while to get back to this.  I'm a bit confused about Laravel's event internals, but I think if I change:

```php
if ($this->fireSluggingEvent($model, $event) === false) {
```

to

```php
if ($this->fireSluggingEvent($model, $event) === null) {
```

it should work.  Any chance you can test that manually in your app first?  If it works, I'll add it to the next version ... if I can write a test for it (if you have any ideas for that as well, it would be appreciated).

**Comment by jpmc3630** [comment]
No worries :)

That turns off slugging altogether, because by default (when slugging is on) fireSluggingEvent method returns null. 

I think 
```
if ($this->fireSluggingEvent($model, $event) === [false]) {
```
is probably the closest to the existing behaviour ( will slug by default ) and can turn off with:
```
        Beach::registerModelEvent('slugging', function ($beach) {
            // the model won't be slugged
            return [false];
        });
```
Have tested and works this way if you happy to just wrap it with array.
