### ISSUE TITLE
Not saving in Laravel 8.41 with sluggable 8.0.6

### ISSUE THREAD

**Issue by elfeffe** [cviebrock/eloquent-sluggable#559]
I just updated using composer update, and the model is not saved anymore.
The problems seems to be this line in Model.php

```
 if ($this->fireModelEvent('saving') === false) {
            return false;
        }
```

I'm still investigating

**Comment by lvoogdt** [comment]
Hi yes, got the same problem here. SlugService::52 returns false, because the attributes are not dirty. Which returns false to the the event, which cancels the saving of the model :(

```
return $this->model->isDirty($attributes);
```

**Comment by elfeffe** [comment]
Exactly, I just discovered the same

**Comment by aprokopenko** [comment]
Same issue. Pls fix asap

**Comment by valascus** [comment]
Jesus, i've been struggling for hours now because of this!

**Comment by llewellyn-kevin** [comment]
It appears I overlooked this event in my PR yesterday. Just submitted this PR which I believe should fix the problem: https://github.com/cviebrock/eloquent-sluggable/pull/560

Wanted to share in this discussion to see if I missed anything, or if the fix won't work.

**Comment by poldixd** [comment]
I've spend an evening and the morning to find the issue. today in the morning I deliberated to change my job... 😂

**Comment by zach-lum-fm** [comment]
Also ran into this issue yesterday and lost a few hours.

However, I am grateful for this package. It has saved me much more time than this small issue caused.

**Comment by cviebrock** [comment]
8.0.7 should fix this.
