### ISSUE TITLE
Not making slug unique

### ISSUE THREAD

**Issue by vtxmg** [cviebrock/eloquent-sluggable#562]
Sql throw error for duplicate slug in slug field that means it didn't make slug unique. If there exists the same slug it should have use suffix right? but it didn't ... in sluggable.php  I have made true for includetrahsed also.  

Note: Although I have created my own slug creation method (function) ... Should I write code to check unique slug on database or it will do that part itself?

**Comment by cviebrock** [comment]
Can you post your config file, and the relevant parts of your model and/or slug creation function?

**Comment by vtxmg** [comment]
config/sluggable.php

return [

    /**
     * What attributes do we use to build the slug?
     * This can be a single field, like "name" which will build a slug from:
     *
     *     $model->name;
     *
     * Or it can be an array of fields, like ["name", "company"], which builds a slug from:
     *
     *     $model->name . ' ' . $model->company;
     *
     * If you've defined custom getters in your model, you can use those too,
     * since Eloquent will call them when you request a custom attribute.
     *
     * Defaults to null, which uses the toString() method on your model.
     */

    'source' => null,

    /**
     * The maximum length of a generated slug.  Defaults to "null", which means
     * no length restrictions are enforced.  Set it to a positive integer if you
     * want to make sure your slugs aren't too long.
     */

    'maxLength' => null,

    /**
     * If you are setting a maximum length on your slugs, you may not want the
     * truncated string to split a word in half.  The default setting of "true"
     * will ensure this, e.g. with a maxLength of 12:
     *
     *   "my source string" -> "my-source"
     *
     * Setting it to "false" will simply truncate the generated slug at the
     * desired length, e.g.:
     *
     *   "my source string" -> "my-source-st"
     */

    'maxLengthKeepWords' => true,

    /**
     * If left to "null", then use the cocur/slugify package to generate the slug
     * (with the separator defined below).
     *
     * Set this to a closure that accepts two parameters (string and separator)
     * to define a custom slugger.  e.g.:
     *
     *    'method' => function( $string, $sep ) {
     *       return preg_replace('/[^a-z]+/i', $sep, $string);
     *    },
     *
     * Otherwise, this will be treated as a callable to be used.  e.g.:
     *
     *    'method' => array('Str','slug'),
     */

    'method' => function( $string, $sep ) {
        return make_slug($string);
    },

    /**
     * Separator to use when generating slugs.  Defaults to a hyphen.
     */

    'separator' => '-',

    /**
     * Enforce uniqueness of slugs?  Defaults to true.
     * If a generated slug already exists, an incremental numeric
     * value will be appended to the end until a unique slug is found.  e.g.:
     *
     *     my-slug
     *     my-slug-1
     *     my-slug-2
     */

    'unique' => true,

    /**
     * If you are enforcing unique slugs, the default is to add an
     * incremental value to the end of the base slug.  Alternatively, you
     * can change this value to a closure that accepts three parameters:
     * the base slug, the separator, and a Collection of the other
     * "similar" slugs.  The closure should return the new unique
     * suffix to append to the slug.
     */
    
    'uniqueSuffix' => null,

    /**
     * What is the first suffix to add to a slug to make it unique?
     * For the default method of adding incremental integers, we start
     * counting at 2, so the list of slugs would be, e.g.:
     *
     *   - my-post
     *   - my-post-2
     *   - my-post-3
     */
    'firstUniqueSuffix' => 2,

    /**
     * Should we include the trashed items when generating a unique slug?
     * This only applies if the softDelete property is set for the Eloquent model.
     * If set to "false", then a new slug could duplicate one that exists on a trashed model.
     * If set to "true", then uniqueness is enforced across trashed and existing models.
     */

    'includeTrashed' => false,

    /**
     * An array of slug names that can never be used for this model,
     * e.g. to prevent collisions with existing routes or controller methods, etc..
     * Defaults to null (i.e. no reserved names).
     * Can be a static array, e.g.:
     *
     *    'reserved' => array('add', 'delete'),
     *
     * or a closure that returns an array of reserved names.
     * If using a closure, it will accept one parameter: the model itself, and should
     * return an array of reserved names, or null. e.g.
     *
     *    'reserved' => function( Model $model) {
     *      return $model->some_method_that_returns_an_array();
     *    }
     *
     * In the case of a slug that gets generated with one of these reserved names,
     * we will do:
     *
     *    $slug .= $separator + "1"
     *
     * and continue from there.
     */

    'reserved' => null,

    /**
     * Whether to update the slug value when a model is being
     * re-saved (i.e. already exists).  Defaults to false, which
     * means slugs are not updated.
     *
     * Be careful! If you are using slugs to generate URLs, then
     * updating your slug automatically might change your URLs which
     * is probably not a good idea from an SEO point of view.
     * Only set this to true if you understand the possible consequences.
     */
    
    'onUpdate' => false,

    /**
     * If the default slug engine of cocur/slugify is used, this array of
     * configuration options will be used when instantiating the engine.
     */
    'slugEngineOptions' => [],

];

my custom function
function make_slug($string,$sep='-'){
    $a = ['@','`','~','^','&','*','_','&','%','#','$',];
    $string = str_replace(' ',$sep,str_replace('\\',$sep,str_replace($a,'',trim($string))));
    $a=[',',':',';','.','(',')','!','[',']','?','/','\'','"','','','',];
    $string = str_replace($a,$sep,$string);
    $string = str_replace($sep.$sep,$sep,$string);
    $string = str_replace($sep.$sep,$sep,$string);
    $string = str_replace($sep.$sep,$sep,$string);
    $string = trim($string,$sep.$sep);
    $string = trim($string,$sep);
    $string = trim($string,$sep);
    return $string;
}

**Comment by vtxmg** [comment]
@cviebrock  Please help

**Comment by cviebrock** [comment]
A few things I notice:
1. In your config:
```php
'source' => null,
```
So you have no explicit source string for your model's slugs.  It will then use the `toString()` method on your model.  Is that defined anywhere?  In general, I suggest you be explicit about the fields you want to use for the slug, e.g.
```php
'source' => 'title'
```

2. Your custom function is:
```php
function make_slug($string,$sep='-'){
```
but your config says:
```php
 'method' => function( $string, $sep ) {
        return make_slug($string);
    },
```
I think you forgot to add the `$sep` parameter to that call.

**Comment by vtxmg** [comment]
For 'source' I have mentioned in Model. 

& make_slug function has default '-' in $sep so it is ok I think. Again I found error for duplicate slug :(

**Comment by vtxmg** [comment]
I found the reason :) it is because of lower and upper case issue.

**Comment by hasnat-we** [comment]
For my case I had 'static' keyword in model event callback like following.
`static::saving(static function(Post $post) {}`
When I removed 'static' keyword then SlugService::createSlug() was able to generate and save unique slug.
Thanks
