### ISSUE TITLE
How To Use Arabic Language In Slug

### ISSUE THREAD

**Issue by Osama-96** [cviebrock/eloquent-sluggable#564]
Hello

My Arabic title changes to latin letters in the slug
How to save it as arabic litters?
**Thank you!**

**Comment by cviebrock** [comment]
Sorry for the delayed response.

The underlying package used to handle the slugging (cocur/slugify) by default "latinizes" all the strings passed to it.  I think the idea was that these slugs would typically be used for URLs, and non-Latin characters might cause issues.

You can configure a different slugging method that works with Arabic characters.  You can use Laravel's default `Str::slug` method:

```php
'method' => ['Illuminate\\Support\\Str', 'slug'],
```

Or create your own class that handles Arabic better, and pass that in.  If you search through the closed issues, there are several others who ran into this, and there are a few posted solutions.
