### ISSUE TITLE
Slug on 2 columns

### ISSUE THREAD

**Issue by alextoader** [cviebrock/eloquent-sluggable#568]
Hi cviebrock ,
Thanks for amazing library.

I have a situation where the slugs should be per user_id. The unique index in DB is drawing_name + user_id. The drawing table has drawings but they only need to be unique per user.
So I need a slug which looks something like 
drawing_name_[user_id]_[slug_increment]
I read the docs but cant figure out how to do it. Is it possible to do this please very much?

**Comment by vidux** [comment]
Hi, im just a user of this library. you can use inside in model like this. I don't know about two tables. but if same columns in same table you can use like this



```
<?php
use Cviebrock\EloquentSluggable\Sluggable;

class ExampleModel extends Model
{
    use Sluggable;


public function sluggable(): array
{
    return [
        'slug' => [
            'source' => ['user_id', 'drawing_name']
        ]
    ];
}
```

**Comment by alextoader** [comment]
Thanks @vidux this could be it.
