### ISSUE TITLE
Slugify not found

### ISSUE THREAD

**Issue by mahdisoftdev** [cviebrock/eloquent-sluggable#571]
hellow,when i am using this package to create slug,I faced the error like this:
Class 'Cocur\Slugify\Slugify' not found
and here is my model:
`use Cviebrock\EloquentSluggable\Sluggable;
class Article extends Model
{

    use Sluggable;

    public function sluggable():array
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }`

and its my controller
`use \Cviebrock\EloquentSluggable\Services\SlugService;
 if(empty($request->slug)){         
               $slug=SlugService::CreateSlug(Article::class,'slug',$request->name);   
            }else{
                $slug = $request->slug;
            }`

**Comment by cviebrock** [comment]
That seems really odd.  Maybe try deleting your `vendor` directory and re-running `composer install`?

**Comment by mahdisoftdev** [comment]
I ran `composer install` and my problem has been solved. thanks to @cviebrock ;
