### ISSUE TITLE
BelongsToMany relation

### ISSUE THREAD

**Issue by neway02** [cviebrock/eloquent-sluggable#575]
Hi. Thank you very much for this package.
Is it possible to make a slug in a pivot table? I have a Categories table and a Languages table. I have a pivot table category_language where I store category translations. It contains id, category_id, language_id, title, slug attributes. I'd like to automatically title the slug in this pivot table when I save Category model. Any ideas for this?

**Comment by neway02** [comment]
![1](https://user-images.githubusercontent.com/25829053/149368591-6b655f0a-f33f-400c-a85f-5695e917cbae.png)

CategoryController

		$category = Category::create();
		$category->translations()->attach(1, ['title' => 'Тест 1']);

CategoryModel

	public function translations()
	{
		return $this->belongsToMany(Language::class, 'category_language', 'category_id', 'language_id')
			->as('translate')
			->withPivot('title', 'slug');
	}

**Comment by cviebrock** [comment]
I've not tried this myself, but I suspect you'd need to use a [custom pivot model](https://laravel.com/docs/8.x/eloquent-relationships#defining-custom-intermediate-table-models) and that pivot model would need to implement the Sluggable package.

**Comment by neway02** [comment]
Thanks for the answer. I was hoping that this way of working has already been used by someone. But it's not a problem. Thanks again

**Comment by neway02** [comment]
If anyone needs to find a solution to use the module along with a pivot table.
- Need to create a pivot table class
- In this table, according to the instructions, we configure eloquent-sluggable
- When defining a belongstomany relationship, use ->using(PivotTable::class)
