### ISSUE TITLE
how to ignore current slug for unique on SlugService::createSlug when update model

### ISSUE THREAD

**Issue by nekooee** [cviebrock/eloquent-sluggable#579]
Hi,
I use the following code to set the slug:
$slug = SlugService::createSlug(Article::class, 'slug', $request->input('slug'));

but when updating the model, a number is added to the slug. how to ignore the current slug for unique?

Thank you

**Comment by vishal-gc** [comment]
Hi,
I'm going through the same situation recently, I found the solution. When you updating your model just pass model instance of current article like this.

$article = Article::find($id);
$slug = SlugService::createSlug($article, 'slug', $request->input('slug));

**Comment by vishal-gc** [comment]
> Hi, I use the following code to set the slug: $slug = SlugService::createSlug(Article::class, 'slug', $request->input('slug));
> 
> but when updating the model, a number is added to the slug. how to ignore the current slug for unique?
> 
> Thank you

Hi,
I'm going through the same situation recently, I found the solution. When you updating your model just pass model instance of current article like this.

$article = Article::find($id);
$slug = SlugService::createSlug($article, 'slug', $request->input('slug));
