### ISSUE TITLE
Slug still duplicated when generate new one with exact same title

### ISSUE THREAD

**Issue by Fliw** [cviebrock/eloquent-sluggable#580]
Please be sure you include all the relevant information in your issue so we can help you:

- [ ] steps taken to reproduce your issue
1. value of config in sluggable.php is unique = true
2. the source of slug is title
3. creating new record on database, with same title generating duplicate entry (using soft deletes)
- [ ] your configuration file(s), where relevant
```php
'unique' => true,
```
- [ ] a copy of your Models that use or extend this package (just the relevant parts!)
```php
/**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
```
**Thank you!**

**Comment by Fliw** [comment]
also already set the includeTrashed to true

**Comment by Fliw** [comment]
Solved it by creating new getter with now() on models based on title, change the source of sluggable to that getter now it's working.

**Comment by hasnat-we** [comment]
For my case I had 'static' keyword in model event callback like following.
`static::saving(static function(Post $post) {}`
When I removed 'static' keyword then SlugService::createSlug() was able to generate and save unique slug.
Thanks
