### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by LyonelZ** [cviebrock/eloquent-sluggable#593]
Good afternoon,

I tried to update to Laravel 10 today and got the following error from composer,

````
 Problem 1
    - Root composer.json requires cviebrock/eloquent-sluggable ^9.0 -> satisfiable by cviebrock/eloquent-sluggable[9.0.0].
    - Only one of these can be installed: illuminate/config[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0, v10.0.0], laravel/framework[v10.0.0]. laravel/framework replaces illuminate/config and thus cannot coexist with it.
    - cviebrock/eloquent-sluggable 9.0.0 requires illuminate/config ^9.0 -> satisfiable by illuminate/config[v9.0.0, ..., v9.52.0].
    - Root composer.json requires laravel/framework ^10.0 -> satisfiable by laravel/framework[v10.0.0].
````

Please let me know if there is something I am doing wrong.

Thanks

**Comment by evan70** [comment]
same problem here,
i try to install > `composer require cviebrock/eloquent-sluggable:dev-master`
but > 
```
  Problem 1
    - Root composer.json requires cviebrock/eloquent-sluggable dev-master -> satisfiable by cviebrock/eloquent-sluggable[dev-master].
    - cviebrock/eloquent-sluggable dev-master requires illuminate/config ^9.0 -> found illuminate/config[v9.0.0, ..., v9.52.0] but these were not loaded, likely because it conflicts with another require.
```

**Comment by anwardote** [comment]
getting same error  :-(

**Comment by miagg** [comment]
PR #591 is already open. Let's hope it gets merged soon. 🤞

**Comment by jamesautodude** [comment]
Same errors for me :/ Grr lol

**Comment by jamesautodude** [comment]
> miagg

Should we maybe just fork this and make a new public repo? Last update was a long time ago and author sounds hesitant from a prior pull request...

**Comment by d3v4nt** [comment]
+

**Comment by d3v4nt** [comment]
+1

**Comment by cviebrock** [comment]
@jamesautodude Or maybe author has a full-time job and doesn't just blindly accept pull requests without testing them himself first.  Give me time, or use some other package.

**Comment by jamesautodude** [comment]
> @jamesautodude Or maybe author has a full-time job and doesn't just blindly accept pull requests without testing them himself first. Give me time, or use some other package.

No reason to get upset, just making a simple statement

**Comment by cviebrock** [comment]
I wasn't upset, just stating the benefits of using Open Source software. 😄 

You can test the 10.0.0 release I just pushed now.

**Comment by evan70** [comment]
Thx, i had a bad forkz ideas yesterday ... ;)
