### ISSUE TITLE
Should findBySlugOrFail return Model instead?

### ISSUE THREAD

**Issue by WalrusSoup** [cviebrock/eloquent-sluggable#596]
Running into an oddity with larastan, which reports this:

```
Access to an undefined property Illuminate\Database\Eloquent\Collection|Illuminate\Database\Eloquent\Model::$id.
```

when calling the function `findBySlugOrFail` 

[this function](https://github.com/cviebrock/eloquent-sluggable/blob/master/src/SluggableScopeHelpers.php#L82) has a docblock which says it can return a collection:

```
@return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection
```
however, I don't believe this is capable of returning a collection due to underlying call only returning an instance of a model or throwing:

```php
return static::whereSlug($slug)->firstOrFail($columns);
```

**Comment by cviebrock** [comment]
Thanks!  Fixed this and it'll go out in the next release.
