### ISSUE TITLE
Turkish character slug problem

### ISSUE THREAD

**Issue by mertcan-tas** [cviebrock/eloquent-sluggable#598]
While slugging some Turkish characters, it updates incorrectly. I made the 'onUpdate' status true in my config file, then the characters I specified below in any updated data are translated incorrectly.

**Example**
kompresörler => kompresoerler
ö => oe (false)
ö => o (true)

**Comment by Hesesses** [comment]
Having the same problem with Finnish letters.

For example a city called Jyväskylä should become "jyvaskyla", not "jyvaeskylae"

**Comment by cviebrock** [comment]
@Hesesses Finnish conversion should already be handled by cocur/slugify, so you likely just need to configure it for your models:

```php
    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title',
                'slugEngineOptions' => [
                    'ruleset' => 'finnish'
                ]
            ]
        ];
    }
```

I'm updating the docs with details, since this is such a common question. :)

**Comment by cviebrock** [comment]
https://github.com/cviebrock/eloquent-sluggable?tab=readme-ov-file#slugengineoptions

**Comment by Hesesses** [comment]
Thank you 🙏
