### ISSUE TITLE
Is it possible to use the slug as source?

### ISSUE THREAD

**Issue by mvynhb** [cviebrock/eloquent-sluggable#600]
Hi, thanks for the great package!

I am trying to generate a unique slug without depending on another column. I just want to generate a unique slug from a title that does not get saved on the model.

I tried doing this but it didn't work:

```php
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'slug'
            ]
        ];
    }
```

I know I can use the `SlugService::createSlug` method on the title and assign it to the slug such as

```php
$post->slug =  SlugService::createSlug(Post::class, 'slug', 'My First Episode');
```

But I want to also use the `scopeWithUniqueSlugConstraints` method to have a custom unique slug. 

Is there an easy way to achieve this?

**Comment by cviebrock** [comment]
I think the point of this package was to create unique slugs and save them on the model.  If you aren't saving the slug anywhere, then it would be difficult to guarantee uniqueness ... no?

I'm unsure as to what you are trying to do.  The slug field can't be generated from itself; that's a chicken-and-egg loop, no?

**Comment by cviebrock** [comment]
To be honest, then ... I don't think you need this package.  Just generate the text however you want, check for uniqueness, and save it to the model.

If you wanted, I suppose you could make a custom getter that is only used for generating the string.  Something like this (untested):

```php
class Person extends Eloquent
{
    use Sluggable;

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'source'
            ]
        ];
    }

    public function getSourceAttribute(): string
    {
        // ... your logic here that generates a slug string ...
        return $string'
    }
}
```

In this case `source` would not be a field in the DB so isn't every accessed except by the slugging package. You could maybe make it a `private` or `protected` method to be sure it isn't accessed outside the model as well.

Would that work?

**Comment by mvynhb** [comment]
Thanks for the suggestions, yes I think you are right that my use case is not really meant for this package. I just could not find any other package that offers all the sluggable features/options you offer out of the box.

Thanks for the example will check it out!
