### ISSUE TITLE
SluggableScopeHelpers Trait: Support for orWhere and whereIn

### ISSUE THREAD

**Issue by thenatsky** [cviebrock/eloquent-sluggable#601]
While this may just be syntactic sugar, it would be nice to have support for 

`$posts = Post::whereSlugIn($arrayOfSlugStrings)->get();`
`$posts = Post::whereSlug($slugString1)->orWhereSlug($slugString2)->get();`

**Comment by cviebrock** [comment]
Old issue, and I don't want to overload things with, as you say, syntactic sugar.
