### ISSUE TITLE
Slugging with Laravel Nova

### ISSUE THREAD

**Issue by mik3lov3st3ch** [cviebrock/eloquent-sluggable#602]
Thanks Colin for that useful Laravel component! It´s a great help...
One issue though in combination with Laravel Nova: When a new entity for a model is created, the slug is not created. It looks like the "saving" or "saved" lifecycle hooks are not called by Nova and therefore the slug isn´t created.

**Steps to reproduce:**
- Install Laravel 10.0 + Laravel Nova 4.0
- Install eloquent-sluggable
- Create a model with a sluggable property
- Create a new entity of the model with the Nova UI

**Result:**
The new entity is created but the sluggable field is not filled. If I create a model via a laravel service, a factory or tinker, the sluggable field is filled as it should be.

**Comment by mik3lov3st3ch** [comment]
Ok, it was my fault - all events are fired as expected.
BTW one side note on switching the default event from "saving" to "saved": In my case the slug fields are set to "not nullable" in the database, which would lead to exceptions if a new entity is stored (cause the slug field doesn´t exist on the first save). I´m sure you know about that possible issue - only wanted to mention it.

**Comment by mik3lov3st3ch** [comment]
Closed...

**Comment by cviebrock** [comment]
Glad to have helped! 😉 

What did the problem end up being?  That way, anyone else with the same issue that searches and lands here will get the benefit of your experience!

**Comment by mik3lov3st3ch** [comment]
It was simply a stupid mistake :) I've set a field as sluggable that was not set as required in Nova (even not shown). As no error was thrown (slug is simply null) I ran in the wrong direction assuming that the saving events might not be fired. Time for weekend 😆
