### ISSUE TITLE
Remove HTML Tags Before Creating Slug

### ISSUE THREAD

**Issue by chard1988** [cviebrock/eloquent-sluggable#603]
Not an issue but an inquiry on the package usage.

I'm using this package on one of my projects. I have a third party api that returns collection of courses. Most of the course title contains html tags like `<sup></sup>`. Question is, how can I remove those tags on model creation? This means cleaning up the string before slugging.

Thank you so much for this great package.

**Comment by chard1988** [comment]
What I've tested so far is listening for creating and updating events on the `course` model with the code as follows

`
protected static function boot()
    {
        parent::boot();

        /**
         * Listen for the creating event.
         * Clean course_name and set as slug
         */
        static::creating(function ($model) {
            $name = strip_tags($model->course_name);
            $model->setAttribute('slug', Str::slug($name));
        });

        /**
         * Listen for the updating event.
         * Clean course_name and set as slug
         */
        static::updating(function ($model) {
            $name = strip_tags($model->course_name);
            $model->setAttribute('slug', Str::slug($name));
        });
    }
`

Is there a better or cleaner way to achieve the same result?

**Comment by chard1988** [comment]
Retracted my code and just used the `method`.

![image](https://github.com/cviebrock/eloquent-sluggable/assets/24698545/fa34e496-c673-492f-9284-7d1dc1c03710)

**Comment by cviebrock** [comment]
Hi @chard1988 .. I was going to suggest something similar: create a model method that does the HTML-stripping for you, and then use that as the source.  e.g.:

```php
public function sluggable(): array {
  return [
    'slug' => [
      'source' => 'stripped_source'
    ]
  ];
}

public function getStrippedSourceAttribute(): string {
  return strip_tags($this->courseName . ' ' . $this->UUID);
}
```

Your solution works just as well.  Either of those would probably be preferable to linking into the event system.
