### ISSUE TITLE
Tag 11.0 version. Laravel 11 just landed 🌕  🚀 

### ISSUE THREAD

**Issue by pxpm** [cviebrock/eloquent-sluggable#609]
Hey @cviebrock 

Thanks for your work 🙏 

I saw you already merged the Laravel 11 support PR. Let me know if there is something else to be done before tagging 11.0 that I can help you with. 

Cheers

**Comment by akr4m** [comment]
Until the final release use dev branch `11.0.x-dev`

**Comment by cviebrock** [comment]
Version 11.0.0 is hot off the presses!
