### ISSUE TITLE
Transliterating Arabic strings into Latin characters

### ISSUE THREAD

**Issue by AhmedBouchta** [cviebrock/eloquent-sluggable#615]
Arabic text is being transliterated into Latin characters for slug generation. 

For example, the string "يلعب الكرة" is being saved as "ylaab-lkr" instead of "يلعب-الكرة".

**Comment by AhmedBouchta** [comment]
I customized the method in Model to allow for Arabic letters, and it is working just as expected.
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'word',
                'onUpdate' => true,
                'unique' => true,
                'method' => static function(string $string, string $separator): string {
                // Allow Arabic letters
                return strtolower(preg_replace('/[^a-zA-Z\x{0600}-\x{06FF}]+/u', $separator, $string));
},
            ],
        ];
    }

**Comment by cviebrock** [comment]
Hi @AhmedBouchta ... the default behaviour is to convert the strings into "ASCII" slugs.  The reason being you probably want to use them for generating nice URLs for things like `example.com/activities/ylaab-lkr`.

Of course, URLs _can_ contain non-ASCII characters, but in practice I don't think many do.

In your case, if you just want a lower-case, simplified version of your Arabic string, then I think your code is the way to go.  Although you might want to add `0-9` in your regex as well, and then trim off any `$separators` from the front and end of the string. 😄

**Comment by AhmedBouchta** [comment]
I see, thank you @cviebrock
