### ISSUE TITLE
Using sluggable while using eloquent outside laravel

### ISSUE THREAD

**Issue by ryanhightower** [cviebrock/eloquent-sluggable#63]
I'm also trying to use Eloquent in a vanilla PHP application and I would like to include "sluggable". I get an error that the class "App" doesn't exist (in SluggableTrait.php:210) when I try to use sluggify(). Since I'm not using Laravel I don't have the "App" class. Any suggestions?

**Comment by lostcause** [comment]
Could you go intro further detail, I am having the same problem, and maybe some others will, so I guess a solution would be nice to be posted in here. Thank you!
