### ISSUE TITLE
Update to latest version broke SLUG

### ISSUE THREAD

**Issue by cerw** [cviebrock/eloquent-sluggable#69]
Hi
I have been using this package for months now and since yesterday i am getting:

1364 Field 'slug' doesn't have a default value

It seems it does not render the slug anymore?

**Comment by cviebrock** [comment]
Sorry I didn't follow up sooner.

I'm sure you've come up with a solution in the meantime, but just to let you know that the new version of Sluggable handles boot events better, so I don't think you should see this kind of error anymore.

**Comment by cerw** [comment]
Softdelete was part of the issue too  fixed now :)
