### ISSUE TITLE
How can I check for uniqueness based on another model?

### ISSUE THREAD

**Issue by LeBlaaanc** [cviebrock/eloquent-sluggable#75]
I have ```Parent``` and ```Child``` models. I'd like Child to be unique based on the Parent then the Child slug so I would end up with a URL ```/{parent_slug}/{child_slug}```. It looks like I need to override ```getExistingSlugs($slug)``` and pass in the $parent somehow to it to find if it's unique to that parent? Does this seem right? How do I pass the $parent_slug to the method if so?

Thanks for your help :)

**Comment by cviebrock** [comment]
Currently, I don't think this is easily done.  But there are two merge requests pending for adding some kind of `scope` configuration so that you can more easily do this.  If you're patient, it should come soon.  :)
