### ISSUE TITLE
Generate slug for existing records 

### ISSUE THREAD

**Issue by dan-klasson** [cviebrock/eloquent-sluggable#76]
Right now it only creates a migration. Would be nice to have a command that creates slugs for existing records in that table. Even nicer with a `--seed` flag that also creates a seed file for it.

**Comment by cviebrock** [comment]
Sorry I never responded to this sooner.  If you still need this, and the `master` branch can't do it for you, please submit an MR again and I'll add it.

**Comment by wessodesigner** [comment]
I found that this problem has been solved. What command should I use in order to create slugs for preexisting records?

**Comment by dan-klasson** [comment]
First you need to copy this file over:

https://github.com/dan-klasson/eloquent-sluggable/commit/4cdf214834420b8383c67bd6624c105e4b8d9e0b

Then to run you do `slugs:create`.

Was planning to create a new pull request for this but never got around to it.

**Comment by wessodesigner** [comment]
@dan-klasson 

Thank you for your response. As I am still a Laravel newbie, can you please tell me where to copy the file?

Thanks.

**Comment by kenmoini** [comment]
Has this been merged into the master branch?  It'd be rather handy to batch create the slugs for existing table rows and a seemingly important feature

**Comment by dan-klasson** [comment]
@kenmoini: I don't think it has. I haven't used Laravel in ages. At work now but I'll try to clean up the code a bit and submit a new pull request when I get home.

**Comment by dan-klasson** [comment]
Another pull request created. Please merge:

https://github.com/cviebrock/eloquent-sluggable/pull/208

**Comment by vvictorov** [comment]
Working with Laravel 5.5. You have to place it in App\Console and include it in the $commands array in Kernel.php

`<?php namespace App\Console;

use Illuminate\Console\Command;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputArgument;
use \Cviebrock\EloquentSluggable\Services\SlugService;

class CreateSlugsCommand extends Command {

	/**
	 * The console command name.
	 *
	 * @var string
	 */
	protected $name = 'slugs:create';

	/**
	 * The console command description.
	 *
	 * @var string
	 */
	protected $description = 'Create slugs for Model.';

	/**
	 * Create a new command instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		parent::__construct();
	}

	/**
	 * Execute the console command.
	 *
	 * @return mixed
	 */
	public function handle()
	{
		$model_name = ucfirst($this->argument('model'));
		
		$model = new $model_name;
		
		try
		{
		    $model = new $model_name;
		}
		catch(Exception $e)
		{
		    $this->error('The model was not found');
		}
        $result = $model::all();
        
        foreach($result as $item) {
			$field = $item->sluggable()['slug']['source'];
			$slug = SlugService::createSlug($model, 'slug', $item->$field);
			$item->slug = $slug;
			$item->save();
        }
	}

	/**
	 * Get the console command arguments.
	 *
	 * @return array
	 */
	protected function getArguments()
	{
		return array(
			array('model', InputArgument::REQUIRED, 'The model you want to update the slugs for.'),
		);
	}

	/**
	 * Get the console command options.
	 *
	 * @return array
	 */
	protected function getOptions()
	{
		return array(
			array('force', null, InputOption::VALUE_NONE, 'Overwrite existing slugs.', null),
		);
	}

}`

**Comment by adriandmitroca** [comment]
I've found a much quicker way to achieve this basically with no coding at all.

```php
config(['sluggable.onUpdate' => true]);
Model::all()->each->save();
```

**Comment by dapseen** [comment]
This feature is hidden, its not in the doc
