### ISSUE TITLE
International languages/characters conversion/support

### ISSUE THREAD

**Issue by jonagoldman** [cviebrock/eloquent-sluggable#93]
I could not find it in the docs, does this library supports different languages conversions?
If I try for example to make a slug of Russian characters will it fail or will some kind of conversion take place? like in this package https://github.com/cocur/slugify
Thanks.

**Comment by cviebrock** [comment]
I plan to switch to `cocur/slugify` instead of `Str::slug` as the default slugging engine.  You can see my response to issue #98 for how to do it in the meantime.
