### ISSUE TITLE
Allow to manually set slug to avoid problems when 'build_from' field is null

### ISSUE THREAD

**Issue by jonagoldman** [cviebrock/eloquent-sluggable#95]
If my 'build_from' db field is null, and 'unique' set to true, then the slug will be something like `'-1'`, `'-2'`, `'-3'` ...
In some cases, I want the slug to be null.
If I try to save the slug manually by doing something like `$model->slug = null; $model->save()` then the slug will be automatically generated.

**Comment by cviebrock** [comment]
Do you still see this behaviour? If so, just reopen this issue.
