### ISSUE TITLE
Not use sluggable in a child model

### ISSUE THREAD

**Issue by evalenzuela** [cviebrock/eloquent-sluggable#97]
I have a model which is extending from a 'sluggable' model, but it ask me to have the slug field (I am using this field in table to save slug text), but I do not want to use it in this child, because the one which should save the slug is the parent, how do I disable slug generation on child class?

**Comment by cviebrock** [comment]
So ... your base model class uses Sluggable, but for a child model class that extends the base model you want to disable it?

Seems like a weird way to architect things, honestly.  But, if you needed to, you could probably just overload the method in the child.  Something like:

```php
public function sluggify($force=false)
{
	// do nothing
	return $this;
}
```
